Repository mathesar-foundation/mathesar, pull requests merged in 2022-11, with the labels that each got.

#1865 Fix array aggregation for some custom types
  db/functions/base.py
  db/types/custom/email.py
  db/types/custom/money.py
  db/types/custom/underlying_type.py
  db/types/custom/uri.py
Labels: status: review

#1903 Change helpText from prop to slot in NameAndDescInputModalForm
  mathesar_ui/src/component-library/alert/Alert.svelte
  mathesar_ui/src/components/NameAndDescInputModalForm.svelte
  mathesar_ui/src/pages/database/AddEditSchemaModal.svelte
  mathesar_ui/src/pages/database/SchemaRow.svelte
Labels: status: review

#1898 Add some information to query column metadata
  db/queries/base.py
  db/transforms/base.py
  mathesar/models/query.py
  mathesar/tests/api/query/test_library_demo_reports.py
  mathesar/tests/api/query/test_query_columns_api.py
  mathesar/tests/api/query/test_query_results.py
  mathesar/tests/api/query/test_query_run.py
Labels: work: backend, status: review

#1910 Atleast one cell always selected when user is on the table page
  mathesar_ui/src/components/sheet/SheetSelection.ts
  mathesar_ui/src/systems/table-view/Body.svelte
  mathesar_ui/src/systems/table-view/TableView.svelte
Labels: status: review

#1907 Live Demo Multitenancy setup
  .env.example
  config/settings.py
  db/install.py
  demo/install.py
  demo/middleware.py
  demo/resources/library_add_checkouts.sql
  demo/resources/library_without_checkouts.sql
  demo/settings.py
  docker-compose.yml
  initial_setup.sh
  install.py
  mathesar/api/db/viewsets/data_files.py
  mathesar/api/db/viewsets/links.py
  mathesar/api/db/viewsets/queries.py
  mathesar/api/dj_filters.py
  mathesar/apps.py
  mathesar/database/base.py
  mathesar/state/django.py
  mathesar/tests/api/test_database_api.py
  mathesar/tests/api/test_schema_api.py
  mathesar/tests/test_multi_db.py
  mathesar/views.py
  setup.cfg
Labels: status: review

#1904 Fixes #1790, changing the column selection in the "Columns to Move" field updates selection
  mathesar_ui/src/components/sheet/SheetSelection.ts
  mathesar_ui/src/systems/table-view/table-inspector/column/column-extraction/ExtractColumnsModal.svelte
Labels: status: review

#1908 Arrow keys on primary column
  mathesar_ui/src/components/cell-fabric/data-types/components/primary-key/PrimaryKeyCell.svelte
Labels: status: review

#1914 Fix bug in query parameter loading
  mathesar/api/db/viewsets/queries.py
Labels: status: review

#1902 Add Database Role permissions
  config/settings.py
  mathesar/api/db/permissions/__init__.py
  mathesar/api/db/permissions/database.py
  mathesar/api/exceptions/mixins.py
  mathesar/api/ui/permissions/database_role.py
  mathesar/api/ui/serializers/users.py
  mathesar/api/ui/viewsets/users.py
  mathesar/tests/api/test_user_api.py
  mathesar/tests/conftest.py
Labels: status: review

#1850 Schema page re design
  mathesar_ui/src/App.svelte
  mathesar_ui/src/component-library/anchorButton/AnchorButton.scss
  mathesar_ui/src/component-library/anchorButton/AnchorButton.svelte
  mathesar_ui/src/component-library/button/Button.scss
  mathesar_ui/src/component-library/common/styles/variables.scss
  mathesar_ui/src/component-library/dropdown-menu/DropdownMenu.svelte
  mathesar_ui/src/component-library/index.ts
  mathesar_ui/src/component-library/menu/LinkMenuItem.svelte
  mathesar_ui/src/component-library/menu/Menu.scss
  mathesar_ui/src/component-library/styles.scss
  mathesar_ui/src/component-library/tabs/Tab.svelte
  mathesar_ui/src/component-library/tabs/TabContainer.scss
  mathesar_ui/src/component-library/tabs/TabContainer.svelte
  mathesar_ui/src/component-library/text-input/TextInputWithPrefix.svelte
  mathesar_ui/src/component-library/tutorial/Tutorial.scss
  mathesar_ui/src/components/AppSecondaryHeader.svelte
  mathesar_ui/src/components/EditTableHOC.svelte
  mathesar_ui/src/components/NameAndDescInputModalForm.svelte
  mathesar_ui/src/components/OnPageFilterBar.svelte
  mathesar_ui/src/components/PageTitleAndMeta.svelte
  mathesar_ui/src/components/TableName.svelte
  mathesar_ui/src/icons/index.ts
  mathesar_ui/src/pages/database/AddEditSchemaModal.svelte
  mathesar_ui/src/pages/schema/CreateEmptyTableButton.svelte
  mathesar_ui/src/pages/schema/CreateNewExplorationTutorial.svelte
  mathesar_ui/src/pages/schema/CreateNewTableButton.svelte
  mathesar_ui/src/pages/schema/CreateNewTableTutorial.svelte
  mathesar_ui/src/pages/schema/EditTable.svelte
  mathesar_ui/src/pages/schema/EmptyEntity.svelte
  mathesar_ui/src/pages/schema/EntityLayout.svelte
  mathesar_ui/src/pages/schema/ExplorationItem.svelte
  mathesar_ui/src/pages/schema/ExplorationsList.svelte
  mathesar_ui/src/pages/schema/OverviewHeader.svelte
  mathesar_ui/src/pages/schema/SchemaExplorations.svelte
  mathesar_ui/src/pages/schema/SchemaOverview.svelte
  mathesar_ui/src/pages/schema/SchemaPage.svelte
  mathesar_ui/src/pages/schema/SchemaTables.svelte
  mathesar_ui/src/pages/schema/TableItem.svelte
  mathesar_ui/src/pages/schema/TablesList.svelte
  mathesar_ui/src/routes/DataExplorerRoute.svelte
  mathesar_ui/src/systems/data-explorer/urlSerializationUtils.ts
  mathesar_ui/src/systems/table-view/table-inspector/table/RenameTable.svelte
  mathesar_ui/src/typeUtils.ts
  mathesar_ui/src/utils/tables.ts
Labels: status: review

#1931 Save description for explorations
  mathesar/migrations/0007_auto_20221115_0627.py
  mathesar/models/query.py
  mathesar/tests/api/query/test_query_api.py
Labels: status: review

#1927 add new div cell and style
  mathesar_ui/src/components/cell-fabric/data-types/components/select/SingleSelectCell.svelte
Labels: status: review

#1915 Improve client side validation within link table dialog
  mathesar_ui/src/systems/table-view/link-table/LinkTableModal.svelte
Labels: status: review

#1929 1701 Improve UX after columns are extracted to a new table
  mathesar_ui/src/components/sheet/SheetSelection.ts
  mathesar_ui/src/components/sheet/index.ts
  mathesar_ui/src/stores/table-data/index.ts
  mathesar_ui/src/systems/table-view/row/RowCell.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/column-extraction/ExtractColumnsModal.svelte
Labels: status: review

#1900 Implement default summarization algorithm
  db/columns/operations/select.py
  db/queries/base.py
  db/tables/operations/select.py
  db/tests/queries/conftest.py
  db/tests/transforms/__init__.py
  db/tests/transforms/test_finish_specifying_summarization.py
  db/transforms/base.py
  db/transforms/operations/finish_specifying.py
Labels: work: backend, status: review

#1940 avoid deleting valid constraints
  mathesar/state/django.py
Labels: status: review

#1937 Removed Sphinx from codebase
  Makefile
  README.md
  docker-compose.yml
  docs/conf.py
  docs/index.rst
  initial_setup.sh
  make.bat
  requirements-dev.txt
  run.sh
Labels: status: review

#1949 Expose live demo mode flag
  mathesar/views.py
Labels: status: review

#1932 Add new abstraction to help with form validation, and use it within the "Extract Columns" modal
  mathesar_ui/src/component-library/alert/Alert.scss
  mathesar_ui/src/component-library/alert/Alert.svelte
  mathesar_ui/src/component-library/alert/AlertTypes.ts
  mathesar_ui/src/component-library/cancel-or-proceed-button-pair/CancelOrProceedButtonPair.svelte
  mathesar_ui/src/component-library/common/types/ComponentAndPropsTypes.ts
  mathesar_ui/src/component-library/labeled-input/LabeledInput.scss
  mathesar_ui/src/component-library/labeled-input/LabeledInput.svelte
  mathesar_ui/src/component-library/spinner-button/SpinnerButton.svelte
  mathesar_ui/src/components/SelectProcessedColumns.svelte
  mathesar_ui/src/components/form/Field.svelte
  mathesar_ui/src/components/form/FieldWrapper.svelte
  mathesar_ui/src/components/form/FormSubmit.svelte
  mathesar_ui/src/components/form/__meta__/Form.stories.svelte
  mathesar_ui/src/components/form/__tests__/form.test.ts
  mathesar_ui/src/components/form/field.ts
  mathesar_ui/src/components/form/form.ts
  mathesar_ui/src/components/form/index.ts
  mathesar_ui/src/components/form/validators.ts
  mathesar_ui/src/stores/tables.ts
  mathesar_ui/src/systems/table-view/table-inspector/column/column-extraction/ExtractColumnsModal.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/column-extraction/ExtractColumnsModalController.ts
  mathesar_ui/src/systems/table-view/table-inspector/column/column-extraction/columnExtractionUtils.ts
Labels: status: review

#1879 Allow partial summarizations in the API
  db/queries/base.py
  db/queries/operations/__init__.py
  db/queries/operations/process.py
  db/transforms/base.py
  db/transforms/operations/serialize.py
  mathesar/api/db/viewsets/queries.py
  mathesar/models/query.py
  mathesar/tests/api/query/test_query_run.py
  mathesar/tests/api/query/test_query_run_partial_transforms.py
Labels: work: backend, status: review

#1916 Add Schema role permissions
  mathesar/api/db/permissions/database.py
  mathesar/api/db/permissions/schema.py
  mathesar/api/ui/permissions/database_role.py
  mathesar/api/ui/permissions/schema_role.py
  mathesar/api/ui/serializers/users.py
  mathesar/api/ui/viewsets/users.py
  mathesar/migrations/0008.py
  mathesar/models/users.py
  mathesar/tests/api/test_user_api.py
Labels: status: review

#1933 Add Database Permissions
  config/settings.py
  mathesar/api/db/viewsets/schemas.py
  mathesar/api/exceptions/mixins.py
  mathesar/api/serializers/schemas.py
  mathesar/tests/api/test_schema_api.py
Labels: status: review

#1905 Throw targeted error message for columns not longer present in the Query
  mathesar/api/db/viewsets/queries.py
  mathesar/api/db/viewsets/tables.py
  mathesar/api/exceptions/error_codes.py
  mathesar/api/exceptions/query_exceptions/__init__.py
  mathesar/api/exceptions/query_exceptions/exceptions.py
  mathesar/models/base.py
  mathesar/models/query.py
  mathesar/tests/api/query/test_query_run.py
  mathesar/tests/api/test_table_api.py
Labels: status: waiting

#1948 Refresh constraints after deleting column
  mathesar_ui/src/stores/table-data/tabularData.ts
Labels: status: review

#1967 Reset record summary to default value when customized is set to False
  mathesar/api/serializers/table_settings.py
  mathesar/models/base.py
  mathesar/signals.py
  mathesar/state/django.py
  mathesar/tests/api/test_record_api.py
Labels: status: review

#1975 Show live demo banner, improve layout components
  config/context_processors.py
  mathesar/templates/mathesar/base.html
  mathesar/templates/mathesar/index.html
  mathesar/templates/registration/login.html
  mathesar_ui/src/App.svelte
  mathesar_ui/src/component-library/common/styles/variables.scss
  mathesar_ui/src/components/LiveDemoBanner.svelte
  mathesar_ui/src/layouts/LayoutWithHeader.svelte
  mathesar_ui/src/layouts/LayoutWithHeader2.svelte
  mathesar_ui/src/pages/data-explorer/DataExplorerPage.svelte
  mathesar_ui/src/pages/database/DatabasePage.svelte
  mathesar_ui/src/pages/exploration/ExplorationPage.svelte
  mathesar_ui/src/pages/schema/SchemaPage.svelte
  mathesar_ui/src/utils/preloadData.ts
Labels: status: review

#1965 Fix partial summarizations
  db/tests/transforms/test_finish_specifying_summarization.py
  db/transforms/operations/finish_specifying.py
  mathesar/tests/api/query/test_query_run_partial_transforms.py
Labels: type: bug, work: backend, status: waiting

#1988 Make metadata cachable per request
  config/settings.py
  mathesar/state/metadata.py
  requirements.txt
Labels: status: review

#1876 Table inspector re design
  mathesar_ui/src/component-library/anchorButton/AnchorButton.scss
  mathesar_ui/src/component-library/anchorButton/AnchorButton.svelte
  mathesar_ui/src/component-library/collapsible/Collapsible.scss
  mathesar_ui/src/component-library/common/icons.ts
  mathesar_ui/src/component-library/common/styles/variables.scss
  mathesar_ui/src/component-library/help/Help.scss
  mathesar_ui/src/component-library/help/Help.svelte
  mathesar_ui/src/component-library/icon/Icon.svelte
  mathesar_ui/src/components/EditableTextWithActions.svelte
  mathesar_ui/src/icons/index.ts
  mathesar_ui/src/pages/table/TablePage.svelte
  mathesar_ui/src/stores/table-data/records.ts
  mathesar_ui/src/stores/tables.ts
  mathesar_ui/src/systems/record-selector/RecordSelectorContent.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorTable.svelte
  mathesar_ui/src/systems/record-selector/recordSelectorUtils.ts
  mathesar_ui/src/systems/table-view/TableView.svelte
  mathesar_ui/src/systems/table-view/table-inspector/CollapsibleHeader.svelte
  mathesar_ui/src/systems/table-view/table-inspector/TableInspector.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnActions.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnMode.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnOptions.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnTypeSpecifierTag.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/RenameColumn.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record/RecordMode.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record/RowActions.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/AdvancedActions.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/RenameTable.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/TableActions.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/TableMode.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/links/LinkItem.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/links/LinkSection.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/links/LinksSectionContainer.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/links/TableLinks.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/links/utils.ts
Labels: status: review

#1901 Add UI to configure Record Summary
  mathesar_ui/.eslintrc.cjs
  mathesar_ui/src/api/tables.ts
  mathesar_ui/src/api/tables/split_table.ts
  mathesar_ui/src/component-library/common/utils/typeUtils.ts
  mathesar_ui/src/component-library/fieldset-group/FieldsetGroup.scss
  mathesar_ui/src/component-library/fieldset-group/FieldsetGroup.svelte
  mathesar_ui/src/component-library/menu/ButtonMenuItem.svelte
  mathesar_ui/src/component-library/radio-group/RadioGroup.svelte
  mathesar_ui/src/components/Identifier.svelte
  mathesar_ui/src/components/LinkedRecord.svelte
  mathesar_ui/src/components/column/ColumnName.svelte
  mathesar_ui/src/stores/table-data/record-summaries/recordSummaryUtils.ts
  mathesar_ui/src/stores/tables.ts
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnMode.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record-summary/AppendColumn.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record-summary/FkRecordSummaryConfig.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record-summary/RecordSummaryConfig.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record-summary/TemplateInput.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record-summary/TemplateInputFormatter.ts
  mathesar_ui/src/systems/table-view/table-inspector/record-summary/__tests__/TemplateInputFormatter.test.ts
  mathesar_ui/src/systems/table-view/table-inspector/record-summary/recordSummaryTemplateUtils.ts
  mathesar_ui/src/systems/table-view/table-inspector/table/TableMode.svelte
  mathesar_ui/src/utils/columnUtils.ts
Labels: status: review

#1972 Change behavior of FK-Column Filter to be more similar to the filters for boolean columns.
  mathesar_ui/src/components/filter-entry/utils.ts
  mathesar_ui/src/stores/abstract-types/index.ts
  mathesar_ui/src/stores/abstract-types/operations/filtering.ts
  mathesar_ui/src/stores/table-data/processedColumns.ts
Labels: status: review

#1953 Add stacktrace to the exception response
  mathesar/exception_handlers.py
  mathesar/tests/api/test_custom_exceptions.py
Labels: status: review

#1973 Improve default summarizations
  db/queries/base.py
  db/tests/transforms/test_finish_specifying_summarization.py
  db/transforms/base.py
  db/transforms/operations/finish_specifying.py
Labels: work: backend, status: review

#1980 Add `remove` transform for hiding columns
  db/tests/records/operations/test_select.py
  db/tests/transforms/test_basic.py
  db/transforms/base.py
Labels: affects: dx, work: backend, status: done

#1977 Add `display_names` key to UIQuery
  .github/workflows/run-pytest.yml
  Dockerfile
  mathesar/api/serializers/queries.py
  mathesar/migrations/0009_auto_20221123_1423.py
  mathesar/models/query.py
  mathesar/tests/api/query/conftest.py
  mathesar/tests/api/query/test_library_demo_reports.py
  mathesar/tests/api/query/test_query_records_api.py
  mathesar/tests/api/query/test_query_run.py
  mathesar/tests/api/query/test_query_run_partial_transforms.py
  mathesar/tests/query/test_base.py
Labels: affects: dx, work: backend, status: review

#1961 Add permissions for Schema API
  mathesar/api/db/permissions/schema.py
  mathesar/api/db/viewsets/schemas.py
  mathesar/api/serializers/queries.py
  mathesar/api/serializers/tables.py
  mathesar/tests/api/test_schema_api.py
  mathesar/tests/api/test_table_api.py
  mathesar/tests/conftest.py
Labels: status: review

#1970 Data Explorer summarization changes
  mathesar_ui/src/api/queries.ts
  mathesar_ui/src/component-library/common/styles/components/input.scss
  mathesar_ui/src/component-library/common/styles/variables.scss
  mathesar_ui/src/component-library/common/utils/EventHandler.ts
  mathesar_ui/src/component-library/multi-select/MultiSelect.scss
  mathesar_ui/src/component-library/multi-select/MultiSelect.svelte
  mathesar_ui/src/components/NameWithIcon.svelte
  mathesar_ui/src/components/column/ColumnName.svelte
  mathesar_ui/src/components/filter-entry/FilterEntry.svelte
  mathesar_ui/src/components/group-entry/GroupEntry.svelte
  mathesar_ui/src/components/group-entry/types.ts
  mathesar_ui/src/systems/data-explorer/QueryFilterTransformationModel.ts
  mathesar_ui/src/systems/data-explorer/QueryManager.ts
  mathesar_ui/src/systems/data-explorer/QueryModel.ts
  mathesar_ui/src/systems/data-explorer/QueryRunner.ts
  mathesar_ui/src/systems/data-explorer/QuerySummarizationTransformationModel.ts
  mathesar_ui/src/systems/data-explorer/input-sidebar/InputSidebar.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/transformations-pane/FilterTransformation.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/transformations-pane/TransformationsPane.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/transformations-pane/summarization/Aggregation.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/transformations-pane/summarization/SummarizationTransformation.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/transformations-pane/transformationUtils.ts
  mathesar_ui/src/systems/data-explorer/urlSerializationUtils.ts
  mathesar_ui/src/systems/data-explorer/utils.ts
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/FilterEntries.svelte
  mathesar_ui/src/typeUtils.ts
Labels: status: review

#1989 1602 upgrade of checkbox cel
  mathesar_ui/src/components/cell-fabric/CellFabric.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/checkbox/CheckboxCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/typeDefinitions.ts
  mathesar_ui/src/systems/table-view/row/RowCell.svelte
Labels: status: review
