Repository mathesar-foundation/mathesar, pull requests merged in 2022-12, with the labels that each got.

#1962 Add Access Control for Tables
  mathesar/api/db/permissions/table.py
  mathesar/api/db/viewsets/tables.py
  mathesar/api/serializers/tables.py
  mathesar/tests/api/test_table_api.py
Labels: status: waiting

#1971 Filters for arrays
  db/functions/base.py
  db/functions/hints.py
  db/functions/packed.py
  db/tests/conftest.py
  db/tests/resources/array_create.sql
  db/tests/types/test_array.py
  db/types/categories.py
  db/types/hintsets.py
Labels: work: backend, status: review

#2023 Fix DE bug while calculating links for tables with multiple columns linking to the same target table
  mathesar_ui/src/api/tables.ts
  mathesar_ui/src/systems/data-explorer/QueryManager.ts
  mathesar_ui/src/systems/data-explorer/__tests__/mockData.ts
  mathesar_ui/src/systems/data-explorer/__tests__/utils.test.ts
  mathesar_ui/src/systems/data-explorer/input-sidebar/InputSidebar.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/column-selection-pane/ColumnSelectionPane.svelte
  mathesar_ui/src/systems/data-explorer/utils.ts
Labels: status: review

#2009 Table page re-design
  mathesar_ui/src/App.svelte
  mathesar_ui/src/api/tables.ts
  mathesar_ui/src/component-library/badge/Badge.scss
  mathesar_ui/src/component-library/badge/Badge.svelte
  mathesar_ui/src/component-library/button/Button.scss
  mathesar_ui/src/component-library/button/Button.svelte
  mathesar_ui/src/component-library/common/styles/variables.scss
  mathesar_ui/src/component-library/index.ts
  mathesar_ui/src/component-library/pagination/Pagination.scss
  mathesar_ui/src/component-library/pagination/Pagination.svelte
  mathesar_ui/src/component-library/styles.scss
  mathesar_ui/src/components/PaginationGroup.svelte
  mathesar_ui/src/components/SelectColumn.svelte
  mathesar_ui/src/components/SelectSortDirection.svelte
  mathesar_ui/src/components/TableNameAndDescription.svelte
  mathesar_ui/src/components/filter-entry/FilterEntry.svelte
  mathesar_ui/src/components/group-entry/GroupEntry.svelte
  mathesar_ui/src/components/sheet/Sheet.svelte
  mathesar_ui/src/icons/index.ts
  mathesar_ui/src/systems/table-view/StatusPane.svelte
  mathesar_ui/src/systems/table-view/actions-pane/ActionsPane.svelte
  mathesar_ui/src/systems/table-view/actions-pane/MiniActionsPane.svelte
  mathesar_ui/src/systems/table-view/actions-pane/SummarizationLink.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/DisplayOption.scss
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/Group.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/Sort.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/filter/Filter.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/filter/FilterEntries.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/sort/Sort.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/sort/SortEntry.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/types.ts
  mathesar_ui/src/systems/table-view/header/header-cell/HeaderCell.svelte
  mathesar_ui/src/systems/table-view/header/new-column-cell/NewColumnCell.svelte
  mathesar_ui/src/systems/table-view/row/GroupHeader.svelte
  mathesar_ui/src/systems/table-view/row/GroupHeaderCellValue.svelte
  mathesar_ui/src/systems/table-view/row/NewRecordMessage.svelte
Labels: status: review

#1992 Add permissions for Columns API
  mathesar/api/db/permissions/columns.py
  mathesar/api/db/viewsets/columns.py
  mathesar/tests/api/test_column_api.py
Labels: status: review

#2017 Stylize NULL values within record summaries
  mathesar_ui/src/App.svelte
  mathesar_ui/src/components/LinkedRecord.svelte
  mathesar_ui/src/components/PostgresKeyword.svelte
  mathesar_ui/src/components/RecordSummary.svelte
  mathesar_ui/src/components/breadcrumb/BreadcrumbItem.svelte
  mathesar_ui/src/components/breadcrumb/breadcrumbTypes.ts
  mathesar_ui/src/pages/record/RecordPage.svelte
  mathesar_ui/src/pages/record/RecordPageContent.svelte
  mathesar_ui/src/routes/RecordPageRoute.svelte
  mathesar_ui/src/stores/table-data/record-summaries/__tests__/recordSummaryUtils.test.ts
  mathesar_ui/src/stores/table-data/record-summaries/recordSummaryUtils.ts
  mathesar_ui/src/utils/stringUtils.ts
Labels: status: waiting

#2008 Fix display options not carrying over to DE
  mathesar/models/query.py
Labels: work: backend, status: waiting

#1963 Add permissions for constraints API
  mathesar/api/db/permissions/columns.py
  mathesar/api/db/permissions/constraint.py
  mathesar/api/db/viewsets/columns.py
  mathesar/api/db/viewsets/constraints.py
  mathesar/api/utils.py
  mathesar/tests/api/test_column_api.py
  mathesar/tests/api/test_constraint_api.py
Labels: work: backend, status: review

#1997 Add permissions for Links API
  mathesar/api/serializers/links.py
  mathesar/tests/api/test_links.py
Labels: status: review

#1999 Data explorer permission
  mathesar/api/db/permissions/query.py
  mathesar/api/db/permissions/query_table.py
  mathesar/api/db/viewsets/queries.py
  mathesar/api/serializers/queries.py
  mathesar/tests/api/query/test_query_api.py
  mathesar/tests/api/query/test_query_run.py
Labels: status: review

#1993 Add permissions for table settings
  mathesar/api/db/permissions/table_settings.py
  mathesar/api/db/viewsets/table_settings.py
  mathesar/tests/api/test_table_settings_api.py
Labels: status: waiting

#2028 Navigation styling
  mathesar_ui/src/component-library/common/styles/variables.scss
  mathesar_ui/src/component-library/dropdown/Dropdown.scss
  mathesar_ui/src/components/AppHeader.svelte
  mathesar_ui/src/components/AppSecondaryHeader.svelte
  mathesar_ui/src/components/Logo.svelte
  mathesar_ui/src/components/SchemaName.svelte
  mathesar_ui/src/components/breadcrumb/Breadcrumb.svelte
  mathesar_ui/src/components/breadcrumb/BreadcrumbItem.svelte
  mathesar_ui/src/components/breadcrumb/BreadcrumbPageSeparator.svelte
  mathesar_ui/src/components/breadcrumb/BreadcrumbRecordSelector.svelte
  mathesar_ui/src/components/breadcrumb/BreadcrumbSelector.svelte
  mathesar_ui/src/components/breadcrumb/BreadcrumbSelectorRow.svelte
  mathesar_ui/src/components/breadcrumb/BreadcrumbSeparatorIcon.svelte
  mathesar_ui/src/components/breadcrumb/LogoAndNameWithLink.svelte
  mathesar_ui/src/components/breadcrumb/breadcrumbTypes.ts
  mathesar_ui/src/icons/index.ts
  mathesar_ui/src/pages/database/SchemaRow.svelte
  mathesar_ui/src/routes/DataExplorerRoute.svelte
  mathesar_ui/src/routes/ExplorationRoute.svelte
  mathesar_ui/src/routes/RecordPageRoute.svelte
  mathesar_ui/src/static-assets/logo.svg
Labels: status: review

#1998 Record permissions
  mathesar/api/db/permissions/records.py
  mathesar/api/db/viewsets/records.py
  mathesar/tests/api/test_record_api.py
Labels: status: review

#2058 Cell tab in Data Explorer inspector
  mathesar_ui/src/component-library/chip/Chip.scss
  mathesar_ui/src/component-library/chip/Chip.svelte
  mathesar_ui/src/component-library/tabs/TabContainer.svelte
  mathesar_ui/src/components/RefreshButton.svelte
  mathesar_ui/src/components/cell-fabric/CellFabric.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/CellWrapper.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/SteppedInputCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/array/ArrayCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/checkbox/CheckboxCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/date-time/DateTimeCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/formatted-input/FormattedInputCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LinkedRecordCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/money/MoneyCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/number/NumberCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/primary-key/PrimaryKeyCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/select/SingleSelectCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/textarea/TextAreaCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/textbox/TextBoxCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/typeDefinitions.ts
  mathesar_ui/src/components/cell-fabric/data-types/components/uri/UriCell.svelte
  mathesar_ui/src/components/sheet/SheetSelection.ts
  mathesar_ui/src/pages/exploration/ExplorationPage.svelte
  mathesar_ui/src/pages/exploration/Header.svelte
  mathesar_ui/src/pages/schema/SchemaPage.svelte
  mathesar_ui/src/systems/data-explorer/QueryInspector.ts
  mathesar_ui/src/systems/data-explorer/QueryManager.ts
  mathesar_ui/src/systems/data-explorer/QueryRunner.ts
  mathesar_ui/src/systems/data-explorer/exploration-inspector/CellTab.svelte
  mathesar_ui/src/systems/data-explorer/exploration-inspector/ExplorationInspector.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/InputSidebar.svelte
  mathesar_ui/src/systems/data-explorer/result-pane/QueryRefreshButton.svelte
  mathesar_ui/src/systems/data-explorer/result-pane/ResultHeaderCell.svelte
  mathesar_ui/src/systems/data-explorer/result-pane/ResultPane.svelte
  mathesar_ui/src/systems/data-explorer/result-pane/ResultRowCell.svelte
  mathesar_ui/src/systems/data-explorer/result-pane/Results.svelte
  mathesar_ui/src/systems/table-view/StatusPane.svelte
Labels: status: review

#2000 Add Password reset View
  config/settings.py
  mathesar/api/ui/permissions/users.py
  mathesar/api/ui/serializers/users.py
  mathesar/api/ui/viewsets/users.py
  mathesar/middleware.py
  mathesar/migrations/0010_auto_20221208_2041.py
  mathesar/migrations/0011_auto_20221208_2303.py
  mathesar/models/users.py
  mathesar/templates/users/__init__.py
  mathesar/templates/users/password_reset_confirmation.html
  mathesar/tests/api/test_user_api.py
  mathesar/urls.py
  mathesar/users/__init__.py
  mathesar/users/password_reset.py
Labels: status: review

#2052 Add Password change API
  mathesar/api/exceptions/error_codes.py
  mathesar/api/exceptions/validation_exceptions/exceptions.py
  mathesar/api/ui/permissions/users.py
  mathesar/api/ui/serializers/users.py
  mathesar/api/ui/viewsets/users.py
  mathesar/tests/api/test_user_api.py
Labels: status: review

#1984 backend changes for column order
  mathesar/api/serializers/table_settings.py
  mathesar/migrations/0012_auto_20221212_2148.py
  mathesar/models/base.py
  mathesar/tests/api/test_table_settings_api.py
Labels: status: review

#2019 Fix typecasting for json list and map type
  mathesar/api/serializers/columns.py
  mathesar/tests/api/test_column_api_display_options.py
  mathesar_ui/src/stores/abstract-types/type-configs/comboTypes/jsonArrayFactory.ts
  mathesar_ui/src/stores/abstract-types/type-configs/comboTypes/jsonObjectFactory.ts
Labels: status: review

#2033 Invalidate type_options having precision without a scale
  mathesar/api/db/viewsets/columns.py
  mathesar/api/serializers/columns.py
  mathesar/tests/api/test_column_api.py
Labels: status: review

#1987 Fix FK behaviour for Tables having round brackets
  mathesar/api/exceptions/error_codes.py
  mathesar/api/exceptions/validation_exceptions/exceptions.py
  mathesar/api/serializers/constraints.py
  mathesar/api/serializers/links.py
  mathesar/api/serializers/tables.py
  mathesar/tests/api/conftest.py
  mathesar/tests/api/test_constraint_api.py
  mathesar/tests/api/test_links.py
  mathesar/tests/api/test_table_api.py
Labels: status: review

#2082 Replace mutable default function parameters with immutable value.
  db/columns/base.py
  db/columns/operations/alter.py
  db/columns/operations/infer_types.py
  db/records/operations/select.py
  db/records/operations/sort.py
  db/transforms/operations/apply.py
  db/types/base.py
  db/types/operations/cast.py
  mathesar/api/pagination.py
  mathesar/models/base.py
  mathesar/tests/api/query/test_query_api.py
  mathesar/utils/preview.py
Labels: status: review

#2056 Have every DE alias inherit display options
  db/transforms/base.py
  mathesar/models/query.py
  mathesar/tests/api/query/test_library_demo_reports.py
Labels: type: enhancement, work: backend, status: review

#2075 Refactor Alert into MessageBox
  mathesar_ui/src/component-library/alert/Alert.scss
  mathesar_ui/src/component-library/alert/Alert.svelte
  mathesar_ui/src/component-library/alert/AlertTypes.ts
  mathesar_ui/src/component-library/alert/__meta__/Alert.stories.svelte
  mathesar_ui/src/component-library/common/styles/variables.scss
  mathesar_ui/src/component-library/index.ts
  mathesar_ui/src/component-library/styles.scss
  mathesar_ui/src/components/form/Errors.svelte
  mathesar_ui/src/components/form/Field.svelte
  mathesar_ui/src/components/form/FieldErrors.svelte
  mathesar_ui/src/components/form/FormErrors.svelte
  mathesar_ui/src/components/form/FormSubmitWithCatch.svelte
  mathesar_ui/src/components/message-boxes/ErrorBox.svelte
  mathesar_ui/src/components/message-boxes/InfoBox.svelte
  mathesar_ui/src/components/message-boxes/MessageBox.svelte
  mathesar_ui/src/components/message-boxes/OutcomeBox.svelte
  mathesar_ui/src/components/message-boxes/WarningBox.svelte
  mathesar_ui/src/icons/customIcons.ts
  mathesar_ui/src/icons/index.ts
  mathesar_ui/src/pages/database/AddEditSchemaModal.svelte
  mathesar_ui/src/pages/database/SchemaRow.svelte
  mathesar_ui/src/pages/record/DirectField.svelte
  mathesar_ui/src/systems/data-explorer/exploration-inspector/column-tab/DeleteColumnAction.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/InputSidebar.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record-summary/RecordSummaryConfig.svelte
Labels: status: review

#2091 Data Explorer - styling - demo blockers
  mathesar_ui/src/api/types/queries.ts
  mathesar_ui/src/component-library/date-time-picker/DateTimePicker.scss
  mathesar_ui/src/component-library/dropdown/Dropdown.scss
  mathesar_ui/src/components/CellValue.svelte
  mathesar_ui/src/components/ModificationStatus.svelte
  mathesar_ui/src/components/SelectTable.svelte
  mathesar_ui/src/components/cell-fabric/data-types/array.ts
  mathesar_ui/src/components/cell-fabric/data-types/arrayFactory.ts
  mathesar_ui/src/components/cell-fabric/data-types/boolean.ts
  mathesar_ui/src/components/cell-fabric/data-types/components/SteppedInputCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/array/ArrayCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/date-time/DateTimeCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/date-time/DateTimeInput.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/formatted-input/FormattedInputCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/money/MoneyCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/number/NumberCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/typeDefinitions.ts
  mathesar_ui/src/components/cell-fabric/data-types/date.ts
  mathesar_ui/src/components/cell-fabric/data-types/datetime.ts
  mathesar_ui/src/components/cell-fabric/data-types/duration.ts
  mathesar_ui/src/components/cell-fabric/data-types/index.ts
  mathesar_ui/src/components/cell-fabric/data-types/money.ts
  mathesar_ui/src/components/cell-fabric/data-types/number.ts
  mathesar_ui/src/components/cell-fabric/data-types/time.ts
  mathesar_ui/src/components/cell-fabric/data-types/typeDefinitions.ts
  mathesar_ui/src/components/cell-fabric/data-types/utils.ts
  mathesar_ui/src/components/cell-fabric/types.ts
  mathesar_ui/src/components/cell-fabric/utils.ts
  mathesar_ui/src/pages/data-explorer/DataExplorerPage.svelte
  mathesar_ui/src/systems/data-explorer/ActionsPane.svelte
  mathesar_ui/src/systems/data-explorer/DataExplorer.svelte
  mathesar_ui/src/systems/data-explorer/QueryFilterTransformationModel.ts
  mathesar_ui/src/systems/data-explorer/QueryHideTransformationModel.ts
  mathesar_ui/src/systems/data-explorer/QueryManager.ts
  mathesar_ui/src/systems/data-explorer/QueryModel.ts
  mathesar_ui/src/systems/data-explorer/QuerySummarizationTransformationModel.ts
  mathesar_ui/src/systems/data-explorer/QueryUndoRedoManager.ts
  mathesar_ui/src/systems/data-explorer/exploration-inspector/ExplorationTab.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/InputSidebar.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/column-selection-pane/ColumnSelectionPane.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/column-selection-pane/SelectableColumn.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/column-selection-pane/SelectableColumnTree.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/transformations-pane/HideTransformation.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/transformations-pane/TransformationsPane.svelte
  mathesar_ui/src/systems/data-explorer/utils.ts
Labels: status: review

#2041 Add `is not null` filter
  db/functions/base.py
  db/functions/operations/deserialize.py
  db/functions/packed.py
  db/tests/functions/operations/test_deserialize.py
  db/tests/functions/operations/test_filter.py
  db/tests/queries/test_base.py
  mathesar/tests/api/query/test_library_demo_reports.py
  mathesar/tests/api/test_record_api.py
  mathesar/tests/filters/test_filters.py
  mathesar_ui/src/stores/abstract-types/operations/filtering.ts
Labels: type: enhancement, work: backend, status: waiting

#2080 Re-style the Link Table modal
  mathesar_ui/src/App.svelte
  mathesar_ui/src/component-library/index.ts
  mathesar_ui/src/component-library/label/Label.scss
  mathesar_ui/src/component-library/label/Label.svelte
  mathesar_ui/src/component-library/menu/CheckboxMenuItem.svelte
  mathesar_ui/src/component-library/menu/MenuItemWrapper.svelte
  mathesar_ui/src/component-library/window/index.ts
  mathesar_ui/src/component-library/window/portalToWindowFooter.ts
  mathesar_ui/src/components/SelectTable.svelte
  mathesar_ui/src/components/SelectTableWithinCurrentSchema.svelte
  mathesar_ui/src/components/form/Field.svelte
  mathesar_ui/src/components/form/FieldLayout.svelte
  mathesar_ui/src/components/form/FieldWrapper.svelte
  mathesar_ui/src/components/form/FormSubmit.svelte
  mathesar_ui/src/components/form/field.ts
  mathesar_ui/src/components/form/validators.ts
  mathesar_ui/src/components/message-boxes/MessageBox.svelte
  mathesar_ui/src/components/message-boxes/OutcomeBox.svelte
  mathesar_ui/src/systems/data-explorer/ActionsPane.svelte
  mathesar_ui/src/systems/table-view/constraints/NewFkConstraintModal.svelte
  mathesar_ui/src/systems/table-view/link-table/LinkTableForm.svelte
  mathesar_ui/src/systems/table-view/link-table/LinkTableModal.svelte
  mathesar_ui/src/systems/table-view/link-table/LinkTablePill.svelte
  mathesar_ui/src/systems/table-view/link-table/LinkTypeOption.svelte
  mathesar_ui/src/systems/table-view/link-table/NewColumn.svelte
  mathesar_ui/src/systems/table-view/link-table/RelationshipDiagram.svelte
  mathesar_ui/src/systems/table-view/link-table/SelectLinkType.svelte
  mathesar_ui/src/systems/table-view/link-table/TableName.svelte
  mathesar_ui/src/systems/table-view/link-table/diagram/Diagram.svelte
  mathesar_ui/src/systems/table-view/link-table/diagram/ManyToManySource.inkscape.svg
  mathesar_ui/src/systems/table-view/link-table/diagram/OneToManySource.inkscape.svg
  mathesar_ui/src/systems/table-view/link-table/diagram/README.md
  mathesar_ui/src/systems/table-view/link-table/link-table.scss
  mathesar_ui/src/systems/table-view/link-table/linkTableUtils.ts
  mathesar_ui/src/utils/columnUtils.ts
  mathesar_ui/src/utils/languageUtils.ts
  mathesar_ui/src/utils/typeUtils.ts
Labels: status: review

#2107 Import styling
  mathesar_ui/src/App.svelte
  mathesar_ui/src/component-library/checkbox/Checkbox.scss
  mathesar_ui/src/component-library/common/styles/variables.scss
  mathesar_ui/src/component-library/fieldset-group/FieldsetGroup.scss
  mathesar_ui/src/component-library/file-upload/FileUpload.scss
  mathesar_ui/src/component-library/file-upload/FileUpload.svelte
  mathesar_ui/src/component-library/labeled-input/LabeledInput.scss
  mathesar_ui/src/component-library/progress/Progress.scss
  mathesar_ui/src/component-library/radio/Radio.scss
  mathesar_ui/src/component-library/spinner-button/SpinnerButton.svelte
  mathesar_ui/src/components/EntityPageHeader.svelte
  mathesar_ui/src/components/ModificationStatus.svelte
  mathesar_ui/src/components/NameWithIcon.svelte
  mathesar_ui/src/components/StatusIndicator.svelte
  mathesar_ui/src/components/TableName.svelte
  mathesar_ui/src/components/abstract-type-control/AbstractTypeControl.svelte
  mathesar_ui/src/components/message-boxes/ErrorBox.svelte
  mathesar_ui/src/components/message-boxes/InfoBox.svelte
  mathesar_ui/src/components/sheet/Sheet.svelte
  mathesar_ui/src/components/sheet/SheetHeader.svelte
  mathesar_ui/src/icons/index.ts
  mathesar_ui/src/layouts/InsetPageLayout.svelte
  mathesar_ui/src/layouts/LayoutWithHeader.svelte
  mathesar_ui/src/pages/database/SchemaConstituentCounts.svelte
  mathesar_ui/src/pages/import-preview/ErrorInfo.svelte
  mathesar_ui/src/pages/import-preview/ImportPreviewPage.svelte
  mathesar_ui/src/pages/import-preview/PreviewColumn.svelte
  mathesar_ui/src/pages/import-upload/ImportUploadPage.svelte
  mathesar_ui/src/pages/import-upload/UploadViaClipboard.svelte
  mathesar_ui/src/pages/import-upload/UploadViaFile.svelte
  mathesar_ui/src/pages/import-upload/UploadViaUrl.svelte
  mathesar_ui/src/pages/import-upload/uploadUtils.ts
  mathesar_ui/src/pages/schema/SchemaPage.svelte
  mathesar_ui/src/pages/schema/TableItem.svelte
  mathesar_ui/src/utils/tables.ts
Labels: status: review

#2092 Constraints modal re design
  mathesar_ui/src/component-library/multi-select/MultiSelect.scss
  mathesar_ui/src/components/SelectColumn.svelte
  mathesar_ui/src/systems/table-view/constraints/ConstraintCollapseHeader.svelte
  mathesar_ui/src/systems/table-view/constraints/ConstraintDetails.svelte
  mathesar_ui/src/systems/table-view/constraints/ConstraintTypeSection.svelte
  mathesar_ui/src/systems/table-view/constraints/ForeignKeyConstraintDetails.svelte
  mathesar_ui/src/systems/table-view/constraints/NewFkConstraint.svelte
  mathesar_ui/src/systems/table-view/constraints/NewUniqueConstraint.svelte
  mathesar_ui/src/systems/table-view/constraints/TableConstraint.svelte
  mathesar_ui/src/systems/table-view/constraints/TableConstraints.svelte
  mathesar_ui/src/systems/table-view/constraints/TableConstraintsModal.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/AdvancedActions.svelte
Labels: status: review

#2118 Click & Drag column headers to select multiple columns
  mathesar_ui/src/component-library/button/Button.svelte
  mathesar_ui/src/components/sheet/SheetSelection.ts
  mathesar_ui/src/systems/data-explorer/result-pane/ResultRowCell.svelte
  mathesar_ui/src/systems/table-view/header/Header.svelte
  mathesar_ui/src/systems/table-view/header/header-cell/HeaderCell.svelte
  mathesar_ui/src/systems/table-view/row/Row.svelte
  mathesar_ui/src/systems/table-view/row/RowCell.svelte
  mathesar_ui/src/systems/table-view/row/RowControl.svelte
  setup.cfg
Labels: status: review

#2078 Add default display names for summarization output aliases
  db/transforms/base.py
  mathesar/api/db/viewsets/queries.py
  mathesar/models/query.py
  mathesar/tests/api/query/test_query_run_partial_transforms.py
Labels: affects: ux, work: backend, status: review

#2074 Fix bad agg output for custom types
  db/functions/base.py
  db/functions/operations/apply.py
  db/tests/conftest.py
  db/tests/types/test_base.py
Labels: affects: ux, work: backend, status: review

#2120 Grow record selector search input width with query
  mathesar_ui/src/systems/record-selector/RecordSelectorCellWrapper.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorInputCell.svelte
Labels: status: review

#2128 Idempotent install script
  db/tests/types/test_install.py
  db/types/custom/email.py
  db/types/custom/json_array.py
  db/types/custom/json_object.py
  db/types/custom/money.py
  db/types/custom/multicurrency.py
  db/types/custom/uri.py
  db/utils.py
Labels: status: review

#2125 Demo video 'must-haves', general improvements
  mathesar_ui/src/component-library/cancel-or-proceed-button-pair/CancelOrProceedButtonPair.svelte
  mathesar_ui/src/component-library/index.ts
  mathesar_ui/src/component-library/list-box/ListBox.scss
  mathesar_ui/src/component-library/list-box/ListBox.svelte
  mathesar_ui/src/component-library/list-box/ListBoxOptions.svelte
  mathesar_ui/src/component-library/list-box/ListBoxTypes.ts
  mathesar_ui/src/component-library/selection-list/SelectionList.scss
  mathesar_ui/src/component-library/selection-list/SelectionList.svelte
  mathesar_ui/src/component-library/selection-list/SelectionListTypes.ts
  mathesar_ui/src/component-library/styles.scss
  mathesar_ui/src/components/ModificationStatus.svelte
  mathesar_ui/src/components/SaveStatusIndicator.svelte
  mathesar_ui/src/components/cell-fabric/CellFabric.svelte
  mathesar_ui/src/components/form/FormStatus.svelte
  mathesar_ui/src/components/sheet/Sheet.svelte
  mathesar_ui/src/components/sheet/SheetHeader.svelte
  mathesar_ui/src/components/sheet/utils.ts
  mathesar_ui/src/routes/DataExplorerRoute.svelte
  mathesar_ui/src/stores/abstract-types/abstractTypeCategories.ts
  mathesar_ui/src/stores/abstract-types/index.ts
  mathesar_ui/src/stores/abstract-types/type-configs/text.ts
  mathesar_ui/src/systems/data-explorer/ActionsPane.svelte
  mathesar_ui/src/systems/data-explorer/urlSerializationUtils.ts
  mathesar_ui/src/systems/table-view/TableView.svelte
  mathesar_ui/src/systems/table-view/actions-pane/ActionsPane.svelte
  mathesar_ui/src/systems/table-view/header/Header.svelte
  mathesar_ui/src/systems/table-view/header/new-column-cell/ColumnTypeSelector.svelte
  mathesar_ui/src/systems/table-view/header/new-column-cell/NewColumnCell.scss
  mathesar_ui/src/systems/table-view/header/new-column-cell/NewColumnCell.svelte
  mathesar_ui/src/typeUtils.ts
Labels: status: review

#2133 Table Inpsector contextual behaviour
  mathesar_ui/src/components/sheet/SheetSelection.ts
  mathesar_ui/src/systems/table-view/table-inspector/TableInspector.svelte
Labels: status: review

#2083 Fix SelectSubsetOfColumns discarding column type
  db/queries/base.py
  db/transforms/base.py
  mathesar/tests/api/query/test_query_run.py
Labels: affects: ux, work: backend, status: review

#2087 Add `distinct_aggregate_to_array`
  db/functions/base.py
  db/functions/operations/apply.py
  db/functions/packed.py
  db/queries/base.py
  db/records/operations/select.py
  db/tests/queries/test_base.py
  db/tests/transforms/test_finish_specifying_summarization.py
  db/transforms/base.py
  mathesar/models/query.py
  mathesar/tests/api/query/test_library_demo_reports.py
  mathesar/tests/api/query/test_query_run_partial_transforms.py
Labels: affects: ux, work: backend, status: waiting

#2140 Re-style the "Move Columns" modal
  mathesar_ui/src/api/types/tables/split_table.ts
  mathesar_ui/src/component-library/toast/ToastItem.scss
  mathesar_ui/src/components/NameWithIcon.svelte
  mathesar_ui/src/components/SelectProcessedColumns.svelte
  mathesar_ui/src/components/column/ColumnName.svelte
  mathesar_ui/src/components/column/ProcessedColumnName.svelte
  mathesar_ui/src/stores/tables.ts
  mathesar_ui/src/systems/table-view/link-table/LinkTableForm.svelte
  mathesar_ui/src/systems/table-view/link-table/linkTableUtils.ts
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnActions.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/column-extraction/CurrentTable.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/column-extraction/ExtractColumnsModal.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/column-extraction/LinkedTableName.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/column-extraction/SuccessToastContent.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/column-extraction/TargetTable.svelte
  mathesar_ui/src/utils/columnUtils.ts
Labels: status: review

#2151 Reset primary key column sequence upon splitting table.
  db/tables/operations/split.py
  db/tests/tables/operations/test_split.py
Labels: status: review

#2148 Fix joins from being duplicated
  db/queries/base.py
Labels: status: review

#2158 Fix db query unique constraint check
  db/records/operations/select.py
  db/transforms/operations/finish_specifying.py
Labels: work: backend, status: review

#2164 Toasts styling
  mathesar_ui/src/component-library/toast/ToastController.ts
  mathesar_ui/src/component-library/toast/ToastItem.scss
  mathesar_ui/src/component-library/toast/ToastItem.svelte
  mathesar_ui/src/systems/table-view/link-table/LinkTableForm.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/column-extraction/ExtractColumnsModal.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/column-extraction/SuccessToastContent.svelte
Labels: status: review

#2167 Demo video nice to haves
  mathesar_ui/src/components/sheet/Sheet.svelte
  mathesar_ui/src/pages/schema/ExplorationSkeleton.svelte
  mathesar_ui/src/pages/schema/SchemaOverview.svelte
  mathesar_ui/src/pages/schema/SchemaPage.svelte
  mathesar_ui/src/pages/schema/TableSkeleton.svelte
  mathesar_ui/src/systems/table-view/row/GroupHeader.svelte
  mathesar_ui/src/systems/table-view/row/NewRecordMessage.svelte
Labels: status: review

#2171 Refresh catalog table metadata if incorrectly reflected.
  db/utils.py
Labels: status: review

#2173 Improve pluralization
  mathesar_ui/src/components/breadcrumb/BreadcrumbSelector.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/array/ArrayCell.svelte
  mathesar_ui/src/pages/database/DatabasePage.svelte
  mathesar_ui/src/pages/database/SchemaConstituentCounts.svelte
  mathesar_ui/src/pages/schema/SchemaExplorations.svelte
  mathesar_ui/src/pages/schema/SchemaTables.svelte
  mathesar_ui/src/systems/data-explorer/exploration-inspector/column-tab/DeleteColumnAction.svelte
  mathesar_ui/src/systems/table-view/StatusPane.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnActions.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnMode.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/column-extraction/ExtractColumnsModal.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record/RecordMode.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record/RowActions.svelte
  mathesar_ui/src/utils/languageUtils.ts
Labels: status: review

#2176 Set up custom user admin so that we can use Django admin for users.
  mathesar/admin.py
Labels: status: review
