Repository mathesar-foundation/mathesar, pull requests merged in 2022-05, with the labels that each got.

#1338 Update DISPLAY_OPTIONS_BY_TYPE_IDENTIFIER to use the new DURATION display options
  mathesar/api/display_options.py
Labels: status: review

#1293 Fix patching columns giving 500 Internal Server Error
  db/columns/operations/alter.py
  mathesar/api/serializers/columns.py
  mathesar/api/serializers/shared_serializers.py
  mathesar/tests/api/test_column_api.py
Labels: status: review

#1333 Set `allowFloat` prop for number inputs
  mathesar_ui/src/api/tables/columns.ts
  mathesar_ui/src/components/cell/data-types/components/number/NumberCell.svelte
  mathesar_ui/src/components/cell/data-types/components/typeDefinitions.ts
  mathesar_ui/src/components/cell/data-types/number.ts
  mathesar_ui/src/stores/abstract-types/type-configs/number.ts
Labels: status: review

#1339 Fix bug with locale number formatting
  mathesar_ui/src/component-library/number-input/number-formatter/StringifiedNumberFormatter.ts
Labels: status: review

#1312 `count_by` and `endpoints` grouping modes
  db/records/operations/group.py
  db/tests/records/operations/test_group.py
Labels: status: review

#1314 First letter grouping
  db/records/operations/group.py
  db/tests/records/operations/test_group.py
  mathesar/api/pagination.py
  mathesar/tests/api/test_record_api.py
Labels: status: draft

#1342 Preprocessed distinct grouping mode
  db/functions/operations/deserialize.py
  db/records/operations/group.py
  db/tests/records/operations/test_group.py
  db/tests/resources/roster_create.sql
  db/tests/resources/uri_testing
  mathesar/api/pagination.py
  mathesar/tests/api/test_record_api.py
Labels: status: review

#1205 Accept display options for MathesarMoney type
  currency_info.json
  db/tests/types/operations/test_cast.py
  db/types/base.py
  db/types/money.py
  db/types/operations/cast.py
  mathesar/api/display_options.py
  mathesar/api/exceptions/error_codes.py
  mathesar/api/exceptions/mixins.py
  mathesar/api/exceptions/validation_exceptions/exceptions.py
  mathesar/api/serializers/databases.py
  mathesar/api/serializers/shared_serializers.py
  mathesar/tests/api/test_column_api.py
  mathesar/tests/api/test_table_api.py
  mathesar/tests/api/test_ui_types_api.py
  mathesar/tests/data/display_options_inference.csv
  mathesar/tests/data/type_inference.csv
  mathesar/tests/display_options_inference/__init__.py
  mathesar/tests/display_options_inference/test_money.py
  mathesar/utils/display_options_inference.py
  requirements.txt
Labels: status: review

#1354 Add UI to remove FK constraint from column header
  mathesar_ui/src/sections/table-view/header/header-cell/DefaultOptions.svelte
Labels: status: review

#1365 Add a default value for precision field if only scale is present
  mathesar/api/db/viewsets/columns.py
  mathesar/api/serializers/columns.py
  mathesar/tests/api/test_column_api.py
Labels: status: review

#1375 Foreign key constraints list
  mathesar/api/exceptions/mixins.py
  mathesar/api/serializers/constraints.py
  mathesar/api/serializers/shared_serializers.py
  mathesar/models.py
  mathesar/tests/api/conftest.py
  mathesar/tests/api/test_constraint_api.py
  mathesar/tests/conftest.py
  mathesar/tests/data/base_table.csv
  mathesar/tests/data/invalid_reference_base_table.csv
  mathesar/tests/data/multi_column_foreign_key_base_table.csv
  mathesar/tests/data/multi_column_reference_table.csv
  mathesar/tests/data/reference_table.csv
  mathesar/tests/data/self_referential_table.csv
Labels: status: review

#1371 Add icons for types
  mathesar/tests/integration/test_columns.py
  mathesar_ui/src/components/ColumnName.svelte
  mathesar_ui/src/components/TypeIcon.svelte
  mathesar_ui/src/components/cell/utils.ts
  mathesar_ui/src/sections/table-view/header/header-cell/HeaderCell.scss
  mathesar_ui/src/sections/table-view/header/header-cell/HeaderCell.svelte
  mathesar_ui/src/sections/table-view/header/header-cell/abstract-type-configuration/AbstractTypeSelector.svelte
  mathesar_ui/src/stores/abstract-types/type-configs/boolean.ts
  mathesar_ui/src/stores/abstract-types/type-configs/duration.ts
  mathesar_ui/src/stores/abstract-types/type-configs/fallback.ts
  mathesar_ui/src/stores/abstract-types/type-configs/number.ts
  mathesar_ui/src/stores/abstract-types/type-configs/text.ts
  mathesar_ui/src/stores/abstract-types/types.ts
Labels: status: review

#1351 Removed the loading skeleton when deleting rows
  mathesar_ui/src/stores/table-data/records.ts
Labels: status: review

#1349 Make URI cells clickable
  mathesar_ui/src/components/CellValue.svelte
  mathesar_ui/src/components/cell/data-types/components/SteppedInputCell.svelte
  mathesar_ui/src/components/cell/data-types/components/uri/UriCell.svelte
  mathesar_ui/src/components/cell/data-types/index.ts
  mathesar_ui/src/components/cell/data-types/typeDefinitions.ts
  mathesar_ui/src/components/cell/data-types/uri.ts
  mathesar_ui/src/stores/abstract-types/abstractTypeCategories.ts
  mathesar_ui/src/stores/abstract-types/type-configs/uri.ts
Labels: status: review

#1366 Fix occasionally re-ordering of columns
  mathesar/api/db/viewsets/columns.py
Labels: status: review

#1307 Batch update columns using id instead of column_index
  db/columns/operations/alter.py
  db/tests/columns/operations/test_alter.py
  mathesar/api/serializers/columns.py
  mathesar/tests/api/test_table_api.py
  mathesar/utils/models.py
Labels: status: review

#1260 Fixes #1214: Intital setup of class to represent CHAR db
  db/tests/columns/operations/test_create.py
  db/tests/types/test_mathesar_char.py
  db/types/__init__.py
  db/types/base.py
  db/types/mathesar_char.py
  db/types/operations/cast.py
Labels: status: review

#1379 Refactor cell backgrounds and improve styling
  mathesar_ui/src/components/cell/Cell.svelte
  mathesar_ui/src/sections/table-view/TableView.scss
  mathesar_ui/src/sections/table-view/row/CellBackground.svelte
  mathesar_ui/src/sections/table-view/row/Row.scss
  mathesar_ui/src/sections/table-view/row/Row.svelte
  mathesar_ui/src/sections/table-view/row/RowCell.svelte
  mathesar_ui/src/sections/table-view/row/RowCellBackgrounds.svelte
  mathesar_ui/src/sections/table-view/row/RowControl.svelte
Labels: status: review

#1378 UI to add FK manually
  mathesar_ui/src/api/tables/constraints.ts
  mathesar_ui/src/components/SelectColumn.svelte
  mathesar_ui/src/sections/table-view/constraints/NewFkConstraintModal.svelte
  mathesar_ui/src/sections/table-view/constraints/TableConstraints.svelte
Labels: status: review

#1323 Removed the rows which are common in savedRecords and newRecords
  mathesar_ui/src/stores/table-data/records.ts
Labels: status: review

#1392 Default polymorphic serializer
  mathesar/api/serializers/constraints.py
  mathesar/api/serializers/shared_serializers.py
  mathesar/tests/api/test_column_api_display_options.py
Labels: status: waiting

#1374 Add link Table API
  db/links/__init__.py
  db/links/operations/__init__.py
  db/links/operations/create.py
  db/tables/operations/select.py
  db/tests/links/__init__.py
  mathesar/api/db/viewsets/__init__.py
  mathesar/api/db/viewsets/links.py
  mathesar/api/exceptions/error_codes.py
  mathesar/api/exceptions/mixins.py
  mathesar/api/exceptions/validation_exceptions/exceptions.py
  mathesar/api/serializers/links.py
  mathesar/tests/api/test_links.py
  mathesar/urls.py
Labels: status: waiting

#1393 Resize columns (persisting only within current Mathesar tab)
  mathesar_ui/src/sections/table-view/header/Header.svelte
  mathesar_ui/src/sections/table-view/header/header-cell/ColumnResizer.svelte
  mathesar_ui/src/sections/table-view/header/header-cell/HeaderCell.scss
  mathesar_ui/src/sections/table-view/header/header-cell/HeaderCell.svelte
  mathesar_ui/src/sections/table-view/row/Row.svelte
  mathesar_ui/src/sections/table-view/row/RowCell.svelte
  mathesar_ui/src/stores/table-data/display.ts
  mathesar_ui/src/stores/table-data/index.ts
  mathesar_ui/src/stores/table-data/tabularData.ts
  mathesar_ui/src/stores/table-data/types.ts
Labels: status: review

#1384 Increase type safety of EventHandler
  mathesar_ui/src/component-library/common/utils/EventHandler.ts
  mathesar_ui/src/stores/table-data/columns.ts
  mathesar_ui/src/stores/table-data/records.ts
  mathesar_ui/src/stores/table-data/tabularData.ts
Labels: status: review
