Repository mathesar-foundation/mathesar, pull requests merged in 2022-08, with the labels that each got.

#1422 Finish Link Table UI
  mathesar_ui/src/api/links.ts
  mathesar_ui/src/routes/schema-home/routes/datascape/table-view/link-table/LinkTableModal.svelte
  mathesar_ui/src/routes/schema-home/routes/datascape/table-view/link-table/linkTableUtils.ts
  mathesar_ui/src/stores/table-data/index.ts
  mathesar_ui/src/stores/table-data/manager.ts
  mathesar_ui/src/stores/tabs/tabList.ts
Labels: status: review

#1472 Split table/Move columns without dropping the original Table
  db/columns/operations/alter.py
  db/columns/operations/create.py
  db/columns/operations/select.py
  db/constraints/base.py
  db/constraints/utils.py
  db/links/operations/create.py
  db/tables/operations/move_columns.py
  db/tables/operations/select.py
  db/tables/operations/split.py
  db/tests/columns/operations/test_alter.py
  db/tests/conftest.py
  db/tests/tables/operations/test_infer_types.py
  db/tests/tables/operations/test_merge.py
  db/tests/tables/operations/test_move_columns.py
  db/tests/tables/operations/test_split.py
  mathesar/api/db/viewsets/tables.py
  mathesar/api/exceptions/error_codes.py
  mathesar/api/exceptions/validation_exceptions/exceptions.py
  mathesar/api/serializers/tables.py
  mathesar/models/base.py
  mathesar/tests/api/test_table_api.py
Labels: status: review

#1512 Constraints based column icons
  mathesar_ui/src/components/ColumnName.svelte
  mathesar_ui/src/components/TableColumnName.svelte
  mathesar_ui/src/components/cell-fabric/utils.ts
  mathesar_ui/src/components/column/ColumnName.svelte
  mathesar_ui/src/components/column/types.ts
  mathesar_ui/src/routes/schema-home/routes/datascape/table-view/constraints/NewUniqueConstraintModal.svelte
  mathesar_ui/src/routes/schema-home/routes/datascape/table-view/header/header-cell/HeaderCell.svelte
  mathesar_ui/src/systems/query-builder/column-selection-pane/SelectableColumn.svelte
  mathesar_ui/src/systems/query-builder/column-selection-pane/TableGroupCollapsible.svelte
  mathesar_ui/src/systems/query-builder/result-pane/ResultPane.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorTable.svelte
Labels: status: review

#1493 Implement JSON array filtering functions
  db/functions/hints.py
  db/functions/known_db_functions.py
  db/tests/types/test_json.py
  db/types/categories.py
  db/types/custom/json_array.py
  db/types/hintsets.py
  mathesar/tests/filters/test_filters.py
  mathesar_ui/src/stores/abstract-types/constants.ts
  mathesar_ui/src/stores/abstract-types/operations/filtering.ts
Labels: status: review

#1517 Reinstate functionality to synchronize the URL with the table's grouping/sorting/filtering/pagination
  mathesar_ui/src/AppTypes.ts
  mathesar_ui/src/pages/import/importUtils.ts
  mathesar_ui/src/pages/table/TablePage.svelte
  mathesar_ui/src/stores/table-data/TabularType.ts
  mathesar_ui/src/stores/table-data/columns.ts
  mathesar_ui/src/stores/table-data/index.ts
  mathesar_ui/src/stores/table-data/manager.ts
  mathesar_ui/src/stores/table-data/meta.ts
  mathesar_ui/src/stores/table-data/records.ts
  mathesar_ui/src/stores/table-data/tabularData.ts
  mathesar_ui/src/stores/table-data/types.ts
  mathesar_ui/src/systems/record-selector/RecordSelectorController.ts
  mathesar_ui/src/systems/table-view/constraints/NewFkConstraintModal.svelte
  mathesar_ui/src/systems/table-view/link-table/LinkTableModal.svelte
Labels: status: review

#1478 Create an endpoint for getting the dependents graph for tables
  db/dependents/__init__.py
  db/dependents/dependents_utils.py
  db/tests/tables/test_dependents.py
  mathesar/api/db/viewsets/tables.py
  mathesar/api/serializers/dependents.py
  mathesar/api/serializers/tables.py
  mathesar/models/base.py
  mathesar/tests/api/test_dependents_api.py
Labels: status: review

#1530 Cell Selection for table inspector
  mathesar_ui/src/components/NameWithIcon.svelte
  mathesar_ui/src/components/TableColumnName.svelte
  mathesar_ui/src/components/cell-fabric/CellFabric.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/CellWrapper.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/SteppedInputCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/checkbox/CheckboxCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/date-time/DateTimeCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/formatted-input/FormattedInputCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LinkedRecordCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/money/MoneyCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/number/NumberCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/select/SingleSelectCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/textarea/TextAreaCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/textbox/TextBoxCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/typeDefinitions.ts
  mathesar_ui/src/components/cell-fabric/data-types/components/uri/UriCell.svelte
  mathesar_ui/src/components/cell-fabric/utils.ts
  mathesar_ui/src/components/column/ColumnName.svelte
  mathesar_ui/src/stores/table-data/meta.ts
  mathesar_ui/src/stores/table-data/records.ts
  mathesar_ui/src/stores/table-data/selection.ts
  mathesar_ui/src/stores/table-data/tabularData.ts
  mathesar_ui/src/systems/table-view/StatusPane.svelte
  mathesar_ui/src/systems/table-view/actions-pane/ActionsPane.svelte
  mathesar_ui/src/systems/table-view/constraints/NewUniqueConstraintModal.svelte
  mathesar_ui/src/systems/table-view/header/Header.svelte
  mathesar_ui/src/systems/table-view/header/header-cell/HeaderCell.svelte
  mathesar_ui/src/systems/table-view/row/Row.svelte
  mathesar_ui/src/systems/table-view/row/RowCell.svelte
  mathesar_ui/src/systems/table-view/row/RowControl.svelte
Labels: status: review

#1404 Mathesar 946 record preview data
  db/tests/links/__init__.py
  mathesar/api/db/viewsets/queries.py
  mathesar/api/db/viewsets/records.py
  mathesar/api/pagination.py
  mathesar/api/serializers/records.py
  mathesar/api/serializers/table_settings.py
  mathesar/api/utils.py
  mathesar/tests/api/conftest.py
  mathesar/tests/api/test_record_api.py
  mathesar/tests/data/base_table.csv
  mathesar/tests/data/reference_table.csv
  mathesar/tests/data/relation_tables/author.csv
  mathesar/tests/data/relation_tables/items.csv
  mathesar/tests/data/relation_tables/publication.csv
  mathesar/tests/data/relation_tables/publisher.csv
  mathesar/utils/preview.py
Labels: status: review

#1528 Complete all json array filtering functions with tests
  db/functions/hints.py
  db/tests/types/test_json.py
  db/types/custom/json_array.py
  mathesar_ui/src/stores/abstract-types/operations/filtering.ts
Labels: status: review

#1529 Navigation Styling
  mathesar/templates/mathesar/base.html
  mathesar_ui/src/App.svelte
  mathesar_ui/src/component-library/button/Button.scss
  mathesar_ui/src/component-library/dropdown/Dropdown.scss
  mathesar_ui/src/components/EntityType.svelte
  mathesar_ui/src/components/Logo.svelte
  mathesar_ui/src/components/NameWithIcon.svelte
  mathesar_ui/src/systems/app-header/AppHeader.svelte
  mathesar_ui/src/systems/app-header/breadcrumb/Breadcrumb.svelte
  mathesar_ui/src/systems/app-header/breadcrumb/BreadcrumbLink.svelte
  mathesar_ui/src/systems/app-header/breadcrumb/BreadcrumbSelector.svelte
  mathesar_ui/src/systems/app-header/breadcrumb/BreadcrumbSeparatorIcon.svelte
  mathesar_ui/src/systems/table-view/actions-pane/ActionsPane.svelte
Labels: status: review

#1525 Add hyperlinks to Record Pages within PK and FK cells
  mathesar_ui/src/App.svelte
  mathesar_ui/src/components/LinkedRecord.svelte
  mathesar_ui/src/components/RecordPageLink.svelte
  mathesar_ui/src/components/cell-fabric/CellFabric.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/CellWrapper.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/SteppedInputCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LinkedRecordCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/number/NumberCell.svelte
  mathesar_ui/src/icons.ts
  mathesar_ui/src/routes/urls.ts
  mathesar_ui/src/stores/storeBasedUrls.ts
  mathesar_ui/src/systems/table-view/row/RowCell.svelte
Labels: status: waiting

#1506 Implementation for column mappings
  db/records/operations/insert.py
  db/tests/conftest.py
  db/tests/records/operations/test_insert.py
  db/tests/resources/books_import_from.sql
  db/tests/resources/books_import_target.sql
  mathesar/api/serializers/tables.py
  mathesar/models/base.py
Labels: status: review

#1538 Fix DB Query joining for demo
  db/queries/base.py
  db/tests/queries/conftest.py
  db/tests/queries/test_initial_relation.py
  db/tests/queries/test_transformations.py
  mathesar/models/query.py
  mathesar/tests/api/test_record_api.py
  mathesar/tests/query/test_base.py
Labels: status: waiting

#1541 Data explorer UI transformations - Filtering
  mathesar_ui/src/api/queries/queryList.ts
  mathesar_ui/src/component-library/common/actions/popper.ts
  mathesar_ui/src/component-library/dropdown-menu/DropdownMenu.svelte
  mathesar_ui/src/component-library/input-group/InputGroup.scss
  mathesar_ui/src/components/cell-fabric/data-types/components/date-time/DateTimeCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/date-time/DateTimeInput.svelte
  mathesar_ui/src/components/filter-entry/FilterEntry.svelte
  mathesar_ui/src/components/filter-entry/index.ts
  mathesar_ui/src/components/filter-entry/types.ts
  mathesar_ui/src/components/filter-entry/utils.ts
  mathesar_ui/src/routes/DataExplorerRoute.svelte
  mathesar_ui/src/stores/table-data/filtering.ts
  mathesar_ui/src/stores/tables.ts
  mathesar_ui/src/systems/query-builder/QueryBuilder.svelte
  mathesar_ui/src/systems/query-builder/QueryFilterTransformationModel.ts
  mathesar_ui/src/systems/query-builder/QueryListEntry.ts
  mathesar_ui/src/systems/query-builder/QueryManager.ts
  mathesar_ui/src/systems/query-builder/QueryModel.ts
  mathesar_ui/src/systems/query-builder/QuerySummarizationTransformationModel.ts
  mathesar_ui/src/systems/query-builder/QueryUndoRedoManager.ts
  mathesar_ui/src/systems/query-builder/column-selection-pane/ColumnSelectionPane.svelte
  mathesar_ui/src/systems/query-builder/column-selection-pane/SelectableColumn.svelte
  mathesar_ui/src/systems/query-builder/column-selection-pane/SelectableColumnTree.svelte
  mathesar_ui/src/systems/query-builder/output-config-sidebar/FilterTransformation.svelte
  mathesar_ui/src/systems/query-builder/output-config-sidebar/OutputConfigSidebar.svelte
  mathesar_ui/src/systems/query-builder/output-config-sidebar/TransformationsPane.svelte
  mathesar_ui/src/systems/query-builder/output-config-sidebar/transformationUtils.ts
  mathesar_ui/src/systems/query-builder/result-pane/ResultPane.svelte
  mathesar_ui/src/systems/query-builder/utils.ts
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/Filter.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/FilterEntries.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/utils.ts
Labels: status: review

#1518 Continued Record Selector UI implementation
  mathesar_ui/src/App.svelte
  mathesar_ui/src/api/tables/records.ts
  mathesar_ui/src/component-library/button/Button.svelte
  mathesar_ui/src/component-library/common/types/ArtificialEvents.ts
  mathesar_ui/src/component-library/common/utils/ImmutableMap.ts
  mathesar_ui/src/component-library/common/utils/inputUtils.ts
  mathesar_ui/src/component-library/debounce/Debounce.svelte
  mathesar_ui/src/component-library/debounce/__meta__/Debounce.stories.svelte
  mathesar_ui/src/component-library/formatted-input/FormattedInput.svelte
  mathesar_ui/src/component-library/index.ts
  mathesar_ui/src/component-library/modal/ControlledModal.svelte
  mathesar_ui/src/component-library/modal/IndependentModal.scss
  mathesar_ui/src/component-library/modal/IndependentModal.svelte
  mathesar_ui/src/component-library/modal/modalTypes.ts
  mathesar_ui/src/component-library/number-input/NumberInput.svelte
  mathesar_ui/src/component-library/number-input/StringifiedNumberInput.svelte
  mathesar_ui/src/component-library/text-area/TextArea.svelte
  mathesar_ui/src/components/KeyboardKey.svelte
  mathesar_ui/src/components/cell-fabric/DynamicInput.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/CellWrapper.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/ClearCue.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LaunchCue.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LinkedRecordCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LinkedRecordInput.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/money/MoneyCellInput.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/number/NumberCellInput.svelte
  mathesar_ui/src/components/cell-fabric/utils.ts
  mathesar_ui/src/stores/table-data/meta.ts
  mathesar_ui/src/stores/table-data/processedColumns.ts
  mathesar_ui/src/stores/table-data/records.ts
  mathesar_ui/src/stores/table-data/searchFuzzy.ts
  mathesar_ui/src/stores/table-data/tabularData.ts
  mathesar_ui/src/systems/query-builder/utils.ts
  mathesar_ui/src/systems/record-selector/Arrow.svelte
  mathesar_ui/src/systems/record-selector/CellArranger.svelte
  mathesar_ui/src/systems/record-selector/CellWrapper.svelte
  mathesar_ui/src/systems/record-selector/ModalRecordSelector.svelte
  mathesar_ui/src/systems/record-selector/NestedRecordSelector.svelte
  mathesar_ui/src/systems/record-selector/NewIndicator.svelte
  mathesar_ui/src/systems/record-selector/QuarterCircle.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorContent.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorController.ts
  mathesar_ui/src/systems/record-selector/RecordSelectorInput.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorModal.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorResults.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorTable.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorTitle.svelte
  mathesar_ui/src/systems/record-selector/recordSelectorTypes.ts
  mathesar_ui/src/systems/record-selector/recordSelectorUtils.ts
  mathesar_ui/src/systems/table-view/actions-pane/ActionsPane.svelte
  mathesar_ui/src/systems/table-view/header/header-cell/abstract-type-configuration/AbstractTypeOptions.svelte
  mathesar_ui/src/systems/table-view/header/header-cell/abstract-type-configuration/SetDefaultValue.svelte
Labels: status: review

#1546 Small file reorganization for the tables API TypeScript types
  mathesar_ui/src/api/queries/queryList.ts
  mathesar_ui/src/api/tables.ts
  mathesar_ui/src/api/tables/joinable_tables.ts
  mathesar_ui/src/components/SelectTable.svelte
  mathesar_ui/src/components/SelectTableWithinCurrentSchema.svelte
  mathesar_ui/src/components/TableName.svelte
  mathesar_ui/src/components/cell-fabric/utils.ts
  mathesar_ui/src/pages/table/TablePage.svelte
  mathesar_ui/src/stores/fileImports.ts
  mathesar_ui/src/stores/table-data/manager.ts
  mathesar_ui/src/stores/tables.ts
  mathesar_ui/src/systems/app-header/breadcrumb/EntitySelector.svelte
  mathesar_ui/src/systems/app-header/breadcrumb/breadcrumbTypes.ts
  mathesar_ui/src/systems/query-builder/QueryBuilder.svelte
  mathesar_ui/src/systems/query-builder/QueryManager.ts
  mathesar_ui/src/systems/query-builder/utils.ts
  mathesar_ui/src/systems/table-view/TableView.svelte
  mathesar_ui/src/systems/table-view/actions-pane/ActionsPane.svelte
  mathesar_ui/src/systems/table-view/constraints/NewFkConstraintModal.svelte
  mathesar_ui/src/systems/table-view/link-table/LinkTableModal.svelte
  mathesar_ui/src/utils/preloadData.ts
Labels: status: review

#1550 Date, Time, and DateTime presets
  mathesar_ui/src/component-library/date-time-picker/InlineDateTimePicker.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/date-time/DateTimeInput.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/date-time/Presets.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/typeDefinitions.ts
  mathesar_ui/src/components/cell-fabric/data-types/date.ts
  mathesar_ui/src/components/cell-fabric/data-types/datetime.ts
  mathesar_ui/src/components/cell-fabric/data-types/time.ts
  mathesar_ui/src/components/filter-entry/FilterEntry.svelte
Labels: status: review

#1551 Improve breadcrumbs
  mathesar_ui/src/systems/app-header/breadcrumb/BreadcrumbSelector.svelte
  mathesar_ui/src/systems/app-header/breadcrumb/breadcrumbUtils.ts
Labels: work: frontend, status: review

#1540 Get parent object type and refactor dependent utils
  db/dependents/dependents_utils.py
  mathesar/api/serializers/dependents.py
  mathesar/tests/api/test_dependents_api.py
Labels: status: review

#1406 Fix constraints endpoint's error behaviour
  mathesar/api/db/viewsets/constraints.py
  mathesar/api/exceptions/error_codes.py
  mathesar/api/exceptions/validation_exceptions/exceptions.py
  mathesar/api/serializers/constraints.py
  mathesar/tests/api/test_constraint_api.py
Labels: status: waiting

#1547 Summarization transform
  conftest.py
  db/columns/base.py
  db/functions/base.py
  db/functions/hints.py
  db/functions/operations/apply.py
  db/functions/operations/deserialize.py
  db/tests/resources/library_add_checkouts.sql
  db/tests/resources/library_without_checkouts.sql
  db/transforms/base.py
  db/transforms/operations/apply.py
  db/types/custom/datetime.py
  mathesar/models/query.py
  mathesar/tests/api/query/test_library_demo_reports.py
Labels: status: review

#1545 Record summary UI
  mathesar/api/db/viewsets/records.py
  mathesar/api/pagination.py
  mathesar/api/serializers/records.py
  mathesar/api/serializers/shared_serializers.py
  mathesar/api/utils.py
  mathesar/tests/api/conftest.py
  mathesar/tests/api/test_column_api_display_options.py
  mathesar/tests/api/test_record_api.py
  mathesar/utils/preview.py
  mathesar_ui/src/api/tables/records.ts
  mathesar_ui/src/components/LinkedRecord.svelte
  mathesar_ui/src/components/cell-fabric/CellFabric.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LinkedRecordCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LinkedRecordInput.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/typeDefinitions.ts
  mathesar_ui/src/stores/table-data/records.ts
  mathesar_ui/src/systems/record-selector/RecordSelectorResults.svelte
  mathesar_ui/src/systems/table-view/row/Row.svelte
  mathesar_ui/src/systems/table-view/row/RowCell.svelte
Labels: status: review

#1486 First time setup script
  Makefile
  README.md
  initial_setup.sh
Labels: status: review

#1555 Table grouping
  mathesar/tests/api/query/test_library_demo_reports.py
  mathesar_ui/src/App.svelte
  mathesar_ui/src/api/tables/records.ts
  mathesar_ui/src/component-library/list-box/ListBox.svelte
  mathesar_ui/src/component-library/select/Select.svelte
  mathesar_ui/src/component-library/select/SelectTypes.ts
  mathesar_ui/src/components/SelectTable.svelte
  mathesar_ui/src/components/SelectTableWithinCurrentSchema.svelte
  mathesar_ui/src/components/group-entry/GroupEntry.svelte
  mathesar_ui/src/components/group-entry/types.ts
  mathesar_ui/src/stores/abstract-types/index.ts
  mathesar_ui/src/stores/abstract-types/operations/preprocFunctions.ts
  mathesar_ui/src/stores/abstract-types/types.ts
  mathesar_ui/src/stores/table-data/grouping.ts
  mathesar_ui/src/stores/table-data/processedColumns.ts
  mathesar_ui/src/stores/table-data/records.ts
  mathesar_ui/src/stores/table-data/selection.ts
  mathesar_ui/src/stores/table-data/sorting.ts
  mathesar_ui/src/stores/table-data/tabularData.ts
  mathesar_ui/src/stores/table-data/types.ts
  mathesar_ui/src/systems/query-builder/QueryBuilder.svelte
  mathesar_ui/src/systems/query-builder/utils.ts
  mathesar_ui/src/systems/table-view/Body.svelte
  mathesar_ui/src/systems/table-view/ScrollAndResetHandler.svelte
  mathesar_ui/src/systems/table-view/actions-pane/ActionsPane.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/Group.svelte
  mathesar_ui/src/systems/table-view/constraints/NewFkConstraintModal.svelte
  mathesar_ui/src/systems/table-view/geometry.ts
  mathesar_ui/src/systems/table-view/header/header-cell/DefaultOptions.svelte
  mathesar_ui/src/systems/table-view/row/GroupHeader.svelte
  mathesar_ui/src/systems/table-view/row/Row.svelte
Labels: status: review

#1558 Focus breadcrumb text input when the BreadcrumbSelector opens
  mathesar_ui/src/systems/app-header/breadcrumb/BreadcrumbSelector.svelte
Labels: status: review

#1560 Increases breadcrumb selector max height
  mathesar_ui/src/component-library/dropdown/Dropdown.scss
  mathesar_ui/src/systems/app-header/breadcrumb/BreadcrumbSelector.svelte
Labels: status: review

#1543 Style Table
  mathesar_ui/src/App.svelte
  mathesar_ui/src/component-library/dropdown/Dropdown.scss
  mathesar_ui/src/component-library/pagination/Pagination.scss
  mathesar_ui/src/components/NameWithIcon.svelte
  mathesar_ui/src/components/sheet/SheetHeader.svelte
  mathesar_ui/src/systems/table-view/StatusPane.svelte
  mathesar_ui/src/systems/table-view/header/header-cell/HeaderCell.svelte
  mathesar_ui/src/systems/table-view/header/new-column-cell/NewColumnCell.scss
  mathesar_ui/src/systems/table-view/header/new-column-cell/NewColumnCell.svelte
  mathesar_ui/src/systems/table-view/row/NewRecordMessage.svelte
  mathesar_ui/src/systems/table-view/row/Row.svelte
Labels: status: review

#1568 Table inspector/table properties
  mathesar_ui/src/App.svelte
  mathesar_ui/src/component-library/cancel-or-proceed-button-pair/CancelOrProceedButtonPair.svelte
  mathesar_ui/src/component-library/dropdown/Dropdown.svelte
  mathesar_ui/src/component-library/spinner-button/SpinnerButton.svelte
  mathesar_ui/src/components/EditableTextWithActions.svelte
  mathesar_ui/src/components/ModalTextInputForm.svelte
  mathesar_ui/src/components/SaveStatusIndicator.svelte
  mathesar_ui/src/icons.ts
  mathesar_ui/src/pages/database/SchemaRow.svelte
  mathesar_ui/src/stores/table-data/display.ts
  mathesar_ui/src/systems/table-view/TableView.svelte
  mathesar_ui/src/systems/table-view/actions-pane/ActionsPane.svelte
  mathesar_ui/src/systems/table-view/actions-pane/RenameTableModal.svelte
  mathesar_ui/src/systems/table-view/constraints/TableConstraint.svelte
  mathesar_ui/src/systems/table-view/constraints/TableConstraints.svelte
  mathesar_ui/src/systems/table-view/table-inspector/ColumnMode.svelte
  mathesar_ui/src/systems/table-view/table-inspector/RenameTableProperty.svelte
  mathesar_ui/src/systems/table-view/table-inspector/TableInspector.svelte
  mathesar_ui/src/systems/table-view/table-inspector/TableMode.svelte
Labels: status: review

#1576 Find and distinguish active breadcrumb selector entry
  mathesar_ui/src/systems/app-header/breadcrumb/BreadcrumbSelector.svelte
  mathesar_ui/src/systems/app-header/breadcrumb/EntitySelector.svelte
  mathesar_ui/src/systems/app-header/breadcrumb/SchemaSelector.svelte
  mathesar_ui/src/systems/app-header/breadcrumb/breadcrumbTypes.ts
Labels: status: review

#1573 Data explorer transforms - summarization
  mathesar_ui/src/api/queries/queryList.ts
  mathesar_ui/src/component-library/common/utils/inputUtils.ts
  mathesar_ui/src/component-library/debounce/Debounce.svelte
  mathesar_ui/src/components/group-entry/GroupEntry.svelte
  mathesar_ui/src/components/group-entry/types.ts
  mathesar_ui/src/pages/table/TablePage.svelte
  mathesar_ui/src/routes/DataExplorerRoute.svelte
  mathesar_ui/src/stores/table-data/types.ts
  mathesar_ui/src/systems/query-builder/QueryManager.ts
  mathesar_ui/src/systems/query-builder/QuerySummarizationTransformationModel.ts
  mathesar_ui/src/systems/query-builder/output-config-sidebar/FilterTransformation.svelte
  mathesar_ui/src/systems/query-builder/output-config-sidebar/OutputConfigSidebar.svelte
  mathesar_ui/src/systems/query-builder/output-config-sidebar/TransformationsPane.svelte
  mathesar_ui/src/systems/query-builder/output-config-sidebar/summarization/Aggregation.svelte
  mathesar_ui/src/systems/query-builder/output-config-sidebar/summarization/SummarizationTransformation.svelte
  mathesar_ui/src/systems/query-builder/output-config-sidebar/transformationUtils.ts
  mathesar_ui/src/systems/query-builder/urlSerializationUtils.ts
  mathesar_ui/src/systems/table-view/TableView.svelte
  mathesar_ui/src/systems/table-view/actions-pane/ActionsPane.svelte
Labels: status: review

#1564 Use Record Selector to navigate to Record Page
  mathesar_ui/src/App.svelte
  mathesar_ui/src/icons.ts
  mathesar_ui/src/pages/schema/SchemaPage.svelte
  mathesar_ui/src/systems/app-header/breadcrumb/BreadcrumbItem.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorController.ts
  mathesar_ui/src/systems/record-selector/RecordSelectorNavigationButton.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorResults.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorRow.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorTable.svelte
  mathesar_ui/src/systems/record-selector/recordSelectorTypes.ts
Labels: status: review
