Repository mathesar-foundation/mathesar, pull requests merged in 2022-10, with the labels that each got.

#1742 Add authentication and login page
  README.md
  config/settings.py
  docker-compose.yml
  initial_setup.sh
  mathesar/templates/registration/login.html
  mathesar/tests/api/conftest.py
  mathesar/tests/conftest.py
  mathesar/tests/integration/conftest.py
  mathesar/urls.py
  mathesar/views.py
  pyproject.toml
Labels: status: review

#1746 Improve unique violation exception
  mathesar/api/exceptions/database_exceptions/exceptions.py
  mathesar/api/serializers/records.py
  mathesar/tests/api/test_record_api.py
Labels: status: review

#1751 Reset migrations, added custom user model.
  config/settings.py
  mathesar/admin.py
  mathesar/migrations/0001_initial.py
  mathesar/migrations/0002_auto_20220719_1112.py
  mathesar/migrations/0003_auto_20220803_1637.py
  mathesar/migrations/0004_auto_20220927_0657.py
  mathesar/models/__init__.py
  mathesar/models/base.py
  mathesar/models/users.py
Labels: status: review

#1712 Prefetch column properties when fetching list of columns
  db/columns/operations/select.py
  db/constraints/base.py
  db/constraints/operations/create.py
  db/tables/operations/move_columns.py
  db/tables/operations/split.py
  mathesar/api/db/viewsets/columns.py
  mathesar/models/base.py
  mathesar/tests/api/test_table_api.py
Labels: status: review

#1759 Reduce max parallel testing threads to 4
  setup.cfg
Labels: affects: dx, status: review

#1745 Improve Constraint syncing performance
  mathesar/migrations/0003_auto_20221006_2340.py
  mathesar/models/base.py
  mathesar/state/django.py
Labels: status: waiting

#1728 Improve performance when syncing DB objects into Django database
  db/columns/operations/select.py
  db/tables/operations/select.py
  mathesar/migrations/0002_auto_20221006_2232.py
  mathesar/migrations/0003_auto_20221006_2340.py
  mathesar/models/base.py
  mathesar/signals.py
  mathesar/state/django.py
  mathesar/tests/api/test_record_api.py
  mathesar/utils/tables.py
Labels: status: review

#1753 Added user API, allows CRUD on users.
  mathesar/api/serializers/users.py
  mathesar/api/ui/viewsets/__init__.py
  mathesar/api/ui/viewsets/users.py
  mathesar/tests/api/test_user_api.py
  mathesar/urls.py
Labels: status: review

#1775 Metadata bug fixes
  db/constraints/operations/select.py
  db/constraints/utils.py
  mathesar/models/base.py
  mathesar/tests/api/test_constraint_api.py
  mathesar/utils/joins.py
Labels: status: review

#1752 Improve Row typing, clean up table-data imports
  mathesar_ui/src/components/SelectProcessedColumns.svelte
  mathesar_ui/src/components/column/ProcessedColumnName.svelte
  mathesar_ui/src/pages/record/DirectField.svelte
  mathesar_ui/src/pages/record/RecordPage.svelte
  mathesar_ui/src/pages/record/RecordPageContent.svelte
  mathesar_ui/src/pages/record/TableWidget.svelte
  mathesar_ui/src/pages/table/TablePage.svelte
  mathesar_ui/src/stores/table-data/display.ts
  mathesar_ui/src/stores/table-data/index.ts
  mathesar_ui/src/stores/table-data/records.ts
  mathesar_ui/src/stores/table-data/selection.ts
  mathesar_ui/src/stores/table-data/types.ts
  mathesar_ui/src/stores/table-data/utils.ts
  mathesar_ui/src/systems/data-explorer/urlSerializationUtils.ts
  mathesar_ui/src/systems/record-selector/ColumnResizer.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorContent.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorInput.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorResults.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorTable.svelte
  mathesar_ui/src/systems/table-view/Body.svelte
  mathesar_ui/src/systems/table-view/ScrollAndResetHandler.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/Filter.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/FilterEntries.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/Group.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/Sort.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/utils.ts
  mathesar_ui/src/systems/table-view/constraints/NewUniqueConstraintModal.svelte
  mathesar_ui/src/systems/table-view/constraints/TableConstraints.svelte
  mathesar_ui/src/systems/table-view/header/Header.svelte
  mathesar_ui/src/systems/table-view/header/header-cell/DefaultOptions.svelte
  mathesar_ui/src/systems/table-view/header/header-cell/HeaderCell.svelte
  mathesar_ui/src/systems/table-view/row/GroupHeader.svelte
  mathesar_ui/src/systems/table-view/row/Row.svelte
  mathesar_ui/src/systems/table-view/row/RowCell.svelte
  mathesar_ui/src/systems/table-view/row/RowControl.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnActions.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnDisplayProperties.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnMode.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnOptions.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnType.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/RenameColumn.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/column-extraction/ExtractColumnsModalController.ts
  mathesar_ui/src/systems/table-view/table-inspector/column/column-extraction/columnExtractionTypes.ts
  mathesar_ui/src/systems/table-view/table-inspector/column/column-extraction/columnExtractionUtils.ts
  mathesar_ui/src/systems/table-view/table-inspector/record/RecordMode.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record/RowActions.svelte
Labels: status: waiting

#1779 Fix error when creating a new record
  mathesar_ui/src/stores/table-data/records.ts
Labels: status: review

#1749 Remove 'table from fk' type of dependents from graph
  db/dependents/dependents_utils.py
  db/tests/dependents/test_dependents.py
  mathesar/tests/api/test_dependents_api.py
Labels: status: waiting

#1806 Fixes critical bugs in Table page
  mathesar_ui/src/components/cell-fabric/data-types/components/money/MoneyCellInput.svelte
  mathesar_ui/src/stores/table-data/display.ts
  mathesar_ui/src/stores/table-data/meta.ts
  mathesar_ui/src/stores/table-data/records.ts
  mathesar_ui/src/systems/record-selector/RecordSelectorResults.svelte
  mathesar_ui/src/systems/table-view/Body.svelte
  mathesar_ui/src/systems/table-view/row/Row.svelte
  mathesar_ui/src/systems/table-view/row/RowCell.svelte
Labels: status: review

#1819 Added create empty table button on schema page
  mathesar_ui/src/pages/schema/SchemaPage.svelte
Labels: status: review

#1821 Increase max link search depth to 3
  mathesar/api/db/viewsets/tables.py
Labels: work: backend, status: review

#1589 Switch query validation exception to use our error infrastructure
  mathesar/api/exceptions/error_codes.py
  mathesar/api/exceptions/validation_exceptions/exceptions.py
  mathesar/migrations/0001_initial.py
  mathesar/migrations/0005_auto_20221014_1109.py
  mathesar/models/query.py
  mathesar/tests/api/query/test_query_api.py
Labels: status: review

#1837 Fix bulk deleting reflected column bug by using OR condition instead of AND
  mathesar/state/django.py
  mathesar/tests/api/test_column_api.py
Labels: status: review

#1826 Metadata refactor's postponed changes
  db/columns/operations/alter.py
  db/columns/operations/select.py
  db/queries/base.py
  db/tables/operations/merge.py
  db/tests/tables/operations/test_move_columns.py
Labels: work: backend, status: review

#1698 Mapping suggestions
  db/columns/exceptions.py
  db/columns/utils.py
  db/tests/columns/operations/test_mapping.py
  mathesar/api/db/viewsets/tables.py
  mathesar/api/exceptions/database_exceptions/exceptions.py
  mathesar/api/exceptions/error_codes.py
  mathesar/models/base.py
Labels: status: review

#1839 Re-create data map inside the schemaMap store
  mathesar_ui/src/stores/schemas.ts
Labels: status: review

#1810 make row order deterministic in more cases
  db/columns/utils.py
  db/queries/base.py
  db/records/exceptions.py
  db/records/operations/select.py
  db/records/operations/sort.py
  db/tests/queries/test_initial_relation.py
  db/tests/records/operations/test_sort.py
  db/transforms/base.py
  mathesar/api/db/viewsets/records.py
  mathesar/models/base.py
  mathesar/tests/api/test_record_api.py
Labels: status: waiting

#1741 Display Record Summary in more places
  mathesar/api/db/viewsets/records.py
  mathesar/api/utils.py
  mathesar/tests/api/test_record_api.py
  mathesar_ui/src/api/tables/records.ts
  mathesar_ui/src/components/LinkedRecord.svelte
  mathesar_ui/src/components/cell-fabric/CellFabric.svelte
  mathesar_ui/src/components/cell-fabric/DynamicInput.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LinkedRecordCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LinkedRecordInput.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/typeDefinitions.ts
  mathesar_ui/src/components/filter-entry/FilterEntry.svelte
  mathesar_ui/src/pages/record/DirectField.svelte
  mathesar_ui/src/pages/record/RecordStore.ts
  mathesar_ui/src/stores/table-data/record-summaries/RecordSummaryStore.ts
  mathesar_ui/src/stores/table-data/record-summaries/__tests__/recordSummaryUtils.test.ts
  mathesar_ui/src/stores/table-data/record-summaries/recordSummaryUtils.ts
  mathesar_ui/src/stores/table-data/records.ts
  mathesar_ui/src/systems/record-selector/RecordSelectorController.ts
  mathesar_ui/src/systems/record-selector/RecordSelectorInput.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorResults.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorTable.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/FilterEntries.svelte
  mathesar_ui/src/systems/table-view/row/GroupHeader.svelte
  mathesar_ui/src/systems/table-view/row/GroupHeaderCellValue.svelte
  mathesar_ui/src/systems/table-view/row/Row.svelte
  mathesar_ui/src/systems/table-view/row/RowCell.svelte
  mathesar_ui/src/utils/__tests__/recordSummary.test.ts
  mathesar_ui/src/utils/recordSummary.ts
  mathesar_ui/src/utils/recordSummaryTypes.ts
Labels: status: review

#1836 Fixes some high priority bugs in Table page
  mathesar/api/serializers/shared_serializers.py
  mathesar/tests/api/test_column_api_display_options.py
  mathesar/tests/api/test_table_api.py
  mathesar_ui/src/api/tables/columns.ts
  mathesar_ui/src/component-library/number-input/__tests__/NumberInput.test.ts
  mathesar_ui/src/component-library/number-input/number-formatter/formatter.ts
  mathesar_ui/src/component-library/number-input/number-formatter/options.ts
  mathesar_ui/src/components/cell-fabric/data-types/money.ts
  mathesar_ui/src/components/cell-fabric/data-types/number.ts
  mathesar_ui/src/pages/table/TablePage.svelte
  mathesar_ui/src/stores/abstract-types/type-configs/money.ts
  mathesar_ui/src/stores/abstract-types/type-configs/number.ts
  mathesar_ui/src/stores/table-data/index.ts
  mathesar_ui/src/stores/table-data/manager.ts
  mathesar_ui/src/systems/table-view/link-table/LinkTableModal.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/TableActions.svelte
Labels: status: review

#1848 Some table widget improvements
  mathesar_ui/src/pages/record/TableWidget.svelte
  mathesar_ui/src/pages/record/Widgets.svelte
  mathesar_ui/src/stores/table-data/TableStructure.ts
  mathesar_ui/src/stores/table-data/columns.ts
  mathesar_ui/src/stores/table-data/display.ts
  mathesar_ui/src/stores/table-data/filtering.ts
  mathesar_ui/src/stores/table-data/index.ts
  mathesar_ui/src/stores/table-data/records.ts
  mathesar_ui/src/stores/table-data/selection.ts
  mathesar_ui/src/stores/table-data/tabularData.ts
  mathesar_ui/src/systems/record-selector/RecordSelectorResults.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorTable.svelte
  mathesar_ui/src/systems/table-view/Body.svelte
  mathesar_ui/src/systems/table-view/actions-pane/ActionsPane.svelte
  mathesar_ui/src/systems/table-view/actions-pane/MiniActionsPane.svelte
  mathesar_ui/src/systems/table-view/constraints/NewFkConstraintModal.svelte
  mathesar_ui/src/systems/table-view/constraints/TableConstraint.svelte
  mathesar_ui/src/systems/table-view/header/Header.svelte
  mathesar_ui/src/systems/table-view/link-table/LinkTableModal.svelte
  mathesar_ui/src/systems/table-view/row/Row.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/RenameColumn.svelte
Labels: status: review

#1849 Improved fkey referenced row deletion error
  db/constraints/operations/select.py
  mathesar/api/db/viewsets/records.py
  mathesar/api/exceptions/database_exceptions/exceptions.py
  mathesar/tests/api/test_record_api.py
Labels: status: review

#1860 Optionally accept column name when splitting table
  db/tables/operations/split.py
  mathesar/api/db/viewsets/tables.py
  mathesar/api/serializers/tables.py
  mathesar/models/base.py
  mathesar/tests/api/test_table_api.py
Labels: status: review

#1793 DB Page re-design
  mathesar_ui/src/App.svelte
  mathesar_ui/src/component-library/alert/Alert.scss
  mathesar_ui/src/component-library/alert/Alert.svelte
  mathesar_ui/src/component-library/alert/AlertTypes.ts
  mathesar_ui/src/component-library/button/Button.scss
  mathesar_ui/src/component-library/common/icons.ts
  mathesar_ui/src/component-library/common/styles/components/input.scss
  mathesar_ui/src/component-library/confirmation/ConfirmationController.ts
  mathesar_ui/src/component-library/dropdown-menu/DropdownMenu.svelte
  mathesar_ui/src/component-library/dropdown/Dropdown.scss
  mathesar_ui/src/component-library/dropdown/Dropdown.svelte
  mathesar_ui/src/component-library/index.ts
  mathesar_ui/src/component-library/labeled-input/LabeledInput.scss
  mathesar_ui/src/component-library/menu/ButtonMenuItem.svelte
  mathesar_ui/src/component-library/menu/Menu.scss
  mathesar_ui/src/component-library/spinner-button/SpinnerButton.svelte
  mathesar_ui/src/component-library/styles.scss
  mathesar_ui/src/component-library/text-input/TextInput.svelte
  mathesar_ui/src/component-library/text-input/TextInputTypes.ts
  mathesar_ui/src/component-library/text-input/TextInputWithPrefix.svelte
  mathesar_ui/src/component-library/tutorial/Tutorial.scss
  mathesar_ui/src/component-library/tutorial/Tutorial.svelte
  mathesar_ui/src/components/AppHeader.svelte
  mathesar_ui/src/components/AppSecondaryHeader.svelte
  mathesar_ui/src/components/NameAndDescInputModalForm.svelte
  mathesar_ui/src/components/NameWithIcon.svelte
  mathesar_ui/src/components/PageTitleAndMeta.svelte
  mathesar_ui/src/components/SchemaName.svelte
  mathesar_ui/src/components/WhiteLogo.svelte
  mathesar_ui/src/components/breadcrumb/Breadcrumb.svelte
  mathesar_ui/src/components/breadcrumb/BreadcrumbItem.svelte
  mathesar_ui/src/layouts/LayoutWithHeader2.svelte
  mathesar_ui/src/pages/database/AddEditSchemaModal.svelte
  mathesar_ui/src/pages/database/DatabasePage.svelte
  mathesar_ui/src/pages/database/SchemaConstituentCounts.svelte
  mathesar_ui/src/pages/database/SchemaRow.svelte
  mathesar_ui/src/static-assets/white-logo.svg
Labels: status: review

#1852 Records API performance improvements
  db/constraints/operations/select.py
  mathesar/api/db/viewsets/records.py
  mathesar/api/pagination.py
  mathesar/models/base.py
  mathesar/utils/preview.py
Labels: status: review

#1853 Type suggestion API performance improvements
  db/columns/operations/alter.py
  db/columns/operations/infer_types.py
  db/schemas/operations/select.py
  db/schemas/utils.py
  db/tables/operations/infer_types.py
  db/tests/tables/operations/test_infer_types.py
  mathesar/utils/tables.py
Labels: status: review

#1747 Improve Linked Record Input UX
  mathesar_ui/src/App.svelte
  mathesar_ui/src/component-library/index.ts
  mathesar_ui/src/component-library/label/Label.svelte
  mathesar_ui/src/component-library/label/index.ts
  mathesar_ui/src/component-library/label/labelUtils.ts
  mathesar_ui/src/components/LinkedRecord.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/ClearCue.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LinkedRecordInput.svelte
  mathesar_ui/src/components/filter-entry/FilterEntry.svelte
  mathesar_ui/src/components/group-entry/GroupEntry.svelte
  mathesar_ui/src/icons.ts
  mathesar_ui/src/pages/database/SchemaRow.svelte
  mathesar_ui/src/pages/exploration/ActionsPane.svelte
  mathesar_ui/src/pages/import-preview/ImportPreviewPage.svelte
  mathesar_ui/src/stores/confirmation.ts
  mathesar_ui/src/systems/data-explorer/output-config-sidebar/OutputConfigSidebar.svelte
  mathesar_ui/src/systems/data-explorer/output-config-sidebar/TransformationsPane.svelte
  mathesar_ui/src/systems/table-view/actions-pane/ActionsPane.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/Sort.svelte
  mathesar_ui/src/systems/table-view/constraints/TableConstraint.svelte
  mathesar_ui/src/systems/table-view/header/header-cell/DefaultOptions.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnActions.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record/RowActions.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/TableActions.svelte
Labels: status: review

#1864 Cursor closed error hacky fix
  config/settings.py
  mathesar/middleware.py
Labels: status: review

#1872 use fresh metadata for enriching table columns
  db/columns/utils.py
  mathesar/models/base.py
Labels: status: review
