Repository mathesar-foundation/mathesar, pull requests merged in 2022-09, with the labels that each got.

#1575 Style database and schema home pages
  config/settings.py
  mathesar/templates/mathesar/base.html
  mathesar_ui/__mocks__/fileMock.cjs
  mathesar_ui/jest.config.cjs
  mathesar_ui/src/App.svelte
  mathesar_ui/src/component-library/button/Button.scss
  mathesar_ui/src/components/Logo.svelte
  mathesar_ui/src/pages/database/DatabasePage.svelte
  mathesar_ui/src/pages/database/SchemaRow.svelte
  mathesar_ui/src/pages/schema/SchemaPage.svelte
  mathesar_ui/src/static-assets/logo.svg
  mathesar_ui/src/systems/app-header/AppHeader.svelte
  mathesar_ui/src/systems/app-header/breadcrumb/Breadcrumb.svelte
  mathesar_ui/tsconfig.json
  mathesar_ui/vite.config.js
Labels: status: review

#1572 Refactor dependents tests using library usecase
  db/dependents/dependents_utils.py
  db/tests/dependents/__init__.py
  db/tests/dependents/conftest.py
  db/tests/dependents/test_dependents.py
  db/tests/tables/test_dependents.py
  mathesar/tests/api/test_dependents_api.py
Labels: status: review

#1592 Data Explorer Styling
  mathesar_ui/src/components/EditableTitle.svelte
  mathesar_ui/src/systems/query-builder/QueryBuilder.svelte
  mathesar_ui/src/systems/query-builder/output-config-sidebar/OutputConfigSidebar.svelte
  mathesar_ui/src/systems/query-builder/output-config-sidebar/TransformationsPane.svelte
Labels: status: review

#1548 Handle constraint violations while import
  db/columns/exceptions.py
  db/records/operations/insert.py
  mathesar/api/db/viewsets/tables.py
  mathesar/api/exceptions/database_exceptions/exceptions.py
  mathesar/api/exceptions/error_codes.py
Labels: status: review

#1581 Record Page, first pass
  mathesar_ui/src/api/tables/joinable_tables.ts
  mathesar_ui/src/component-library/dropdown/Dropdown.svelte
  mathesar_ui/src/components/TableName.svelte
  mathesar_ui/src/components/sheet/Sheet.svelte
  mathesar_ui/src/icons.ts
  mathesar_ui/src/pages/record/DirectField.svelte
  mathesar_ui/src/pages/record/RecordPage.svelte
  mathesar_ui/src/pages/record/RecordPageContent.svelte
  mathesar_ui/src/pages/record/RecordStore.ts
  mathesar_ui/src/pages/record/TableWidget.svelte
  mathesar_ui/src/pages/record/Widgets.svelte
  mathesar_ui/src/pages/table/TablePage.svelte
  mathesar_ui/src/stores/table-data/TableStructure.ts
  mathesar_ui/src/stores/table-data/tabularData.ts
  mathesar_ui/src/systems/query-builder/QueryManager.ts
  mathesar_ui/src/systems/query-builder/result-pane/ResultPane.svelte
  mathesar_ui/src/systems/query-builder/utils.ts
  mathesar_ui/src/systems/record-selector/RecordSelectorTable.svelte
  mathesar_ui/src/systems/table-view/Body.svelte
  mathesar_ui/src/systems/table-view/TableView.svelte
  mathesar_ui/src/systems/table-view/actions-pane/ActionsPane.svelte
  mathesar_ui/src/systems/table-view/actions-pane/MiniActionsPane.svelte
  mathesar_ui/src/systems/table-view/header/Header.svelte
Labels: status: review

#1583 Return foreign key columns summary data when creating or retrieving a single record
  mathesar/api/db/viewsets/records.py
  mathesar/api/exceptions/mixins.py
  mathesar/api/serializers/table_settings.py
  mathesar/api/serializers/tables.py
  mathesar/models/base.py
  mathesar/tests/api/test_record_api.py
  mathesar/tests/api/test_table_api.py
  mathesar/tests/data/relation_tables/publication.csv
  mathesar_ui/src/pages/record/RecordStore.ts
  mathesar_ui/src/stores/table-data/records.ts
Labels: status: review

#1565 Add test for json object sorting as well as json array contains function
  db/functions/base.py
  db/tests/records/operations/test_sort.py
  db/tests/resources/json_sort.sql
  db/tests/types/test_json.py
  db/types/custom/json_array.py
  mathesar_ui/src/stores/abstract-types/operations/filtering.ts
Labels: status: review

#1567 add RPC-style endpoint to submit and run a query
  db/columns/base.py
  db/queries/base.py
  db/tests/queries/test_base.py
  mathesar/api/db/viewsets/queries.py
  mathesar/api/serializers/queries.py
  mathesar/models/query.py
  mathesar/tests/api/query/test_library_demo_reports.py
  mathesar/tests/api/query/test_query_run.py
Labels: status: review

#1577 Return views and indexes as dependents
  db/dependents/dependents_utils.py
  db/tests/dependents/test_dependents.py
  mathesar/api/serializers/dependents.py
Labels: status: review

#1609 Schema api updates
  mathesar/api/serializers/schemas.py
  mathesar/models/query.py
Labels: status: review

#1591 Table inspector/column properties
  mathesar_ui/src/components/cell-fabric/data-types/components/CellWrapper.svelte
  mathesar_ui/src/stores/table-data/columns.ts
  mathesar_ui/src/stores/table-data/display.ts
  mathesar_ui/src/stores/table-data/records.ts
  mathesar_ui/src/stores/table-data/selection.ts
  mathesar_ui/src/stores/table-data/tabularData.ts
  mathesar_ui/src/systems/table-view/TableView.svelte
  mathesar_ui/src/systems/table-view/actions-pane/ActionsPane.svelte
  mathesar_ui/src/systems/table-view/header/header-cell/abstract-type-configuration/AbstractTypeConfiguration.scss
  mathesar_ui/src/systems/table-view/header/header-cell/abstract-type-configuration/AbstractTypeConfiguration.svelte
  mathesar_ui/src/systems/table-view/row/RowCell.svelte
  mathesar_ui/src/systems/table-view/table-inspector/ColumnMode.svelte
  mathesar_ui/src/systems/table-view/table-inspector/TableInspector.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnActions.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnDisplayProperties.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnMode.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnOptions.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnType.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/RenameColumn.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record/RecordMode.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record/RowActions.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/RenameTable.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/TableActions.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/TableMode.svelte
  mathesar_ui/src/utils/errors.ts
Labels: status: review

#1607 Add schema and table comments
  db/schemas/operations/alter.py
  db/schemas/operations/create.py
  db/schemas/operations/select.py
  db/tables/operations/alter.py
  db/tables/operations/create.py
  db/tables/operations/select.py
  db/tests/schemas/operations/test_alter.py
  db/tests/schemas/operations/test_select.py
  db/tests/tables/operations/test_alter.py
  db/tests/tables/operations/test_create.py
  db/tests/tables/operations/test_select.py
  mathesar/api/db/viewsets/schemas.py
  mathesar/api/serializers/schemas.py
  mathesar/api/serializers/tables.py
  mathesar/imports/csv.py
  mathesar/models/base.py
  mathesar/models/query.py
  mathesar/tests/api/test_schema_api.py
  mathesar/tests/api/test_table_api.py
  mathesar/utils/schemas.py
  mathesar/utils/tables.py
Labels: status: review

#1585 Add dependents endpoint to schema resource
  db/dependents/dependents_utils.py
  mathesar/api/db/viewsets/schemas.py
  mathesar/api/serializers/dependents.py
  mathesar/api/serializers/schemas.py
  mathesar/api/serializers/tables.py
  mathesar/models/base.py
  mathesar/tests/api/test_dependents_api.py
  mathesar/tests/api/test_schema_api.py
  mathesar/tests/api/test_table_api.py
Labels: status: waiting

#1624 Fix records endpoint's DELETE behavior
  mathesar/api/db/viewsets/records.py
  mathesar/api/exceptions/error_codes.py
  mathesar/api/utils.py
Labels: status: waiting

#1618 Improve readability of custom JS error class
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnType.svelte
  mathesar_ui/src/utils/errors.ts
Labels: status: review

#1616 Don't force Table Inspector to be visible after fetching columns
  mathesar_ui/src/stores/table-data/tabularData.ts
Labels: status: review

#1620 Make a few small improvements to the breadcrumb selector
  mathesar_ui/src/component-library/common/utils/__tests__/stringUtils.test.ts
  mathesar_ui/src/component-library/common/utils/stringUtils.ts
  mathesar_ui/src/component-library/index.ts
  mathesar_ui/src/component-library/match-highlighter/Match.svelte
  mathesar_ui/src/component-library/match-highlighter/MatchHighlighter.svelte
  mathesar_ui/src/component-library/match-highlighter/__meta__/MatchHighlighter.stories.svelte
  mathesar_ui/src/component-library/match-highlighter/__tests__/matchHighlighterUtils.test.ts
  mathesar_ui/src/component-library/match-highlighter/matchHighlighterTypes.ts
  mathesar_ui/src/component-library/match-highlighter/matchHighlighterUtils.ts
  mathesar_ui/src/systems/app-header/breadcrumb/BreadcrumbSelector.svelte
  mathesar_ui/src/systems/app-header/breadcrumb/BreadcrumbSelectorRow.svelte
  mathesar_ui/src/systems/app-header/breadcrumb/EntitySelector.svelte
  mathesar_ui/src/systems/app-header/breadcrumb/SchemaSelector.svelte
  mathesar_ui/src/systems/app-header/breadcrumb/breadcrumbTypes.ts
  mathesar_ui/src/systems/app-header/breadcrumb/breadcrumbUtils.ts
  mathesar_ui/src/systems/record-selector/RecordSelectorNavigationButton.svelte
Labels: status: review

#1635 Show table and queries count on db page from API
  mathesar_ui/src/AppTypes.ts
  mathesar_ui/src/pages/schema/SchemaPage.svelte
Labels: status: review

#1670 Filter before other operations
  db/tests/tables/operations/test_select.py
  db/transforms/operations/apply.py
  mathesar/tests/api/test_record_api.py
Labels: status: review

#1627 Prefetch SQLAlchemy Table when fetching a list of Django Tables
  THIRDPARTY
  mathesar/api/db/viewsets/tables.py
  mathesar/models/base.py
  mathesar/utils/prefetch.py
Labels: status: review

#1634 Landing page to be db page
  mathesar/urls.py
  mathesar/views.py
  mathesar_ui/src/stores/queries.ts
  mathesar_ui/src/stores/schemas.ts
  mathesar_ui/src/stores/tables.ts
  mathesar_ui/src/utils/preloadData.ts
Labels: status: review

#1629 Better error handling for invalid dates and date formats.
  db/records/exceptions.py
  db/records/operations/update.py
  mathesar/api/exceptions/database_exceptions/exceptions.py
  mathesar/api/exceptions/error_codes.py
  mathesar/api/serializers/records.py
  mathesar/tests/api/test_record_api.py
Labels: status: review

#1695 Minor fix for PR workflow
  .github/workflows/update-project-on-pr-label.yml
Labels: type: bug, work: infrastructure, status: waiting

#1608 Get column dependents; return column as a dependent
  db/dependents/dependents_utils.py
  db/tests/dependents/test_dependents.py
  mathesar/api/db/viewsets/columns.py
  mathesar/api/serializers/columns.py
  mathesar/api/serializers/dependents.py
  mathesar/models/base.py
  mathesar/tests/api/test_column_api.py
  mathesar/tests/api/test_dependents_api.py
Labels: status: review

#1687 Extract columns UI
  mathesar_ui/src/api/tables.ts
  mathesar_ui/src/component-library/index.ts
  mathesar_ui/src/component-library/modal/ModalMultiplexer.ts
  mathesar_ui/src/component-library/modal/index.ts
  mathesar_ui/src/component-library/multi-select/MultiSelect.scss
  mathesar_ui/src/component-library/multi-select/MultiSelect.svelte
  mathesar_ui/src/component-library/multi-select/__meta__/MultiSelect.stories.svelte
  mathesar_ui/src/component-library/multi-select/__meta__/Side.svelte
  mathesar_ui/src/component-library/select/__meta__/Select.stories.svelte
  mathesar_ui/src/component-library/styles.scss
  mathesar_ui/src/components/Form.svelte
  mathesar_ui/src/components/SelectProcessedColumns.svelte
  mathesar_ui/src/components/SelectTable.svelte
  mathesar_ui/src/components/TableColumnName.svelte
  mathesar_ui/src/components/column/ProcessedColumnName.svelte
  mathesar_ui/src/icons.ts
  mathesar_ui/src/pages/import-preview/ImportPreviewPage.svelte
  mathesar_ui/src/pages/record/DirectField.svelte
  mathesar_ui/src/stores/tables.ts
  mathesar_ui/src/systems/record-selector/RecordSelectorTable.svelte
  mathesar_ui/src/systems/table-view/constraints/NewUniqueConstraintModal.svelte
  mathesar_ui/src/systems/table-view/header/header-cell/HeaderCell.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnActions.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnMode.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/column-extraction/ExtractColumnsModal.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/column-extraction/ExtractColumnsModalController.ts
  mathesar_ui/src/systems/table-view/table-inspector/column/column-extraction/LinkedTableName.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/column-extraction/SelectLinkedTable.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/column-extraction/columnExtractionTypes.ts
  mathesar_ui/src/systems/table-view/table-inspector/column/column-extraction/columnExtractionUtils.ts
  mathesar_ui/src/utils/api.ts
Labels: status: waiting

#1630 Schema description
  mathesar_ui/src/AppTypes.ts
  mathesar_ui/src/components/ModalTextInputForm.svelte
  mathesar_ui/src/pages/database/AddEditSchemaModal.svelte
  mathesar_ui/src/pages/database/AddEditSchemaModalForm.svelte
  mathesar_ui/src/pages/database/SchemaRow.svelte
  mathesar_ui/src/stores/schemas.ts
Labels: status: review

#1707 Dataexplorer - use RPC endpoints, Implement Explorations page
  mathesar/views.py
  mathesar_ui/src/api/queries.ts
  mathesar_ui/src/components/NameAndDescInputModalForm.svelte
  mathesar_ui/src/components/QueryName.svelte
  mathesar_ui/src/components/SaveStatusIndicator.svelte
  mathesar_ui/src/components/breadcrumb/EntitySelector.svelte
  mathesar_ui/src/components/routing/EventfulRoute.svelte
  mathesar_ui/src/components/routing/MultiPathRoute.svelte
  mathesar_ui/src/components/routing/Observer.svelte
  mathesar_ui/src/components/routing/utils.ts
  mathesar_ui/src/components/sheet/Sheet.svelte
  mathesar_ui/src/components/sheet/SheetCell.svelte
  mathesar_ui/src/icons.ts
  mathesar_ui/src/pages/data-explorer/DataExplorerPage.svelte
  mathesar_ui/src/pages/database/AddEditSchemaModal.svelte
  mathesar_ui/src/pages/exploration/ActionsPane.svelte
  mathesar_ui/src/pages/exploration/ExplorationPage.svelte
  mathesar_ui/src/pages/schema/SchemaPage.svelte
  mathesar_ui/src/routes/DataExplorerRoute.svelte
  mathesar_ui/src/routes/ExplorationRoute.svelte
  mathesar_ui/src/routes/SchemaRoute.svelte
  mathesar_ui/src/routes/urls.ts
  mathesar_ui/src/stores/queries.ts
  mathesar_ui/src/systems/data-explorer/QueryBuilder.svelte
  mathesar_ui/src/systems/data-explorer/QueryFilterTransformationModel.ts
  mathesar_ui/src/systems/data-explorer/QueryListEntry.ts
  mathesar_ui/src/systems/data-explorer/QueryManager.ts
  mathesar_ui/src/systems/data-explorer/QueryModel.ts
  mathesar_ui/src/systems/data-explorer/QueryRunner.ts
  mathesar_ui/src/systems/data-explorer/QuerySummarizationTransformationModel.ts
  mathesar_ui/src/systems/data-explorer/QueryUndoRedoManager.ts
  mathesar_ui/src/systems/data-explorer/column-selection-pane/ColumnSelectionPane.svelte
  mathesar_ui/src/systems/data-explorer/column-selection-pane/SelectableColumn.svelte
  mathesar_ui/src/systems/data-explorer/column-selection-pane/SelectableColumnTree.svelte
  mathesar_ui/src/systems/data-explorer/column-selection-pane/TableGroupCollapsible.svelte
  mathesar_ui/src/systems/data-explorer/index.ts
  mathesar_ui/src/systems/data-explorer/output-config-sidebar/FilterTransformation.svelte
  mathesar_ui/src/systems/data-explorer/output-config-sidebar/OutputConfigSidebar.svelte
  mathesar_ui/src/systems/data-explorer/output-config-sidebar/TransformationsPane.svelte
  mathesar_ui/src/systems/data-explorer/output-config-sidebar/summarization/Aggregation.svelte
  mathesar_ui/src/systems/data-explorer/output-config-sidebar/summarization/SummarizationTransformation.svelte
  mathesar_ui/src/systems/data-explorer/output-config-sidebar/transformationUtils.ts
  mathesar_ui/src/systems/data-explorer/result-pane/ResultPane.svelte
  mathesar_ui/src/systems/data-explorer/result-pane/Results.svelte
  mathesar_ui/src/systems/data-explorer/types.ts
  mathesar_ui/src/systems/data-explorer/urlSerializationUtils.ts
  mathesar_ui/src/systems/data-explorer/utils.ts
  mathesar_ui/src/systems/query-builder/result-pane/ResultPane.svelte
  mathesar_ui/src/systems/table-view/actions-pane/ActionsPane.svelte
  mathesar_ui/src/systems/table-view/header/Header.svelte
  mathesar_ui/src/systems/table-view/row/Row.svelte
  mathesar_ui/src/utils/preloadData.ts
Labels: status: review

#1708 Display record summary in on Record Page title
  mathesar_ui/src/api/tables.ts
  mathesar_ui/src/components/LinkedRecord.svelte
  mathesar_ui/src/components/cell-fabric/CellFabric.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/typeDefinitions.ts
  mathesar_ui/src/pages/data-explorer/DataExplorerPage.svelte
  mathesar_ui/src/pages/database/DatabasePage.svelte
  mathesar_ui/src/pages/import-preview/ImportPreviewPage.svelte
  mathesar_ui/src/pages/import-upload/ImportUploadPage.svelte
  mathesar_ui/src/pages/pageTitleUtils.ts
  mathesar_ui/src/pages/record/RecordPage.svelte
  mathesar_ui/src/pages/record/RecordPageContent.svelte
  mathesar_ui/src/pages/record/RecordStore.ts
  mathesar_ui/src/pages/schema/SchemaPage.svelte
  mathesar_ui/src/pages/table/TablePage.svelte
  mathesar_ui/src/routes/RecordPageRoute.svelte
  mathesar_ui/src/stores/table-data/records.ts
  mathesar_ui/src/systems/table-view/row/RowCell.svelte
  mathesar_ui/src/utils/__tests__/recordSummary.test.ts
  mathesar_ui/src/utils/recordSummary.ts
  mathesar_ui/src/utils/recordSummaryTypes.ts
Labels: status: review

#1710 Selected and active cell sync & Table inspector should not scroll the table view
  mathesar_ui/src/components/cell-fabric/data-types/components/CellWrapper.svelte
  mathesar_ui/src/stores/table-data/selection.ts
  mathesar_ui/src/stores/table-data/tabularData.ts
  mathesar_ui/src/systems/table-view/Body.svelte
  mathesar_ui/src/systems/table-view/row/RowCell.svelte
  mathesar_ui/src/systems/table-view/table-inspector/TableInspector.svelte
Labels: status: review

#1721 Frontend - update all of our npm packages
  .github/workflows/run-lint-audit-tests-ui.yml
  mathesar/templates/mathesar/base.html
  mathesar/utils/frontend.py
  mathesar_ui/.eslintrc.cjs
  mathesar_ui/.storybook/main.js
  mathesar_ui/package-lock.json
  mathesar_ui/package.json
  mathesar_ui/src/api/queries.ts
  mathesar_ui/src/api/tables/records.ts
  mathesar_ui/src/component-library/__meta__/utils/SlotTest.svelte
  mathesar_ui/src/component-library/button/__meta__/Button.stories.svelte
  mathesar_ui/src/component-library/common/actions/actionsTypes.ts
  mathesar_ui/src/component-library/common/actions/clickOffBounds.ts
  mathesar_ui/src/component-library/common/actions/popper.ts
  mathesar_ui/src/component-library/common/actions/portal.ts
  mathesar_ui/src/component-library/common/utils/__tests__/filterUtils.test.ts
  mathesar_ui/src/component-library/common/utils/filterUtils.ts
  mathesar_ui/src/component-library/common/utils/storeUtils.ts
  mathesar_ui/src/component-library/common/utils/typeUtils.ts
  mathesar_ui/src/component-library/confirmation/__meta__/Confirmation.stories.svelte
  mathesar_ui/src/component-library/form-builder/__meta__/FormBuilder.mdx
  mathesar_ui/src/component-library/formatted-input/FormattedInputTypes.ts
  mathesar_ui/src/component-library/icon/__meta__/Icon.test.ts
  mathesar_ui/src/component-library/list-box/ListBoxOptions.svelte
  mathesar_ui/src/component-library/number-input/NumberInputTypes.ts
  mathesar_ui/src/component-library/pagination/Pagination.svelte
  mathesar_ui/src/component-library/string-or-component/StringOrComponent.svelte
  mathesar_ui/src/component-library/text-area/TextArea.svelte
  mathesar_ui/src/component-library/text-avatar/TextAvatar.svelte
  mathesar_ui/src/component-library/text-input/TextInputTypes.ts
  mathesar_ui/src/component-library/toast/ToastController.ts
  mathesar_ui/src/component-library/tree/Tree.svelte
  mathesar_ui/src/component-library/tree/TreeItem.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/__tests__/SteppedInputCell.test.ts
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LinkedRecordInput.svelte
  mathesar_ui/src/components/sheet/virtual-list/detectElementResize.ts
  mathesar_ui/src/pages/data-explorer/DataExplorerPage.svelte
  mathesar_ui/src/pages/schema/SchemaPage.svelte
  mathesar_ui/src/routes/DataExplorerRoute.svelte
  mathesar_ui/src/stores/table-data/meta.ts
  mathesar_ui/src/systems/data-explorer/QueryManager.ts
  mathesar_ui/src/systems/data-explorer/output-config-sidebar/TransformationsPane.svelte
  mathesar_ui/src/systems/table-view/row/Row.svelte
  mathesar_ui/src/utils/api.ts
  mathesar_ui/svelte.config.cjs
  mathesar_ui/vite.config.js
Labels: status: review

#1722 Display cell selection while dragging
  mathesar_ui/src/stores/table-data/selection.ts
Labels: status: review

#1726 Removed id suffix when linking two tables issue#1542
  mathesar_ui/src/systems/table-view/link-table/linkTableUtils.ts
Labels: status: review

#1731 Replace jest with vitest, remove unnecessary packages
  mathesar_ui/.eslintrc.cjs
  mathesar_ui/README.md
  mathesar_ui/jest.config.cjs
  mathesar_ui/package-lock.json
  mathesar_ui/package.json
  mathesar_ui/src/__tests__/App.test.ts
  mathesar_ui/src/component-library/button/__meta__/Button.test.ts
  mathesar_ui/src/component-library/common/utils/__tests__/CancellablePromise.test.ts
  mathesar_ui/src/component-library/icon/__meta__/Icon.test.ts
  mathesar_ui/src/component-library/input-group/__meta__/InputGroup.test.ts
  mathesar_ui/src/component-library/number-input/__tests__/NumberInput.test.ts
  mathesar_ui/src/component-library/select/__meta__/Select.test.ts
  mathesar_ui/src/component-library/text-input/__meta__/TextInput.test.ts
  mathesar_ui/src/components/cell-fabric/data-types/components/__tests__/SteppedInputCell.test.ts
  mathesar_ui/svelte.config.cjs
  mathesar_ui/tsconfig.json
  mathesar_ui/vite.config.js
Labels: status: review

#1733 Table Inspector: Support column selection when table has no rows
  mathesar_ui/src/stores/table-data/selection.ts
  mathesar_ui/src/systems/table-view/header/Header.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnMode.svelte
Labels: status: review

#1734 Reduce warnings count without changing logic
  db/columns/operations/select.py
  db/constraints/operations/select.py
  db/dependents/dependents_utils.py
  db/functions/operations/apply.py
  db/functions/operations/check_support.py
  db/schemas/operations/select.py
  db/tables/operations/move_columns.py
  db/tables/operations/select.py
  db/types/custom/char.py
  db/utils.py
Labels: status: waiting

#1736 Ignore the cartesian product warning for dependents query
  db/dependents/dependents_utils.py
Labels: status: review

#1725 RPC style returning GET endpoint
  mathesar/api/db/viewsets/queries.py
  mathesar/api/serializers/queries.py
  mathesar/migrations/0004_auto_20220927_0657.py
  mathesar/models/query.py
  mathesar/tests/api/query/test_query_results.py
Labels: status: review

#1638 Add filters to dependents' endpoints
  db/dependents/dependents_utils.py
  db/tests/dependents/test_dependents.py
  mathesar/api/db/viewsets/columns.py
  mathesar/api/db/viewsets/schemas.py
  mathesar/api/db/viewsets/tables.py
  mathesar/api/serializers/dependents.py
  mathesar/models/base.py
  mathesar/tests/api/test_dependents_api.py
Labels: status: review

#1723 Specify types for DBFunction call returns
  db/functions/base.py
  db/functions/packed.py
  db/records/operations/select.py
  db/tests/functions/test_func_imports.py
  db/tests/types/test_email.py
  db/tests/types/test_json.py
  db/tests/types/test_uri.py
  db/types/custom/datetime.py
  db/types/custom/email.py
  db/types/custom/json_array.py
  db/types/custom/json_object.py
  db/types/custom/uri.py
Labels: status: review

#1738 Improve UX for FK and PK cell interactions
  mathesar_ui/src/component-library/context-menu/__meta__/ContextMenu.stories.svelte
  mathesar_ui/src/component-library/dropdown-menu/__meta__/DropdownMenu.stories.svelte
  mathesar_ui/src/component-library/menu/ButtonMenuItem.svelte
  mathesar_ui/src/component-library/menu/CheckboxMenuItem.svelte
  mathesar_ui/src/component-library/menu/LinkMenuItem.svelte
  mathesar_ui/src/component-library/menu/Menu.scss
  mathesar_ui/src/component-library/menu/MenuItem.svelte
  mathesar_ui/src/component-library/menu/__meta__/Menu.stories.svelte
  mathesar_ui/src/component-library/menu/index.ts
  mathesar_ui/src/components/cell-fabric/CellFabric.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/CellWrapper.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/SteppedInputCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LaunchCue.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LinkedRecordCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LinkedRecordInput.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/number/NumberCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/primary-key/PrimaryKeyCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/typeDefinitions.ts
  mathesar_ui/src/components/cell-fabric/utils.ts
  mathesar_ui/src/components/sheet/Sheet.svelte
  mathesar_ui/src/geometry.ts
  mathesar_ui/src/pages/import-preview/ImportPreviewPage.svelte
  mathesar_ui/src/stores/abstract-types/type-configs/boolean.ts
  mathesar_ui/src/stores/abstract-types/type-configs/date.ts
  mathesar_ui/src/stores/abstract-types/type-configs/datetime.ts
  mathesar_ui/src/stores/abstract-types/type-configs/duration.ts
  mathesar_ui/src/stores/abstract-types/type-configs/email.ts
  mathesar_ui/src/stores/abstract-types/type-configs/fallback.ts
  mathesar_ui/src/stores/abstract-types/type-configs/jsonArray.ts
  mathesar_ui/src/stores/abstract-types/type-configs/jsonObject.ts
  mathesar_ui/src/stores/abstract-types/type-configs/money.ts
  mathesar_ui/src/stores/abstract-types/type-configs/number.ts
  mathesar_ui/src/stores/abstract-types/type-configs/text.ts
  mathesar_ui/src/stores/abstract-types/type-configs/time.ts
  mathesar_ui/src/stores/abstract-types/type-configs/uri.ts
  mathesar_ui/src/stores/abstract-types/types.ts
  mathesar_ui/src/stores/table-data/TableStructure.ts
  mathesar_ui/src/stores/table-data/processedColumns.ts
  mathesar_ui/src/stores/table-data/tabularData.ts
  mathesar_ui/src/systems/data-explorer/output-config-sidebar/TransformationsPane.svelte
  mathesar_ui/src/systems/data-explorer/result-pane/Results.svelte
  mathesar_ui/src/systems/data-explorer/utils.ts
  mathesar_ui/src/systems/record-selector/RecordSelectorResults.svelte
  mathesar_ui/src/systems/table-view/Body.svelte
  mathesar_ui/src/systems/table-view/TableView.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/Group.svelte
  mathesar_ui/src/systems/table-view/constraints/TableConstraints.svelte
  mathesar_ui/src/systems/table-view/row/RowCell.svelte
Labels: status: review

#1744 Data explorer bug fixes - PR 1
  mathesar_ui/src/api/queries.ts
  mathesar_ui/src/pages/exploration/ActionsPane.svelte
  mathesar_ui/src/stores/queries.ts
  mathesar_ui/src/systems/data-explorer/QueryManager.ts
  mathesar_ui/src/systems/data-explorer/QueryModel.ts
  mathesar_ui/src/systems/data-explorer/QueryRunner.ts
  mathesar_ui/src/systems/data-explorer/output-config-sidebar/FilterTransformation.svelte
  mathesar_ui/src/systems/data-explorer/output-config-sidebar/OutputConfigSidebar.svelte
  mathesar_ui/src/systems/data-explorer/output-config-sidebar/TransformationsPane.svelte
  mathesar_ui/src/systems/data-explorer/output-config-sidebar/transformationUtils.ts
  mathesar_ui/src/systems/data-explorer/result-pane/Results.svelte
  mathesar_ui/src/systems/data-explorer/utils.ts
Labels: status: review
