Repository mathesar-foundation/mathesar, pull requests merged in 2022-02, with the labels that each got.

#976 Implement renaming a column
  mathesar_ui/.eslintrc.cjs
  mathesar_ui/src/component-library/common/utils/EventHandler.ts
  mathesar_ui/src/sections/table-view/header/header-cell/DefaultOptions.svelte
  mathesar_ui/src/sections/table-view/header/header-cell/HeaderCell.svelte
  mathesar_ui/src/stores/table-data/columns.ts
  mathesar_ui/src/stores/table-data/records.ts
  mathesar_ui/src/stores/table-data/tabularData.ts
  mathesar_ui/src/stores/tabs/tabList.ts
  mathesar_ui/src/utils/domUtils.ts
Labels: status: review

#1005 UI for adding multi-column unique constraints
  mathesar_ui/.eslintrc.cjs
  mathesar_ui/src/component-library/cancel-or-proceed-button-pair/CancelOrProceedButtonPair.d.ts
  mathesar_ui/src/component-library/cancel-or-proceed-button-pair/CancelOrProceedButtonPair.svelte
  mathesar_ui/src/component-library/checkbox-group/CheckboxGroup.svelte
  mathesar_ui/src/component-library/common/utils/ImmutableSet.ts
  mathesar_ui/src/component-library/common/utils/__tests__/ImmutableSet.test.ts
  mathesar_ui/src/component-library/confirmation/Confirmation.svelte
  mathesar_ui/src/component-library/confirmation/ConfirmationController.ts
  mathesar_ui/src/component-library/confirmation/__meta__/Confirmation.stories.svelte
  mathesar_ui/src/component-library/fieldset-group/FieldsetGroup.svelte
  mathesar_ui/src/component-library/index.ts
  mathesar_ui/src/component-library/modal/ActiveModalStore.ts
  mathesar_ui/src/component-library/modal/ControlledModal.svelte
  mathesar_ui/src/component-library/modal/IndependentModal.scss
  mathesar_ui/src/component-library/modal/IndependentModal.svelte
  mathesar_ui/src/component-library/modal/ModalController.ts
  mathesar_ui/src/component-library/modal/ModalMultiplexer.ts
  mathesar_ui/src/component-library/modal/ModalStack.ts
  mathesar_ui/src/component-library/modal/ModalVisibilityStore.ts
  mathesar_ui/src/component-library/modal/__meta__/Modal.stories.svelte
  mathesar_ui/src/component-library/modal/index.ts
  mathesar_ui/src/component-library/radio-group/RadioGroup.svelte
  mathesar_ui/src/component-library/seesaw/Seesaw.scss
  mathesar_ui/src/component-library/seesaw/Seesaw.svelte
  mathesar_ui/src/component-library/styles.scss
  mathesar_ui/src/component-library/text-input/TextInput.svelte
  mathesar_ui/src/component-library/types.d.ts
  mathesar_ui/src/components/ColumnName.svelte
  mathesar_ui/src/components/Form.svelte
  mathesar_ui/src/components/FormField.svelte
  mathesar_ui/src/components/ModalTextInputForm.svelte
  mathesar_ui/src/pages/schemas/AddEditSchema.svelte
  mathesar_ui/src/pages/schemas/Schemas.svelte
  mathesar_ui/src/sections/table-view/actions-pane/ActionsPane.svelte
  mathesar_ui/src/sections/table-view/actions-pane/RenameTableModal.svelte
  mathesar_ui/src/sections/table-view/constraints/NewUniqueConstraintModal.svelte
  mathesar_ui/src/sections/table-view/constraints/TableConstraint.scss
  mathesar_ui/src/sections/table-view/constraints/TableConstraint.svelte
  mathesar_ui/src/sections/table-view/constraints/TableConstraints.scss
  mathesar_ui/src/sections/table-view/constraints/TableConstraints.svelte
  mathesar_ui/src/stores/confirmation.ts
Labels: status: review

#1024 In-app help content
  mathesar_ui/src/component-library/checkbox-group/CheckboxGroup.svelte
  mathesar_ui/src/component-library/dropdown/Dropdown.svelte
  mathesar_ui/src/component-library/help/Help.scss
  mathesar_ui/src/component-library/help/Help.svelte
  mathesar_ui/src/component-library/help/__meta__/Help.stories.svelte
  mathesar_ui/src/component-library/index.ts
  mathesar_ui/src/component-library/radio-group/RadioGroup.svelte
  mathesar_ui/src/component-library/styles.scss
  mathesar_ui/src/components/Null.svelte
  mathesar_ui/src/pages/schemas/Schemas.svelte
  mathesar_ui/src/pages/schemas/__help__/SchemasHelp.svelte
  mathesar_ui/src/sections/table-view/constraints/NewUniqueConstraintModal.svelte
  mathesar_ui/src/sections/table-view/constraints/TableConstraints.svelte
  mathesar_ui/src/sections/table-view/constraints/__help__/ConstraintHelp.svelte
  mathesar_ui/src/sections/table-view/constraints/__help__/ConstraintNameHelp.svelte
  mathesar_ui/src/sections/table-view/constraints/__help__/UniqueConstraintColumnsHelp.svelte
  mathesar_ui/src/sections/table-view/constraints/__help__/UniqueConstraintsHelp.svelte
Labels: status: review

#963 Keyboard Accessibility Pagination Component
  mathesar_ui/src/component-library/icon/Icon.svelte
  mathesar_ui/src/component-library/pagination/Pagination.scss
  mathesar_ui/src/component-library/pagination/Pagination.svelte
Labels: status: review

#1016 Handle error consistently on the backend using custom drf error handler
  config/settings.py
  mathesar/api/exceptions/data_import_exceptions/exceptions.py
  mathesar/api/exceptions/error_codes.py
  mathesar/api/exceptions/exception_converters.py
  mathesar/api/exceptions/exception_mappers.py
  mathesar/api/serializers/data_files.py
  mathesar/errors.py
  mathesar/exception_handlers.py
  mathesar/tests/api/test_column_api.py
  mathesar/tests/api/test_constraint_api.py
  mathesar/tests/api/test_data_file_api.py
  mathesar/tests/api/test_record_api.py
  mathesar/tests/api/test_schema_api.py
  mathesar/tests/api/test_table_api.py
  mathesar/utils/datafiles.py
  mathesar/utils/models.py
Labels: status: waiting

#926 Type configuration for Text, Number, Boolean, and all mathesar types with single associated db type
  mathesar_ui/.eslintrc.cjs
  mathesar_ui/src/component-library/checkbox-group/CheckboxGroup.svelte
  mathesar_ui/src/component-library/common/utils/ImmutableSet.ts
  mathesar_ui/src/component-library/common/utils/__tests__/ImmutableSet.test.ts
  mathesar_ui/src/component-library/common/utils/__tests__/ruleExecutor.test.ts
  mathesar_ui/src/component-library/common/utils/filterUtils.ts
  mathesar_ui/src/component-library/common/utils/formatUtils.ts
  mathesar_ui/src/component-library/common/utils/index.ts
  mathesar_ui/src/component-library/common/utils/ruleExecuter.ts
  mathesar_ui/src/component-library/form-builder/FormBuilder.scss
  mathesar_ui/src/component-library/form-builder/FormBuilder.svelte
  mathesar_ui/src/component-library/form-builder/FormElement.svelte
  mathesar_ui/src/component-library/form-builder/__meta__/FormBuilder.mdx
  mathesar_ui/src/component-library/form-builder/__meta__/FormBuilder.stories.svelte
  mathesar_ui/src/component-library/form-builder/__meta__/FormBuilderStory.svelte
  mathesar_ui/src/component-library/form-builder/formFactory.ts
  mathesar_ui/src/component-library/form-builder/index.ts
  mathesar_ui/src/component-library/form-builder/types.d.ts
  mathesar_ui/src/component-library/index.ts
  mathesar_ui/src/component-library/modal/ModalStack.ts
  mathesar_ui/src/component-library/number-input/NumberInput.svelte
  mathesar_ui/src/component-library/number-input/types.d.ts
  mathesar_ui/src/component-library/styles.scss
  mathesar_ui/src/component-library/types.d.ts
  mathesar_ui/src/components/ColumnName.svelte
  mathesar_ui/src/sections/table-view/header/header-cell/HeaderCell.svelte
  mathesar_ui/src/sections/table-view/header/header-cell/type-options/TypeOptions.scss
  mathesar_ui/src/sections/table-view/header/header-cell/type-options/TypeOptions.svelte
  mathesar_ui/src/sections/table-view/header/header-cell/type-options/database-options/DatabaseOptions.svelte
  mathesar_ui/src/sections/table-view/header/header-cell/type-options/database-options/DbForm.svelte
  mathesar_ui/src/sections/table-view/header/header-cell/type-options/database-options/DbTypeIndicator.svelte
  mathesar_ui/src/sections/table-view/header/header-cell/type-options/database-options/DbTypeSelect.svelte
  mathesar_ui/src/stores/abstract-types/abstractTypeCategories.ts
  mathesar_ui/src/stores/abstract-types/constants.ts
  mathesar_ui/src/stores/abstract-types/index.ts
  mathesar_ui/src/stores/abstract-types/store.ts
  mathesar_ui/src/stores/abstract-types/type-configs/boolean.ts
  mathesar_ui/src/stores/abstract-types/type-configs/number.ts
  mathesar_ui/src/stores/abstract-types/type-configs/text.ts
  mathesar_ui/src/stores/abstract-types/type-configs/unknown.ts
  mathesar_ui/src/stores/abstract-types/types.d.ts
  mathesar_ui/src/stores/table-data/columns.ts
Labels: status: review

#1048 Fix spelling error in function name
  mathesar_ui/src/component-library/common/utils/ruleExecuter.ts
Labels: status: review

#1022 Introduce function API
  db/functions/__init__.py
  db/functions/base.py
  db/functions/exceptions.py
  db/functions/hints.py
  db/functions/known_db_functions.py
  db/functions/operations/apply.py
  db/functions/operations/check_support.py
  db/functions/operations/deserialize.py
  db/tests/functions/__init__.py
  db/tests/functions/conftest.py
  db/tests/functions/operations/__init__.py
  db/tests/functions/operations/test_filter.py
  db/types/base.py
  db/types/uri.py
  mathesar/api/serializers/db_types.py
  mathesar/api/serializers/functions.py
  mathesar/api/viewsets/databases.py
  mathesar/tests/api/test_db_type_api.py
  mathesar/tests/api/test_function_api.py
  requirements.txt
Labels: affects: architecture, status: review

#1041 Introduce ui and db API namespaces
  mathesar/api/db/__init__.py
  mathesar/api/db/viewsets/__init__.py
  mathesar/api/db/viewsets/columns.py
  mathesar/api/db/viewsets/constraints.py
  mathesar/api/db/viewsets/data_files.py
  mathesar/api/db/viewsets/databases.py
  mathesar/api/db/viewsets/records.py
  mathesar/api/db/viewsets/schemas.py
  mathesar/api/db/viewsets/tables.py
  mathesar/api/dj_filters.py
  mathesar/api/serializers/databases.py
  mathesar/api/ui/__init__.py
  mathesar/api/ui/viewsets/__init__.py
  mathesar/api/ui/viewsets/databases.py
  mathesar/api/viewsets/__init__.py
  mathesar/tests/api/test_column_api.py
  mathesar/tests/api/test_constraint_api.py
  mathesar/tests/api/test_data_file_api.py
  mathesar/tests/api/test_database_api.py
  mathesar/tests/api/test_db_type_api.py
  mathesar/tests/api/test_function_api.py
  mathesar/tests/api/test_mathesar_types_api.py
  mathesar/tests/api/test_record_api.py
  mathesar/tests/api/test_schema_api.py
  mathesar/tests/api/test_table_api.py
  mathesar/tests/test_multi_db.py
  mathesar/urls.py
  mathesar_ui/src/stores/abstract-types/store.ts
  mathesar_ui/src/utils/api.ts
Labels: affects: architecture, work: backend, work: frontend, status: review

#1053 Fix `Not Null Violation` to return detailed error response
  mathesar/api/db/viewsets/records.py
  mathesar/api/exceptions/database_exceptions/exceptions.py
  mathesar/tests/api/test_record_api.py
Labels: status: review

#1075 Fix form render regression
  mathesar_ui/src/component-library/form-builder/FormElement.svelte
Labels: status: review

#1067 Interval type improvements
  db/columns/base.py
  db/columns/operations/select.py
  db/tests/columns/operations/test_create.py
  db/tests/columns/test_base.py
  db/tests/types/operations/test_cast.py
  db/tests/types/test_interval.py
  db/types/__init__.py
  db/types/exceptions.py
  db/types/interval.py
  db/types/operations/cast.py
  mathesar/api/db/viewsets/columns.py
  mathesar/api/serializers/columns.py
  mathesar/tests/api/test_column_api.py
  mathesar/tests/api/test_constraint_api.py
Labels: status: waiting

#1032 Improve E2E test setup
  .github/workflows/run-e2e-integ-tests.yml
  .github/workflows/run-pytest.yml
  .gitignore
  Dockerfile.integ-tests
  README.md
  docker-compose.yml
  integration_tests/test_base_page.py
  mathesar/tests/integration/README.md
  mathesar/tests/integration/__init__.py
  mathesar/tests/integration/conftest.py
  mathesar/tests/integration/test_base_page.py
  mathesar/tests/integration/test_imports.py
  mathesar_ui/README.md
  mathesar_ui/src/header/Header.svelte
  mathesar_ui/src/sections/left-pane/LeftPane.svelte
  requirements-dev.txt
Labels: status: review

#1069 Replace filtering API; includes support for filtering numbers
  db/functions/base.py
  db/functions/exceptions.py
  db/functions/known_db_functions.py
  db/functions/operations/apply.py
  db/functions/operations/deserialize.py
  db/records/operations/select.py
  db/tests/functions/operations/test_deserialize.py
  db/tests/functions/operations/test_filter.py
  db/tests/records/operations/test_filter.py
  db/tests/records/operations/test_select.py
  mathesar/api/db/viewsets/columns.py
  mathesar/api/db/viewsets/records.py
  mathesar/api/pagination.py
  mathesar/api/serializers/records.py
  mathesar/functions/__init__.py
  mathesar/functions/operations/__init__.py
  mathesar/functions/operations/convert.py
  mathesar/models.py
  mathesar/tests/api/test_column_api.py
  mathesar/tests/api/test_record_api.py
Labels: affects: architecture, work: backend, status: waiting

#1088 Datetimes to RFC 3339
  db/tests/columns/test_base.py
  db/tests/columns/utils.py
  db/tests/conftest.py
  db/tests/functions/operations/test_filter.py
  db/tests/tables/operations/test_infer_types.py
  db/tests/types/operations/test_cast.py
  db/tests/types/test_datetime.py
  db/tests/types/test_interval.py
  db/types/__init__.py
  db/types/datetime.py
  db/types/interval.py
  mathesar/tests/api/test_column_api.py
  mathesar/tests/api/test_record_api.py
Labels: status: review

#1062 Finish adding E2E tests
  mathesar/tests/api/conftest.py
  mathesar/tests/conftest.py
  mathesar/tests/integration/conftest.py
  mathesar/tests/integration/test_columns.py
  mathesar/tests/integration/test_constraints.py
  mathesar/tests/integration/test_imports.py
  mathesar/tests/integration/test_records.py
  mathesar/tests/integration/test_schemas.py
  mathesar/tests/integration/test_tables.py
  mathesar/tests/integration/test_ui.py
  mathesar/tests/integration/utils/locators.py
  mathesar_ui/src/pages/schemas/schema-row/SchemaRow.svelte
  mathesar_ui/src/sections/table-view/constraints/TableConstraints.svelte
  mathesar_ui/src/sections/table-view/header/new-column-cell/NewColumnCell.svelte
  pyproject.toml
Labels: status: review

#1091 Implement display options for Duration type
  mathesar/api/display_options.py
  mathesar/api/serializers/shared_serializers.py
  mathesar/tests/api/test_column_api.py
Labels: status: review

#1079 Add URI and text filters
  db/functions/base.py
  db/functions/known_db_functions.py
  db/functions/operations/apply.py
  db/functions/operations/check_support.py
  db/functions/redundant.py
  db/tests/conftest.py
  db/tests/functions/operations/test_filter.py
  db/tests/records/conftest.py
  db/tests/resources/uris_create.sql
  db/tests/types/fixtures.py
  db/tests/types/test_uri.py
  db/types/base.py
  db/types/uri.py
  mathesar/database/types.py
  mathesar/models.py
  mathesar/tests/api/conftest.py
  mathesar/tests/conftest.py
  mathesar/tests/filters/test_filters.py
Labels: affects: architecture, work: backend, status: review

#1087 Add email filters
  db/functions/hints.py
  db/functions/known_db_functions.py
  db/functions/operations/check_support.py
  db/tests/conftest.py
  db/tests/types/fixtures.py
  db/tests/types/test_email.py
  db/types/base.py
  db/types/email.py
  db/types/uri.py
  mathesar/tests/filters/test_filters.py
Labels: affects: architecture, work: backend, status: review
