Repository mathesar-foundation/mathesar, pull requests merged in 2022-03, with the labels that each got.

#1080 Text type & basic Boolean type frontend implementation
  mathesar/tests/integration/test_records.py
  mathesar_ui/src/component-library/checkbox/Checkbox.svelte
  mathesar_ui/src/component-library/common/base-components/BaseInput.svelte
  mathesar_ui/src/component-library/dynamic-input/DynamicInput.svelte
  mathesar_ui/src/component-library/form-builder/FormBuilder.svelte
  mathesar_ui/src/component-library/form-builder/FormElement.svelte
  mathesar_ui/src/component-library/form-builder/formFactory.ts
  mathesar_ui/src/component-library/form-builder/types.d.ts
  mathesar_ui/src/component-library/index.ts
  mathesar_ui/src/component-library/text-area/TextArea.svelte
  mathesar_ui/src/component-library/text-input/TextInput.svelte
  mathesar_ui/src/components/ColumnName.svelte
  mathesar_ui/src/components/ModalTextInputForm.svelte
  mathesar_ui/src/components/cell/Cell.svelte
  mathesar_ui/src/components/cell/cell-types/CheckboxCell.svelte
  mathesar_ui/src/components/cell/cell-types/TextAreaCell.svelte
  mathesar_ui/src/components/cell/cell-types/TextBoxCell.svelte
  mathesar_ui/src/components/cell/cell-types/common/SteppedInputCell.svelte
  mathesar_ui/src/components/cell/utils.ts
  mathesar_ui/src/sections/table-view/Body.svelte
  mathesar_ui/src/sections/table-view/TableView.scss
  mathesar_ui/src/sections/table-view/header/header-cell/HeaderCell.svelte
  mathesar_ui/src/sections/table-view/header/header-cell/type-options/TypeOptions.svelte
  mathesar_ui/src/sections/table-view/header/header-cell/type-options/database-options/DatabaseOptions.svelte
  mathesar_ui/src/sections/table-view/header/header-cell/type-options/database-options/DbForm.svelte
  mathesar_ui/src/sections/table-view/header/header-cell/type-options/utils.ts
  mathesar_ui/src/sections/table-view/row/Row.scss
  mathesar_ui/src/sections/table-view/row/RowCell.svelte
  mathesar_ui/src/stores/abstract-types/abstractTypeCategories.ts
  mathesar_ui/src/stores/abstract-types/index.ts
  mathesar_ui/src/stores/abstract-types/store.ts
  mathesar_ui/src/stores/abstract-types/type-configs/number.ts
  mathesar_ui/src/stores/abstract-types/type-configs/text.ts
  mathesar_ui/src/stores/abstract-types/types.d.ts
  mathesar_ui/src/stores/table-data/columns.ts
  mathesar_ui/src/stores/table-data/display.ts
  mathesar_ui/src/stores/table-data/index.ts
Labels: status: review

#1090 Add filters for money and boolean
  db/functions/known_db_functions.py
  db/functions/operations/apply.py
  db/functions/packed.py
  db/tests/conftest.py
  db/tests/functions/operations/test_filter.py
  db/tests/resources/booleans_create.sql
  db/types/base.py
  db/types/email.py
  db/types/uri.py
Labels: affects: architecture, work: backend, status: waiting

#1098 Hint system improvements
  db/functions/hints.py
  mathesar/filters/base.py
Labels: affects: architecture, work: backend, status: review

#1106 Fix Column dropping operations to use attnum instead of column index
  db/columns/operations/drop.py
  db/tests/columns/operations/test_drop.py
  mathesar/api/db/viewsets/columns.py
  mathesar/models.py
Labels: status: waiting

#1101 Introduce some filter aliases for time types
  db/functions/base.py
  db/functions/hints.py
  db/functions/packed.py
  db/types/base.py
  mathesar/api/serializers/filters.py
  mathesar/filters/base.py
Labels: affects: architecture, work: backend, status: review

#1133 Add code comments linking to discussions
  mathesar_ui/src/App.svelte
  mathesar_ui/src/component-library/pagination/Pagination.svelte
  mathesar_ui/src/utils/routing.ts
Labels: status: review

#1141 UI changes for column ids in records API
  mathesar_ui/src/api/tables/records.ts
  mathesar_ui/src/sections/table-view/display-options/DisplayGroup.svelte
  mathesar_ui/src/sections/table-view/display-options/DisplaySort.svelte
  mathesar_ui/src/sections/table-view/header/Header.svelte
  mathesar_ui/src/sections/table-view/header/header-cell/DefaultOptions.svelte
  mathesar_ui/src/sections/table-view/row/GroupHeader.svelte
  mathesar_ui/src/sections/table-view/row/Row.svelte
  mathesar_ui/src/sections/table-view/row/RowControl.svelte
  mathesar_ui/src/stores/table-data/columns.ts
  mathesar_ui/src/stores/table-data/display.ts
  mathesar_ui/src/stores/table-data/filtering.ts
  mathesar_ui/src/stores/table-data/grouping.ts
  mathesar_ui/src/stores/table-data/index.ts
  mathesar_ui/src/stores/table-data/records.ts
  mathesar_ui/src/stores/table-data/sorting.ts
  mathesar_ui/src/stores/table-data/utils.ts
  mathesar_ui/src/stores/tabs/__tests__/tabDataSaver.test.ts
Labels: status: review

#1132 Replace column index usage in db column alter operations with column attnum.
  db/columns/operations/alter.py
  db/columns/operations/infer_types.py
  db/tests/columns/operations/test_alter.py
  db/tests/types/fixtures.py
  db/tests/types/operations/test_cast.py
  mathesar/api/db/viewsets/columns.py
  mathesar/models.py
  mathesar/tests/api/test_column_api.py
  mathesar/tests/api/test_table_api.py
Labels: status: review

#1093 Split datetime into three UI types
  db/functions/hints.py
  db/types/base.py
  mathesar/api/display_options.py
  mathesar/api/serializers/shared_serializers.py
  mathesar/database/types.py
  mathesar/tests/api/test_column_api.py
  requirements.txt
Labels: affects: architecture, work: backend, status: waiting

#1047 Mathesar 896 Change records api parameters to use column id instead of name
  mathesar/api/db/viewsets/columns.py
  mathesar/api/db/viewsets/records.py
  mathesar/api/pagination.py
  mathesar/api/serializers/records.py
  mathesar/models.py
  mathesar/tests/api/conftest.py
  mathesar/tests/api/test_record_api.py
  mathesar/tests/api/test_table_api.py
  mathesar_ui/src/api/tables/records.ts
  mathesar_ui/src/sections/table-view/display-options/DisplayGroup.svelte
  mathesar_ui/src/sections/table-view/display-options/DisplaySort.svelte
  mathesar_ui/src/sections/table-view/header/Header.svelte
  mathesar_ui/src/sections/table-view/header/header-cell/DefaultOptions.svelte
  mathesar_ui/src/sections/table-view/row/GroupHeader.svelte
  mathesar_ui/src/sections/table-view/row/Row.svelte
  mathesar_ui/src/sections/table-view/row/RowControl.svelte
  mathesar_ui/src/stores/table-data/columns.ts
  mathesar_ui/src/stores/table-data/display.ts
  mathesar_ui/src/stores/table-data/filtering.ts
  mathesar_ui/src/stores/table-data/grouping.ts
  mathesar_ui/src/stores/table-data/index.ts
  mathesar_ui/src/stores/table-data/records.ts
  mathesar_ui/src/stores/table-data/sorting.ts
  mathesar_ui/src/stores/table-data/utils.ts
  mathesar_ui/src/stores/tabs/__tests__/tabDataSaver.test.ts
  requirements.txt
Labels: status: waiting

#1137 Add non-composite custom money
  db/columns/operations/infer_types.py
  db/tests/columns/operations/test_create.py
  db/tests/tables/operations/test_infer_types.py
  db/tests/types/operations/test_cast.py
  db/tests/types/test_money.py
  db/tests/types/test_multicurrency.py
  db/types/__init__.py
  db/types/base.py
  db/types/install.py
  db/types/money.py
  db/types/multicurrency.py
  db/types/operations/cast.py
  mathesar/database/types.py
  mathesar/tests/api/test_column_api.py
  mathesar/tests/api/test_ui_types_api.py
Labels: status: review

#1152 Hide the tab close button on hover-capable devices. Fix #1074
  mathesar_ui/src/component-library/tabs/TabContainer.scss
Labels: status: review

#1157 Fix URI check constraint to allow null values
  db/tests/types/test_uri.py
  db/types/uri.py
Labels: status: review

#1103 Test Cases to Ensure that we can set, get, and delete default values for all types
  db/tests/columns/operations/test_alter.py
  db/tests/columns/operations/test_select.py
  db/tests/columns/utils.py
Labels: status: review

#1160 Add E2E test for trying to to rename a table to the name of another table
  mathesar/tests/integration/test_tables.py
Labels: status: review

#1164 Added integration tests for changing column type from text to number
  mathesar/tests/integration/test_columns.py
Labels: status: review

#1171 Remove dbPrefixUrl function & prefix every instance of API call with dbPrefix
  mathesar_ui/src/sections/import-data/importUtils.ts
  mathesar_ui/src/sections/import-data/preview/PreviewRows.svelte
  mathesar_ui/src/stores/databases.ts
  mathesar_ui/src/stores/schemas.ts
  mathesar_ui/src/stores/table-data/columns.ts
  mathesar_ui/src/stores/table-data/constraints.ts
  mathesar_ui/src/stores/table-data/records.ts
  mathesar_ui/src/stores/tables.ts
  mathesar_ui/src/utils/api.ts
Labels: status: review

#1144 Text type updates
  mathesar/tests/integration/conftest.py
  mathesar/tests/integration/test_text_type.py
  mathesar_ui/src/component-library/common/styles/components/input.scss
  mathesar_ui/src/component-library/common/utils/contextValidationUtil.ts
  mathesar_ui/src/component-library/common/utils/index.ts
  mathesar_ui/src/component-library/form-builder/FormBuilder.scss
  mathesar_ui/src/component-library/form-builder/FormBuilder.svelte
  mathesar_ui/src/component-library/form-builder/FormElement.svelte
  mathesar_ui/src/component-library/form-builder/FormInput.svelte
  mathesar_ui/src/component-library/form-builder/FormLayout.svelte
  mathesar_ui/src/component-library/form-builder/If.svelte
  mathesar_ui/src/component-library/form-builder/Switch.svelte
  mathesar_ui/src/component-library/form-builder/formFactory.ts
  mathesar_ui/src/component-library/form-builder/types.ts
  mathesar_ui/src/component-library/form-builder/utils.ts
  mathesar_ui/src/component-library/number-input/NumberInput.svelte
  mathesar_ui/src/component-library/number-input/types.d.ts
  mathesar_ui/src/component-library/text-input/TextInput.svelte
  mathesar_ui/src/component-library/types.d.ts
  mathesar_ui/src/components/cell/utils.ts
  mathesar_ui/src/sections/table-view/constraints/NewUniqueConstraintModal.svelte
  mathesar_ui/src/sections/table-view/header/header-cell/HeaderCell.svelte
  mathesar_ui/src/sections/table-view/header/header-cell/type-options/TypeOptions.svelte
  mathesar_ui/src/sections/table-view/header/header-cell/type-options/database-options/DatabaseOptions.svelte
  mathesar_ui/src/sections/table-view/header/header-cell/type-options/database-options/DbForm.svelte
  mathesar_ui/src/sections/table-view/header/header-cell/type-options/utils.ts
  mathesar_ui/src/sections/table-view/header/new-column-cell/NewColumnCell.svelte
  mathesar_ui/src/stores/abstract-types/abstractTypeCategories.ts
  mathesar_ui/src/stores/abstract-types/store.ts
  mathesar_ui/src/stores/abstract-types/type-configs/boolean.ts
  mathesar_ui/src/stores/abstract-types/type-configs/number.ts
  mathesar_ui/src/stores/abstract-types/type-configs/text.ts
  mathesar_ui/src/stores/abstract-types/type-configs/unknown.ts
  mathesar_ui/src/stores/abstract-types/types.ts
  mathesar_ui/src/stores/table-data/columns.ts
  pyproject.toml
Labels: status: review

#1176 Uppercase db types in db types endpoint
  mathesar/api/serializers/db_types.py
Labels: status: waiting

#1178 E2E Test issue #1130 For moving the selected cell with arrow keys
  mathesar/tests/integration/test_records.py
Labels: status: review

#1180 E2E test for renaming a table
  mathesar/tests/integration/test_tables.py
  mathesar/tests/integration/utils/table_actions.py
  mathesar/tests/integration/utils/validators.py
Labels: status: review

#1166 Text overflow schema selector is represented by ellipsis. Fixes#984
  mathesar_ui/src/header/schema-selector/SchemaSelector.scss
  mathesar_ui/src/header/schema-selector/SchemaSelector.svelte
Labels: status: review

#1188 Avoid inferring type varchar
  db/columns/operations/infer_types.py
  db/tables/operations/create.py
  mathesar/tests/api/test_table_api.py
Labels: status: review

#1200 Modify .eslintrc.cjs for explicit-member-accessibility
  mathesar_ui/.eslintrc.cjs
  mathesar_ui/src/component-library/common/utils/contextValidationUtil.ts
Labels: status: review

#1212 Focus state being reset Fixes #1040
  mathesar_ui/src/component-library/pagination/Pagination.svelte
Labels: status: done

#1216 "undefined" column type for the column "id" in the preview
  mathesar_ui/src/sections/import-data/preview/PreviewColumn.svelte
  mathesar_ui/src/stores/fileImports.ts
Labels: status: review

#1217 Fix schema fixture causing an Integrity error
  mathesar/tests/imports/test_csv.py
Labels: status: review

#1203 Add flake8 no type
  .github/workflows/run-flake8.yml
  db/functions/operations/deserialize.py
  db/types/base.py
  mathesar/errors.py
  mathesar/models.py
  mathesar/tests/conftest.py
  mathesar/tests/integration/utils/locators.py
  requirements-dev.txt
Labels: status: review

#1194 Generate column names
  db/columns/operations/create.py
  db/tests/columns/operations/test_create.py
  mathesar/api/serializers/columns.py
  mathesar/tests/api/test_column_api.py
Labels: status: review

#1213 Add ContextMenu component
  mathesar_ui/src/component-library/common/actions/clickOffBounds.ts
  mathesar_ui/src/component-library/common/actions/popper.ts
  mathesar_ui/src/component-library/context-menu/ContextMenu.svelte
  mathesar_ui/src/component-library/context-menu/__meta__/ContextMenu.stories.svelte
  mathesar_ui/src/component-library/index.ts
Labels: status: review

#1215 Add context menu to set cell to null
  mathesar_ui/src/sections/table-view/row/RowCell.svelte
Labels: status: waiting

#1191 Switching a schema from the Manage Schema
  mathesar_ui/src/header/schema-selector/SchemaSelector.scss
  mathesar_ui/src/pages/schemas/schema-row/SchemaRow.scss
  mathesar_ui/src/pages/schemas/schema-row/SchemaRow.svelte
Labels: status: review

#1201 [1177] - Strip column names before adding in DB
  mathesar/imports/csv.py
  mathesar/tests/conftest.py
  mathesar/tests/data/col_names_with_spaces.csv
  mathesar/tests/imports/test_csv.py
Labels: status: waiting

#1226 Remove column index from MathesarColumn and clean up leftover column index functions
  db/columns/base.py
  db/columns/operations/select.py
  db/constraints/operations/select.py
  db/tests/columns/operations/test_alter.py
  db/tests/columns/operations/test_select.py
  db/tests/columns/test_base.py
  mathesar/api/serializers/columns.py
  mathesar/reflection.py
  mathesar/tests/api/test_column_api.py
Labels: status: review

#1210 Fixes #1197 - raised the playwright page default from 5sec to 10 sec
  mathesar/tests/integration/conftest.py
Labels: status: review

#1199 Added fixture for `custom_types_schema` for the e2e test integrations to work properly
  mathesar/tests/conftest.py
Labels: status: review

#1229 Refactor TableRecord interface to Row
  mathesar_ui/src/api/tables/records.ts
  mathesar_ui/src/components/cell/utils.ts
  mathesar_ui/src/sections/table-view/Body.svelte
  mathesar_ui/src/sections/table-view/header/new-column-cell/NewColumnCell.svelte
  mathesar_ui/src/sections/table-view/row/GroupHeader.svelte
  mathesar_ui/src/sections/table-view/row/Row.svelte
  mathesar_ui/src/sections/table-view/row/RowCell.svelte
  mathesar_ui/src/sections/table-view/row/RowControl.svelte
  mathesar_ui/src/stores/abstract-types/type-configs/text.ts
  mathesar_ui/src/stores/abstract-types/types.ts
  mathesar_ui/src/stores/table-data/display.ts
  mathesar_ui/src/stores/table-data/records.ts
  mathesar_ui/src/stores/table-data/types.ts
  mathesar_ui/src/stores/table-data/utils.ts
Labels: status: review

#1236 Fix regressions from #1229:
  mathesar_ui/src/stores/table-data/records.ts
Labels: status: review

#1240 Merge Select and SimpleSelect
  mathesar_ui/src/component-library/common/utils/formatUtils.ts
  mathesar_ui/src/component-library/common/utils/typeUtils.ts
  mathesar_ui/src/component-library/dynamic-input/BooleanInput.svelte
  mathesar_ui/src/component-library/dynamic-input/DynamicInput.svelte
  mathesar_ui/src/component-library/dynamic-input/EnumInput.svelte
  mathesar_ui/src/component-library/dynamic-input/StringInput.svelte
  mathesar_ui/src/component-library/dynamic-input/types.ts
  mathesar_ui/src/component-library/form-builder/FormInput.svelte
  mathesar_ui/src/component-library/form-builder/types.ts
  mathesar_ui/src/component-library/index.ts
  mathesar_ui/src/component-library/select/Select.d.ts
  mathesar_ui/src/component-library/select/Select.svelte
  mathesar_ui/src/component-library/select/__meta__/Select.stories.svelte
  mathesar_ui/src/component-library/simple-select/SimpleSelect.svelte
  mathesar_ui/src/component-library/simple-select/__meta__/SimpleSelect.stories.svelte
  mathesar_ui/src/component-library/types.d.ts
  mathesar_ui/src/components/SelectColumn.svelte
  mathesar_ui/src/components/SelectSortDirection.svelte
  mathesar_ui/src/sections/import-data/preview/PreviewColumn.svelte
  mathesar_ui/src/sections/table-view/header/header-cell/type-options/database-options/DbTypeSelect.svelte
  mathesar_ui/src/sections/table-view/status-pane/StatusPane.svelte
  mathesar_ui/src/stores/table-data/filtering.ts
Labels: status: review

#1155 Number component
  mathesar_ui/.eslintrc.cjs
  mathesar_ui/package-lock.json
  mathesar_ui/package.json
  mathesar_ui/src/component-library/common/utils/index.ts
  mathesar_ui/src/component-library/common/utils/inputUtils.ts
  mathesar_ui/src/component-library/common/utils/stringUtils.ts
  mathesar_ui/src/component-library/dynamic-input/DynamicInput.svelte
  mathesar_ui/src/component-library/formatted-input/FormattedInput.svelte
  mathesar_ui/src/component-library/formatted-input/InputFormatter.ts
  mathesar_ui/src/component-library/number-input/NumberInput.svelte
  mathesar_ui/src/component-library/number-input/StringifiedNumberInput.svelte
  mathesar_ui/src/component-library/number-input/__meta__/NumberInput.stories.svelte
  mathesar_ui/src/component-library/number-input/__tests__/NumberInput.test.ts
  mathesar_ui/src/component-library/number-input/number-formatter/AbstractNumberFormatter.ts
  mathesar_ui/src/component-library/number-input/number-formatter/NumberFormatter.ts
  mathesar_ui/src/component-library/number-input/number-formatter/StringifiedNumberFormatter.ts
  mathesar_ui/src/component-library/number-input/number-formatter/__tests__/NumberFormatter.test.ts
  mathesar_ui/src/component-library/number-input/number-formatter/__tests__/cleaners.test.ts
  mathesar_ui/src/component-library/number-input/number-formatter/__tests__/formatter.test.ts
  mathesar_ui/src/component-library/number-input/number-formatter/cleaners.ts
  mathesar_ui/src/component-library/number-input/number-formatter/formatter.ts
  mathesar_ui/src/component-library/number-input/number-formatter/index.ts
  mathesar_ui/src/component-library/number-input/number-formatter/inference.ts
  mathesar_ui/src/component-library/number-input/number-formatter/locale.ts
  mathesar_ui/src/component-library/number-input/number-formatter/options.ts
  mathesar_ui/src/component-library/number-input/number-formatter/parsers.ts
  mathesar_ui/src/component-library/number-input/number-formatter/types.ts
  mathesar_ui/src/component-library/number-input/numberInputUtils.ts
Labels: status: review

#1253 Added cell border Styling when in edit mode
  mathesar_ui/src/components/cell/cell-types/common/SteppedInputCell.svelte
Labels: status: review

#1204 Fixes #1131 - Add E2E tests for checking the toggle button
  mathesar/tests/integration/conftest.py
  mathesar/tests/integration/test_text_type.py
Labels: status: review

#1223 Add a Unique constraint to Table model
  mathesar/migrations/0027_auto_20220329_1855.py
  mathesar/models.py
Labels: status: review
