Repository mathesar-foundation/mathesar, pull requests merged in 2023-04, with the labels that each got.

#2699 Adding non-breaking spaces after icons in our NameWithIcon component
  mathesar_ui/src/components/NameWithIcon.svelte
Labels: status: review

#2791 Add prefix `/db/` to database route and subroutes
  mathesar/urls.py
  mathesar_ui/src/routes/RootRoute.svelte
  mathesar_ui/src/routes/urls.ts
Labels: status: review

#2792 Allow dragging to select cells from active cell
  mathesar_ui/src/components/cell-fabric/CellFabric.svelte
  mathesar_ui/src/systems/data-explorer/result-pane/ResultRowCell.svelte
  mathesar_ui/src/systems/table-view/row/RowCell.svelte
Labels: status: review

#2795 Fixes #2664: Added workflow to automate PR to develop branch on merge to master branch
  .github/workflows/automate-pr-to-develop.yml
Labels: status: waiting

#2727 added docker compose
  docs/docs/contributing/local-dev.md
Labels: status: review

#2725 Reduce max column name size (during CSV import) further
  db/identifiers.py
  mathesar/tests/api/test_table_api.py
  mathesar/tests/imports/test_csv.py
Labels: work: backend, status: waiting

#2516 Common Header typographies, Fixes part issue #2416
  mathesar_ui/src/App.svelte
  mathesar_ui/src/pages/import-preview/ImportPreviewPage.svelte
  mathesar_ui/src/pages/record/TableWidget.svelte
  mathesar_ui/src/pages/user-profile/ProfilePage.svelte
Labels: status: review

#2772 Fixes #2764: Preventing user from changing column type to JSON or map from data inspector
  mathesar_ui/src/components/abstract-type-control/AbstractTypeSelector.svelte
Labels: status: review

#2819 Add docs for connecting mathesar to local db
  docs/docs/install/docker-compose/connecting-local-db.md
  docs/docs/install/docker-compose/index.md
Labels: status: waiting

#2803 Showed both row and column level context menu options in the cell level #2728
  mathesar_ui/src/systems/table-view/row/Row.svelte
  mathesar_ui/src/systems/table-view/row/RowCell.svelte
  mathesar_ui/src/systems/table-view/row/RowContextOptions.svelte
Labels: status: review

#2762 Disable form inputs while submitting
  mathesar_ui/src/component-library/checkbox-group/CheckboxGroup.svelte
  mathesar_ui/src/component-library/common/utils/storeUtils.ts
  mathesar_ui/src/component-library/dropdown-menu/DropdownMenu.svelte
  mathesar_ui/src/component-library/dropdown/Dropdown.svelte
  mathesar_ui/src/component-library/fieldset-group/FieldsetGroup.svelte
  mathesar_ui/src/component-library/radio-group/RadioGroup.svelte
  mathesar_ui/src/components/form/Field.svelte
  mathesar_ui/src/components/form/FormSubmit.svelte
  mathesar_ui/src/components/form/FormSubmitWithCatch.svelte
  mathesar_ui/src/components/form/field.ts
  mathesar_ui/src/components/form/form.ts
  mathesar_ui/src/components/form/index.ts
  mathesar_ui/src/pages/record/DirectField.svelte
  mathesar_ui/src/pages/record/RecordPageContent.svelte
  mathesar_ui/src/pages/schema/TableCard.svelte
  mathesar_ui/src/systems/data-explorer/ActionsPane.svelte
  mathesar_ui/src/systems/table-view/header/new-column-cell/NewColumnCell.svelte
  mathesar_ui/src/systems/table-view/link-table/LinkTableForm.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record-summary/AppendColumn.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record-summary/RecordSummaryConfig.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record-summary/TemplateInput.svelte
  mathesar_ui/src/systems/users-and-permissions/PasswordChangeForm.svelte
  mathesar_ui/src/systems/users-and-permissions/UserDetailsForm.svelte
Labels: status: review

#2773 Allow data to be copied from Mathesar and pasted elsewhere
  mathesar_ui/src/App.svelte
  mathesar_ui/src/component-library/toast/ToastController.ts
  mathesar_ui/src/components/cell-fabric/data-types/arrayFactory.ts
  mathesar_ui/src/components/cell-fabric/data-types/boolean.ts
  mathesar_ui/src/components/cell-fabric/data-types/components/CellWrapper.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/typeDefinitions.ts
  mathesar_ui/src/components/cell-fabric/data-types/date.ts
  mathesar_ui/src/components/cell-fabric/data-types/datetime.ts
  mathesar_ui/src/components/cell-fabric/data-types/duration.ts
  mathesar_ui/src/components/cell-fabric/data-types/money.ts
  mathesar_ui/src/components/cell-fabric/data-types/number.ts
  mathesar_ui/src/components/cell-fabric/data-types/string.ts
  mathesar_ui/src/components/cell-fabric/data-types/time.ts
  mathesar_ui/src/components/cell-fabric/data-types/typeDefinitions.ts
  mathesar_ui/src/components/cell-fabric/data-types/uri.ts
  mathesar_ui/src/components/cell-fabric/utils.ts
  mathesar_ui/src/components/sheet/Sheet.svelte
  mathesar_ui/src/components/sheet/SheetClipboardHandler.ts
  mathesar_ui/src/components/sheet/SheetSelection.ts
  mathesar_ui/src/icons/index.ts
  mathesar_ui/src/stores/clipboard.ts
  mathesar_ui/src/stores/table-data/index.ts
  mathesar_ui/src/stores/table-data/processedColumns.ts
  mathesar_ui/src/systems/data-explorer/result-pane/Results.svelte
  mathesar_ui/src/systems/data-explorer/utils.ts
  mathesar_ui/src/systems/table-view/TableView.svelte
  mathesar_ui/src/systems/table-view/row/RowCell.svelte
  mathesar_ui/src/utils/languageUtils.ts
Labels: status: review

#2768 [#2355] Part 2- Fixes for Icon type for Unique Constraint, Foreign Key Constraint and Record Summary
  mathesar_ui/src/components/filter-entry/FilterEntry.svelte
  mathesar_ui/src/components/group-entry/GroupEntry.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/filter/FilterEntries.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/group/Group.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/sort/Sort.svelte
  mathesar_ui/src/systems/table-view/constraints/NewFkConstraint.svelte
  mathesar_ui/src/systems/table-view/constraints/NewUniqueConstraint.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record-summary/AppendColumn.svelte
  mathesar_ui/src/utils/columnUtils.ts
Labels: status: review

#2735 Doc for getting started with the FE codebase
  docs/docs/contributing/getting-started-with-frontend-codebase.md
  docs/docs/index.md
Labels: status: review

#2794 Clean up some form validation code
  mathesar_ui/src/components/form/field.ts
  mathesar_ui/src/components/form/validators.ts
  mathesar_ui/src/systems/users-and-permissions/UserDetailsForm.svelte
Labels: status: review

#2677 Add documentation to rebuild docker image when there is dependency change
  docs/docs/contributing/local-dev.md
Labels: status: review

#2808 Resizable Sidebars
  mathesar_ui/src/component-library/common/actions/slider.ts
  mathesar_ui/src/component-library/index.ts
  mathesar_ui/src/component-library/styles.scss
  mathesar_ui/src/component-library/with-panel/WithPanel.scss
  mathesar_ui/src/component-library/with-panel/WithPanel.svelte
  mathesar_ui/src/component-library/with-panel/__meta__/WithPanel.stories.svelte
  mathesar_ui/src/components/sheet/SheetCellResizer.svelte
  mathesar_ui/src/pages/exploration/ExplorationPage.svelte
  mathesar_ui/src/stores/LocalStorageStore.ts
  mathesar_ui/src/stores/localStorage.ts
  mathesar_ui/src/stores/releases.ts
  mathesar_ui/src/systems/data-explorer/DataExplorer.svelte
  mathesar_ui/src/systems/data-explorer/exploration-inspector/ExplorationInspector.svelte
  mathesar_ui/src/systems/data-explorer/exploration-inspector/WithExplorationInspector.svelte
  mathesar_ui/src/systems/data-explorer/exploration-inspector/index.ts
  mathesar_ui/src/systems/data-explorer/index.ts
  mathesar_ui/src/systems/data-explorer/input-sidebar/InputSidebar.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/WithInputSidebar.svelte
  mathesar_ui/src/systems/data-explorer/result-pane/ResultPane.svelte
  mathesar_ui/src/systems/data-explorer/result-pane/Results.svelte
  mathesar_ui/src/systems/table-view/TableView.svelte
  mathesar_ui/src/systems/table-view/table-inspector/TableInspector.svelte
  mathesar_ui/src/systems/table-view/table-inspector/WithTableInspector.svelte
Labels: status: review

#2818 Move docker compose services used for development into a separate compose file
  .github/workflows/run-pytest.yml
  docker-compose.dev.yml
  docker-compose.yml
  docs/docs/contributing/local-dev.md
  docs/docs/install/docker-compose/index.md
  docs/docs/install/docker-compose/troubleshooting.md
  install.sh
Labels: status: waiting

#2824 Add documentation for configuring Mathesar
  docs/docs/install/configuration.md
  docs/docs/install/index.md
  docs/mkdocs.yml
Labels: status: review

#2834 Avoid text selection when selecting cells in safari
  mathesar_ui/src/component-library/tabs/TabContainer.scss
  mathesar_ui/src/components/sheet/SheetHeader.svelte
  mathesar_ui/src/systems/data-explorer/result-pane/ResultRowCell.svelte
  mathesar_ui/src/systems/table-view/row/Row.svelte
  mathesar_ui/src/systems/table-view/row/RowCell.svelte
  mathesar_ui/src/systems/table-view/row/RowControl.svelte
Labels: status: review

#2813 Make sure multi-db tests are passing
  mathesar/tests/test_multi_db.py
Labels: work: backend

#2828 SQL port for schema related DDL operations
  conftest.py
  db/install.py
  db/schemas/operations/alter.py
  db/schemas/operations/create.py
  db/schemas/operations/drop.py
  db/sql/0_msar.sql
  db/tables/operations/create.py
  db/tables/operations/infer_types.py
  db/tests/schemas/operations/test_alter.py
  db/tests/schemas/operations/test_drop.py
  db/types/install.py
Labels: status: waiting

#2826 Add Documentation for Docker compose Manual Installation without using the `install.sh` script
  docker-compose.yml
  docs/docs/install/configuration.md
  docs/docs/install/docker-compose/index.md
  docs/docs/install/docker-compose/troubleshooting.md
  docs/docs/install/docker-compose/under-the-hood.md
  docs/docs/stylesheets/extra.css
  docs/mkdocs.yml
Labels: status: review

#2848 Make Dockerfile standalone + remove redundant environment variables
  .env.example
  Dockerfile
  config/settings/common_settings.py
  docker-compose.yml
  docs/docs/install/docker-compose/index.md
  install.py
  install.sh
  setup.cfg
Labels: status: waiting

#2846 Improve ambiguous links to record page within the new cell context menu
  mathesar_ui/src/systems/table-view/row/RowCell.svelte
Labels: status: review
