Repository mathesar-foundation/mathesar, pull requests merged in 2023-10, with the labels that each got.

#3170 API for database config
  config/settings/common_settings.py
  db/types/install.py
  demo/management/commands/load_arxiv_data.py
  demo/management/commands/setup_demo_template_db.py
  demo/middleware.py
  mathesar/api/db/permissions/database.py
  mathesar/api/db/viewsets/databases.py
  mathesar/api/exceptions/error_codes.py
  mathesar/api/exceptions/generic_exceptions/base_exceptions.py
  mathesar/api/exceptions/validation_exceptions/exceptions.py
  mathesar/api/serializers/databases.py
  mathesar/api/utils.py
  mathesar/apps.py
  mathesar/database/base.py
  mathesar/exception_handlers.py
  mathesar/imports/csv.py
  mathesar/imports/excel.py
  mathesar/imports/json.py
  mathesar/install.py
  mathesar/migrations/0008_auto_20230921_1834.py
  mathesar/models/base.py
  mathesar/state/django.py
  mathesar/tests/api/test_database_api.py
  mathesar/tests/conftest.py
  mathesar/tests/test_models.py
  mathesar/utils/schemas.py
  mathesar/utils/tables.py
  mathesar/views.py
  requirements.txt
Labels: status: review

#3229 Make MATHESAR_CLIENT_DEV_URL configurable via .env
  config/settings/common_settings.py
Labels: affects: dx

#3197 fix: read-only css for input
  mathesar_ui/src/component-library/common/styles/components/input.scss
  mathesar_ui/src/component-library/text-input/TextInput.svelte
Labels: status: review

#3102 [i18n] Load "en" translations parallely
  config/context_processors.py
  config/settings/common_settings.py
  mathesar/templates/mathesar/index.html
  mathesar/utils/frontend.py
  mathesar_ui/src/App.svelte
  mathesar_ui/src/global.d.ts
  mathesar_ui/src/i18n/en/index.ts
  mathesar_ui/src/i18n/formatters.ts
  mathesar_ui/src/i18n/i18n-load.ts
  mathesar_ui/src/i18n/i18n-store.ts
  mathesar_ui/src/i18n/i18n-svelte.ts
  mathesar_ui/src/i18n/i18n-util.ts
  mathesar_ui/src/i18n/ja/index.ts
  mathesar_ui/vite.config.js
Labels: status: waiting

#3103 [i18n] Save preferred_language for auth user in db
  config/context_processors.py
  config/settings/common_settings.py
  mathesar/api/ui/serializers/users.py
  mathesar/migrations/0005_user_display_language.py
  mathesar/migrations/0009_merge_20231025_1733.py
  mathesar/models/users.py
  mathesar/views.py
  mathesar_ui/src/api/users.ts
  mathesar_ui/src/i18n/i18n-util.ts
  mathesar_ui/src/stores/users.ts
  mathesar_ui/src/systems/users-and-permissions/SelectDisplayLanguage.svelte
  mathesar_ui/src/systems/users-and-permissions/UserDetailsForm.svelte
  mathesar_ui/src/utils/preloadData.ts
Labels: status: blocked

#3104 [i18n] Language switcher for anon users
  mathesar/templates/mathesar/login_base.html
  mathesar/urls.py
Labels: status: blocked

#3254 add jobs for testing strategy branches
  .github/workflows/handle-required-checks.yml
  .github/workflows/run-flake8.yml
  .github/workflows/run-lint-audit-tests-ui.yml
  .github/workflows/run-pytest.yml
  .github/workflows/run-sql-tests.yml
  .github/workflows/run-vulture.yml
  .github/workflows/test-and-lint-code.yml
Labels: priority: urgent, status: review

#3243 Fix check constraints on a table breaking the app
  mathesar/api/serializers/constraints.py
  mathesar/tests/conftest.py
Labels: status: review

#3220 bug: Close on overlay click -ModalRecordSelector
  mathesar_ui/src/systems/record-selector/RecordSelectorWindow.svelte
Labels: status: review

#3271 Generated OpenAPI specification for `database_roles` endpoint
  config/settings/openapi.py
  schema.yml
Labels: work: documentation, type: enhancement, work: backend, status: ready
