Repository mathesar-foundation/mathesar, pull requests merged in 2023-05, with the labels that each got.

#2832 Clean up NewFkConstraint form
  mathesar_ui/src/components/SelectColumn.svelte
  mathesar_ui/src/components/SelectProcessedColumn.svelte
  mathesar_ui/src/components/form/FormSubmit.svelte
  mathesar_ui/src/components/form/form.ts
  mathesar_ui/src/components/form/validators.ts
  mathesar_ui/src/systems/table-view/constraints/NewFkConstraint.svelte
  mathesar_ui/src/systems/table-view/link-table/LinkTableForm.svelte
Labels: status: review

#2847 Implement UI to switch DBs
  mathesar_ui/src/App.svelte
  mathesar_ui/src/__tests__/App.test.ts
  mathesar_ui/src/component-library/button/Button.scss
  mathesar_ui/src/component-library/common/styles/components/input.scss
  mathesar_ui/src/component-library/common/styles/variables.scss
  mathesar_ui/src/component-library/common/utils/ImmutableSet.ts
  mathesar_ui/src/component-library/common/utils/ReductionStore.ts
  mathesar_ui/src/component-library/common/utils/WritableSet.ts
  mathesar_ui/src/component-library/dropdown/AttachableDropdown.svelte
  mathesar_ui/src/component-library/dropdown/Dropdown.scss
  mathesar_ui/src/component-library/dropdown/Dropdown.svelte
  mathesar_ui/src/component-library/help/Help.svelte
  mathesar_ui/src/component-library/label/Label.svelte
  mathesar_ui/src/component-library/menu/ButtonMenuItem.svelte
  mathesar_ui/src/component-library/menu/CheckboxMenuItem.svelte
  mathesar_ui/src/component-library/menu/LinkMenuItem.svelte
  mathesar_ui/src/component-library/menu/Menu.scss
  mathesar_ui/src/component-library/menu/Menu.svelte
  mathesar_ui/src/component-library/menu/MenuController.ts
  mathesar_ui/src/component-library/menu/MenuHeading.svelte
  mathesar_ui/src/component-library/menu/MenuItemContents.svelte
  mathesar_ui/src/component-library/menu/MenuItemWrapper.svelte
  mathesar_ui/src/component-library/menu/__meta__/Menu.stories.svelte
  mathesar_ui/src/component-library/menu/index.ts
  mathesar_ui/src/component-library/tooltip/Tooltip.scss
  mathesar_ui/src/component-library/tooltip/Tooltip.svelte
  mathesar_ui/src/components/AppSecondaryHeader.svelte
  mathesar_ui/src/components/DatabaseName.svelte
  mathesar_ui/src/components/DocsLink.svelte
  mathesar_ui/src/components/NameWithIcon.svelte
  mathesar_ui/src/components/breadcrumb/BreadcrumbItem.svelte
  mathesar_ui/src/components/breadcrumb/DatabaseSelector.svelte
  mathesar_ui/src/layouts/InsetPageLayout.svelte
  mathesar_ui/src/layouts/LayoutWithHeader.svelte
  mathesar_ui/src/layouts/PageLayoutWithSidebar.svelte
  mathesar_ui/src/pages/admin-users/AdminNavigation.svelte
  mathesar_ui/src/pages/admin-users/AdminPageLayout.svelte
  mathesar_ui/src/pages/admin-users/UserListingPage.svelte
  mathesar_ui/src/pages/database/DatabaseDetails.svelte
  mathesar_ui/src/pages/database/DatabaseNavigationList.svelte
  mathesar_ui/src/pages/database/DatabasePage.svelte
  mathesar_ui/src/pages/database/SchemaRow.svelte
  mathesar_ui/src/pages/import-preview/ImportPreviewPage.svelte
  mathesar_ui/src/pages/import-upload/ImportUploadPage.svelte
  mathesar_ui/src/pages/schema/SchemaPage.svelte
  mathesar_ui/src/pages/user-profile/ProfilePage.svelte
  mathesar_ui/src/routes/AdminRoute.svelte
  mathesar_ui/src/routes/DatabaseRoute.svelte
  mathesar_ui/src/stores/databases.ts
Labels: status: waiting

#2854 Override entrypoint in docker-compose config files
  docker-compose.dev.yml
  docker-compose.yml
Labels: status: review

#2825 Fix text wrapping within NameWithIcon
  mathesar_ui/src/components/NameWithIcon.svelte
Labels: status: review

#2856 Fix regression displaying record page table widget
  mathesar_ui/src/systems/table-view/TableView.svelte
  mathesar_ui/src/systems/table-view/table-inspector/WithTableInspector.svelte
Labels: status: review

#2840 Specify the limitation of the Docker compose install script
  docs/docs/install/docker-compose/index.md
Labels: status: review

#2851 Docker compose installation docs improvements.
  docker-compose.yml
  docs/docs/install/configuration.md
  docs/docs/install/docker-compose/connecting-local-db.md
  docs/docs/install/docker-compose/index.md
Labels: status: review

#2833 Clean up dev docs
  CONTRIBUTING.md
  DEVELOPER_GUIDE.md
  README.md
  demo/README.md
  docs/README.md
  docs/docs/contributing/local-dev.md
  docs/docs/contributing/welcome.md
  docs/docs/index.md
  docs/mkdocs.yml
  mathesar/api/README.md
  mathesar/api/STANDARDS.md
  mathesar/tests/integration/README.md
  mathesar_ui/ARCHITECTURE.md
  mathesar_ui/README.md
  mathesar_ui/STANDARDS.md
  mathesar_ui/src/api/utils/errors.ts
  mathesar_ui/src/component-library/README.md
  mathesar_ui/src/stores/storeBasedUrls.ts
Labels: status: review

#2838 Documentation for Installing Mathsar using Docker Image
  docs/docs/install/docker/index.md
  docs/docs/install/index.md
  docs/mkdocs.yml
Labels: work: documentation, status: review

#2861 Link to commit message guidelines from CONTRIBUTING.md
  CONTRIBUTING.md
Labels: status: review

#2862 RSQLA for dropping constraints
  db/constraints/operations/drop.py
  db/sql/0_msar.sql
Labels: status: review

#2868 Improve documentation structure
  .github/workflows/deploy-docs.yml
  .github/workflows/test-docs.yml
  docker-compose.yml
  docs/README.md
  docs/docs/administration/uninstall.md
  docs/docs/administration/upgrade.md
  docs/docs/configuration/connect-to-existing-db.md
  docs/docs/configuration/customize-docker-compose.md
  docs/docs/configuration/env-variables.md
  docs/docs/contributing/getting-started-with-frontend-codebase.md
  docs/docs/index.md
  docs/docs/install/docker-compose/connecting-local-db.md
  docs/docs/install/docker-compose/index.md
  docs/docs/install/index.md
  docs/docs/installation/build-from-source/index.md
  docs/docs/installation/docker-compose/index.md
  docs/docs/installation/docker/index.md
  docs/docs/installation/guided-install/index.md
  docs/docs/installation/guided-install/troubleshooting.md
  docs/docs/installation/guided-install/under-the-hood.md
  docs/docs/installation/index.md
  docs/docs/snippets/docker-compose-administration.md
  docs/docs/snippets/docker-compose-prerequisites.md
  docs/docs/user-guide/index.md
  docs/docs/user-guide/syncing-db.md
  docs/docs/user-guide/users.md
  docs/mkdocs.yml
  docs/requirements.txt
  install.sh
  mathesar_ui/src/pages/database/DatabaseNavigationList.svelte
Labels: status: review

#2809 Documentation for installing Mathesar on Debian and Ubuntu
  docs/docs/installation/build-from-source/index.md
Labels: work: documentation, status: review

#2873 Docs cleanup for installing from source
  docs/README.md
  docs/docs/installation/build-from-source/index.md
  docs/mkdocs.yml
  docs/placeholder-plugin.yaml
  docs/requirements.txt
  requirements.txt
Labels: status: review

#2858 Protect tables more
  mathesar_ui/src/component-library/confirmation/Confirmation.svelte
  mathesar_ui/src/component-library/confirmation/ConfirmationController.ts
  mathesar_ui/src/pages/record/recordHelp.ts
  mathesar_ui/src/pages/schema/TableCard.svelte
  mathesar_ui/src/systems/table-view/row/RowContextOptions.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record/RowActions.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/TableActions.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/TableDeleteConfirmationBody.svelte
  mathesar_ui/src/utils/languageUtils.ts
Labels: status: review

#2878 Set default value of DOMAIN_NAME to http://localhost
  docker-compose.yml
Labels: status: review

#2879 Psycopg requirements fix
  docs/docs/installation/build-from-source/index.md
  docs/placeholder-plugin.yaml
  requirements.txt
Labels: status: review

#2782 Add/Remove filters via the column header context menu
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LinkedRecordInput.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LinkedRecordUtils.ts
  mathesar_ui/src/components/filter-entry/FilterEntry.svelte
  mathesar_ui/src/components/filter-entry/utils.ts
  mathesar_ui/src/icons/index.ts
  mathesar_ui/src/pages/table/ImperativeFilterController.ts
  mathesar_ui/src/pages/table/TablePage.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/filter/Filter.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/filter/FilterDropdown.svelte
  mathesar_ui/src/systems/table-view/header/header-cell/ColumnHeaderContextMenu.svelte
  mathesar_ui/src/utils/languageUtils.ts
Labels: status: review

#2882 Add information of the acceptable values for `ALLOWED_HOSTS` env variable
  docs/docs/configuration/env-variables.md
Labels: status: review

#2780 Disable Default value assignment for columns with Dynamic Defaults
  mathesar/api/exceptions/database_exceptions/exceptions.py
  mathesar/api/exceptions/error_codes.py
  mathesar/api/serializers/columns.py
  mathesar/tests/api/test_column_api.py
Labels: status: review

#2886 Comment `depends_on` property when disabling the inbuilt-database
  docs/docs/configuration/customize-docker-compose.md
  docs/docs/installation/docker-compose/index.md
Labels: status: review

#2874 Add support for Unsetting Default Value of a column
  mathesar_ui/src/systems/table-view/table-inspector/column/SetDefaultValue.svelte
Labels: status: waiting

#2889 Hotfixes to release v0.1.2 based on testing feedback
  docs/docs/configuration/customize-docker-compose.md
  docs/docs/installation/docker-compose/index.md
  mathesar/api/exceptions/database_exceptions/exceptions.py
  mathesar/api/exceptions/error_codes.py
  mathesar/api/serializers/columns.py
  mathesar/tests/api/test_column_api.py
  mathesar_ui/src/systems/table-view/table-inspector/column/SetDefaultValue.svelte
  requirements.txt
Labels: status: review

#2891 Prevent default credentials being used for removed DBs
  mathesar/database/base.py
  mathesar/views.py
Labels: status: review
