Repository mathesar-foundation/mathesar, pull requests merged in 2023-02, with the labels that each got.

#2339 Navbar navigates to import preview page for tables with unconfirmed imports
  mathesar_ui/src/components/TableName.svelte
  mathesar_ui/src/components/breadcrumb/BreadcrumbItem.svelte
  mathesar_ui/src/components/breadcrumb/BreadcrumbSelectorRow.svelte
  mathesar_ui/src/components/breadcrumb/EntitySelector.svelte
  mathesar_ui/src/utils/tables.ts
Labels: status: review

#2386 Added confirmation when deleting records via table inspector , Fix #2236
  mathesar_ui/src/systems/table-view/table-inspector/record/RowActions.svelte
Labels: status: waiting

#2403 Fix duplicate migrations bug
  mathesar/migrations/0001_initial.py
  mathesar/migrations/0005_auto_20221014_1109.py
  mathesar/migrations/0006_auto_20221110_1152.py
  mathesar/migrations/0007_auto_20221115_0627.py
  mathesar/migrations/0009_auto_20221123_1423.py
  mathesar/migrations/0010_auto_20221208_2041.py
  mathesar/migrations/0011_auto_20221208_2303.py
  mathesar/migrations/0012_auto_20221212_2148.py
  mathesar/migrations/0013_auto_20230119_1303.py
  mathesar/models/query.py
  mathesar/models/validators.py
Labels: status: review

#2344 Add query-param for faster type inference when columns known not to have defaults
  db/columns/operations/alter.py
  db/columns/operations/infer_types.py
  db/tables/operations/infer_types.py
  db/tests/tables/operations/test_infer_types.py
  mathesar/api/db/viewsets/tables.py
  mathesar/utils/tables.py
  mathesar_ui/src/stores/tables.ts
Labels: work: backend, status: review

#2329 Restrict common data based on user permission
  mathesar/api/db/permissions/query_table.py
  mathesar/views.py
Labels: status: review

#2390 Users - base work
  mathesar/urls.py
  mathesar/views.py
  mathesar_ui/package-lock.json
  mathesar_ui/package.json
  mathesar_ui/src/App.svelte
  mathesar_ui/src/api/users.ts
  mathesar_ui/src/api/utils/errors.ts
  mathesar_ui/src/component-library/common/types/ComponentAndPropsTypes.ts
  mathesar_ui/src/component-library/index.ts
  mathesar_ui/src/component-library/password-input/PasswordInput.svelte
  mathesar_ui/src/component-library/password-input/PasswordInputTypes.ts
  mathesar_ui/src/component-library/types.ts
  mathesar_ui/src/components/AppHeader.svelte
  mathesar_ui/src/components/InsetPageSection.svelte
  mathesar_ui/src/components/breadcrumb/Breadcrumb.svelte
  mathesar_ui/src/components/form/Field.svelte
  mathesar_ui/src/components/form/FormSubmitWithCatch.svelte
  mathesar_ui/src/components/form/field.ts
  mathesar_ui/src/components/form/validators.ts
  mathesar_ui/src/components/message-boxes/ErrorBox.svelte
  mathesar_ui/src/components/message-boxes/InfoBox.svelte
  mathesar_ui/src/components/message-boxes/OutcomeBox.svelte
  mathesar_ui/src/components/message-boxes/WarningBox.svelte
  mathesar_ui/src/icons/index.ts
  mathesar_ui/src/layouts/InsetPageLayout.svelte
  mathesar_ui/src/pages/admin-users/EditUserPage.svelte
  mathesar_ui/src/pages/admin-users/NewUserPage.svelte
  mathesar_ui/src/pages/admin-users/UserListingPage.svelte
  mathesar_ui/src/pages/import-preview/ImportPreviewPage.svelte
  mathesar_ui/src/pages/user-profile/ProfilePage.svelte
  mathesar_ui/src/routes/AdminRoute.svelte
  mathesar_ui/src/routes/RootRoute.svelte
  mathesar_ui/src/routes/UserProfileRoute.svelte
  mathesar_ui/src/routes/UsersRoute.svelte
  mathesar_ui/src/routes/urls.ts
  mathesar_ui/src/stores/abstract-types/store.ts
  mathesar_ui/src/stores/schemas.ts
  mathesar_ui/src/stores/userProfile.ts
  mathesar_ui/src/stores/users.ts
  mathesar_ui/src/systems/users-and-permissions/PasswordChangeForm.svelte
  mathesar_ui/src/systems/users-and-permissions/SelectRole.svelte
  mathesar_ui/src/systems/users-and-permissions/UserDetailsForm.svelte
  mathesar_ui/src/systems/users-and-permissions/UserFormInput.svelte
  mathesar_ui/src/systems/users-and-permissions/UserFormInputRow.svelte
  mathesar_ui/src/systems/users-and-permissions/index.ts
  mathesar_ui/src/utils/preloadData.ts
Labels: status: review

#2098 Creating More Helpful Error Messages in the Case Where an Email is Invalid
  mathesar/api/exceptions/database_exceptions/exceptions.py
  mathesar/api/exceptions/error_codes.py
  mathesar/api/serializers/records.py
  mathesar/tests/api/test_record_api.py
Labels: status: review

#2407 Allow creating new admin user
  mathesar/api/ui/serializers/users.py
  mathesar/tests/api/test_user_api.py
Labels: status: review

#2418 Silently run install.py with default values when using docker-compose up
  run.sh
Labels: status: review

#2426 Revert a bad merge
  mathesar_ui/package-lock.json
  run.sh
Labels: status: review

#2423 Styling admin & users list page
  mathesar_ui/src/components/PageTitleAndMeta.svelte
  mathesar_ui/src/pages/admin-users/AdminNavigation.svelte
  mathesar_ui/src/pages/admin-users/AdminPageLayout.svelte
  mathesar_ui/src/pages/admin-users/UserListingPage.svelte
  mathesar_ui/src/pages/admin-users/UserRow.svelte
  mathesar_ui/src/routes/AdminRoute.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record/RowActions.svelte
Labels: status: review

#2436 Minor code clean up in Users code
  mathesar_ui/src/App.svelte
  mathesar_ui/src/pages/admin-users/EditUserPage.svelte
  mathesar_ui/src/pages/admin-users/NewUserPage.svelte
  mathesar_ui/src/pages/admin-users/UserListingPage.svelte
  mathesar_ui/src/pages/user-profile/ProfilePage.svelte
  mathesar_ui/src/routes/UsersRoute.svelte
  mathesar_ui/src/stores/userProfile.ts
  mathesar_ui/src/stores/users.ts
  mathesar_ui/src/systems/users-and-permissions/UserDetailsForm.svelte
  mathesar_ui/src/utils/typeUtils.ts
Labels: status: review

#2424 Added success_url for the successful password reset Issue#2312
  mathesar/users/password_reset.py
Labels: status: review

#2401 Setup Watchtower
  Caddyfile
  docker-compose.yml
Labels: work: infrastructure

#2429 Style the password reset page
  mathesar/templates/mathesar/login_base.html
  mathesar/templates/registration/login.html
  mathesar/templates/users/password_reset_confirmation.html
Labels: status: review

#2439 Style Add/Edit User pages
  mathesar_ui/src/App.svelte
  mathesar_ui/src/component-library/cancel-or-proceed-button-pair/CancelOrProceedButtonPair.scss
  mathesar_ui/src/component-library/cancel-or-proceed-button-pair/CancelOrProceedButtonPair.svelte
  mathesar_ui/src/component-library/spinner-button/SpinnerButton.svelte
  mathesar_ui/src/icons/index.ts
  mathesar_ui/src/pages/admin-users/EditUserPage.svelte
  mathesar_ui/src/pages/admin-users/FormBox.svelte
  mathesar_ui/src/pages/admin-users/NewUserPage.svelte
  mathesar_ui/src/pages/import-preview/ImportPreviewPage.svelte
  mathesar_ui/src/pages/import-upload/ImportUploadPage.svelte
  mathesar_ui/src/pages/user-profile/ProfilePage.svelte
  mathesar_ui/src/stores/users.ts
  mathesar_ui/src/systems/users-and-permissions/UserDetailsForm.svelte
Labels: status: review

#2456 Allow editing user admin status from UI
  mathesar_ui/src/systems/users-and-permissions/UserDetailsForm.svelte
Labels: status: review

#2410 Enable caddy compression and precompression
  Caddyfile
Labels: work: backend, work: infrastructure, status: review

#2482 Update Logo
  README.md
Labels: status: review

#2443 Permission utilities
  mathesar_ui/src/App.svelte
  mathesar_ui/src/components/AppHeader.svelte
  mathesar_ui/src/pages/database/DatabasePage.svelte
  mathesar_ui/src/pages/database/SchemaRow.svelte
  mathesar_ui/src/pages/schema/SchemaExplorations.svelte
  mathesar_ui/src/pages/schema/SchemaOverview.svelte
  mathesar_ui/src/pages/schema/SchemaPage.svelte
  mathesar_ui/src/pages/schema/SchemaTables.svelte
  mathesar_ui/src/pages/schema/TableCard.svelte
  mathesar_ui/src/pages/schema/TablesList.svelte
  mathesar_ui/src/pages/user-profile/ProfilePage.svelte
  mathesar_ui/src/routes/DatabaseRoute.svelte
  mathesar_ui/src/routes/RootRoute.svelte
  mathesar_ui/src/stores/tables.ts
  mathesar_ui/src/stores/userProfile.ts
  mathesar_ui/src/systems/users-and-permissions/PasswordChangeForm.svelte
  mathesar_ui/src/systems/users-and-permissions/UserDetailsForm.svelte
  mathesar_ui/src/utils/permissions.ts
Labels: status: review

#2483 Fix typo in clean_stale_db command by changing timedelta function parameter from 'minutes' to 'days'
  demo/management/commands/clean_stale_db.py
Labels: status: review

#2497 Add Deployment docs
  docs/docs/administration/docker-compose.md
  docs/docs/index.md
  docs/docs/installation/docker-compose.md
  docs/mkdocs.yml
  install.sh
Labels: status: review

#2498 Access controls in Table Page
  mathesar_ui/src/systems/table-view/Body.svelte
  mathesar_ui/src/systems/table-view/StatusPane.svelte
  mathesar_ui/src/systems/table-view/TableView.svelte
  mathesar_ui/src/systems/table-view/row/RowCell.svelte
  mathesar_ui/src/systems/table-view/row/RowContextOptions.svelte
Labels: status: review

#2506 Fix permission check bug where map doesn't have the right key
  mathesar_ui/src/stores/userProfile.ts
Labels: status: review

#2500 Add analytics to the demo app
  config/settings/common_settings.py
  demo/settings.py
  demo/templates/demo/analytics.html
  mathesar/template_context_processors/__init__.py
  mathesar/template_context_processors/base_template_extensions.py
  mathesar/templates/mathesar/base.html
Labels: status: review

#2504 Restructured documentation.
  docs/docs/administration/docker-compose.md
  docs/docs/assets/images/favicon.ico
  docs/docs/assets/images/header.png
  docs/docs/index.md
  docs/docs/installation/docker-compose.md
  docs/mkdocs.yml
Labels: status: review

#2493 Stop proxying, put version in common_data
  mathesar/api/exceptions/error_codes.py
  mathesar/api/exceptions/version_exceptions/__init__.py
  mathesar/api/exceptions/version_exceptions/base_exceptions.py
  mathesar/api/ui/viewsets/version.py
  mathesar/tests/api/test_version_api.py
  mathesar/views.py
Labels: work: backend, status: review

#2486 Implement access control within the Record Selector
  mathesar_ui/src/systems/record-selector/RecordSelectorContent.svelte
Labels: status: review

#2460 Fix un-authenticated behavior for all endpoints
  config/settings/common_settings.py
  mathesar/api/db/permissions/columns.py
  mathesar/api/db/permissions/constraint.py
  mathesar/api/db/permissions/database.py
  mathesar/api/db/permissions/query.py
  mathesar/api/db/permissions/query_table.py
  mathesar/api/db/permissions/records.py
  mathesar/api/db/permissions/schema.py
  mathesar/api/db/permissions/table.py
  mathesar/api/db/permissions/table_settings.py
  mathesar/api/ui/permissions/database_role.py
  mathesar/api/ui/permissions/schema_role.py
  mathesar/api/ui/permissions/ui_database.py
  mathesar_ui/src/api/utils/requestUtils.ts
Labels: status: review

#2488 Implement access control within the Record Page
  mathesar_ui/src/components/LinkedRecord.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LinkedRecordInput.svelte
  mathesar_ui/src/pages/record/DirectField.svelte
Labels: status: review

#2489 Table inspector Access controls
  mathesar_ui/src/component-library/form-builder/FormBuilder.svelte
  mathesar_ui/src/component-library/form-builder/FormElement.svelte
  mathesar_ui/src/components/EditableTextWithActions.svelte
  mathesar_ui/src/components/abstract-type-control/AbstractTypeDisplayOptions.svelte
  mathesar_ui/src/stores/table-data/processedColumns.ts
  mathesar_ui/src/systems/table-view/constraints/ConstraintTypeSection.svelte
  mathesar_ui/src/systems/table-view/constraints/TableConstraints.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnFormatting.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnMode.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnOptions.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnType.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/RenameColumn.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/SetDefaultValue.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record-summary/RecordSummaryConfig.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record/RecordMode.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record/RowActions.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/TableActions.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/TableMode.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/links/LinksSectionContainer.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/links/TableLinks.svelte
  mathesar_ui/src/utils/permissions.ts
Labels: status: review

#2517 Reset migrations to single file
  mathesar/migrations/0001_initial.py
  mathesar/migrations/0002_auto_20221006_2232.py
  mathesar/migrations/0003_auto_20221006_2340.py
  mathesar/migrations/0004_auto_20221009_1324.py
  mathesar/migrations/0005_auto_20221014_1109.py
  mathesar/migrations/0006_auto_20221110_1152.py
  mathesar/migrations/0007_auto_20221115_0627.py
  mathesar/migrations/0008.py
  mathesar/migrations/0009_auto_20221123_1423.py
  mathesar/migrations/0010_auto_20221208_2041.py
  mathesar/migrations/0011_auto_20221208_2303.py
  mathesar/migrations/0012_auto_20221212_2148.py
  mathesar/migrations/0013_auto_20230119_1303.py
Labels: status: waiting

#2521 Increment patch version for mock release
  mathesar/__init__.py
Labels: work: backend

#2525 Avoid passing args to `_setup_demo_template_db` function
  demo/management/commands/setup_demo_template_db.py
Labels: status: review

#2531 Revert calling collect static commend from install.py
  install.py
Labels: status: review

#2524 Users & permissions - remaining frontend work
  mathesar_ui/src/api/users.ts
  mathesar_ui/src/component-library/button/Button.scss
  mathesar_ui/src/component-library/chip/Chip.scss
  mathesar_ui/src/component-library/chip/Chip.svelte
  mathesar_ui/src/component-library/select/Select.svelte
  mathesar_ui/src/component-library/spinner-button/SpinnerButton.svelte
  mathesar_ui/src/icons/index.ts
  mathesar_ui/src/pages/admin-users/EditUserPage.svelte
  mathesar_ui/src/pages/admin-users/UserListingPage.svelte
  mathesar_ui/src/pages/admin-users/UserRow.svelte
  mathesar_ui/src/pages/data-explorer/DataExplorerPage.svelte
  mathesar_ui/src/pages/database/DatabasePage.svelte
  mathesar_ui/src/pages/database/DbAccessControlModal.svelte
  mathesar_ui/src/pages/exploration/ExplorationPage.svelte
  mathesar_ui/src/pages/exploration/Header.svelte
  mathesar_ui/src/pages/schema/SchemaAccessControlModal.svelte
  mathesar_ui/src/pages/schema/SchemaPage.svelte
  mathesar_ui/src/routes/DataExplorerRoute.svelte
  mathesar_ui/src/routes/RootRoute.svelte
  mathesar_ui/src/routes/SchemaRoute.svelte
  mathesar_ui/src/routes/urls.ts
  mathesar_ui/src/stores/userProfile.ts
  mathesar_ui/src/stores/users.ts
  mathesar_ui/src/systems/data-explorer/ActionsPane.svelte
  mathesar_ui/src/systems/data-explorer/DataExplorer.svelte
  mathesar_ui/src/systems/data-explorer/exploration-inspector/ExplorationInspector.svelte
  mathesar_ui/src/systems/data-explorer/exploration-inspector/ExplorationTab.svelte
  mathesar_ui/src/systems/users-and-permissions/AccessControlRow.svelte
  mathesar_ui/src/systems/users-and-permissions/AccessControlView.svelte
  mathesar_ui/src/systems/users-and-permissions/index.ts
  mathesar_ui/src/utils/permissions.ts
Labels: status: review

#2513 Add telemetry to frontend app
  demo/templates/demo/analytics.html
  mathesar_ui/src/pages/schema/SchemaPage.svelte
  mathesar_ui/src/utils/telemetry.ts
Labels: status: review

#2527 Replace aggregate_to_array with distinct_aggregate_to_array
  mathesar_ui/src/api/types/queries.ts
  mathesar_ui/src/systems/data-explorer/QuerySummarizationTransformationModel.ts
  mathesar_ui/src/systems/data-explorer/input-sidebar/transformations-pane/summarization/Aggregation.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/transformations-pane/summarization/SummarizationTransformation.svelte
  mathesar_ui/src/systems/data-explorer/utils.ts
Labels: status: review

#2530 Turn on SSL support in caddy
  Caddyfile
  Dockerfile.caddy
  docker-compose.yml
  install.sh
Labels: status: review

#2533 Force POST method for upgrade calls
  Caddyfile
Labels: work: backend, status: review

#2514 In-app upgrades
  mathesar/urls.py
  mathesar_ui/src/3rd-party-apis/github-releases.ts
  mathesar_ui/src/App.svelte
  mathesar_ui/src/api/upgrade.ts
  mathesar_ui/src/api/utils/requestUtils.ts
  mathesar_ui/src/component-library/icon/Icon.scss
  mathesar_ui/src/component-library/icon/Icon.svelte
  mathesar_ui/src/component-library/icon/IconPath.svelte
  mathesar_ui/src/component-library/icon/iconUtils.ts
  mathesar_ui/src/component-library/menu/ButtonMenuItem.svelte
  mathesar_ui/src/component-library/menu/LinkMenuItem.svelte
  mathesar_ui/src/components/AppHeader.svelte
  mathesar_ui/src/icons/index.ts
  mathesar_ui/src/pages/admin-update/ReleaseBox.svelte
  mathesar_ui/src/pages/admin-update/SoftwareUpdateContent.svelte
  mathesar_ui/src/pages/admin-update/SoftwareUpdatePage.svelte
  mathesar_ui/src/pages/admin-update/upgrade-modal/UpgradeConfirm.svelte
  mathesar_ui/src/pages/admin-update/upgrade-modal/UpgradeError.svelte
  mathesar_ui/src/pages/admin-update/upgrade-modal/UpgradeModal.svelte
  mathesar_ui/src/pages/admin-update/upgrade-modal/UpgradeProcessing.svelte
  mathesar_ui/src/pages/admin-users/AdminNavigation.svelte
  mathesar_ui/src/pages/admin-users/AdminPageLayout.svelte
  mathesar_ui/src/pages/admin-users/UserListingPage.svelte
  mathesar_ui/src/routes/AdminRoute.svelte
  mathesar_ui/src/routes/urls.ts
  mathesar_ui/src/stores/releases.ts
  mathesar_ui/src/stores/userProfile.ts
  mathesar_ui/src/utils/cachedFetchStore.ts
  mathesar_ui/src/utils/preloadData.ts
Labels: status: review

#2540 Update schema access control modal UX, allow schema managers to edit & delete the schema they have access to
  mathesar_ui/src/pages/database/DatabasePage.svelte
  mathesar_ui/src/systems/users-and-permissions/AccessControlRow.svelte
  mathesar_ui/src/systems/users-and-permissions/AccessControlView.svelte
Labels: status: review

#2551 Warn live demo users that Mathesar does not work on mobile devices
  mathesar/templates/mathesar/login_base.html
Labels: status: review

#2529 Consistent 404 pages across client and server
  config/urls.py
  docker-compose.yml
  mathesar/views.py
  mathesar_ui/src/pages/ErrorPage.svelte
  mathesar_ui/src/routes/RootRoute.svelte
Labels: status: review

#2549 Style Docs
  docs/docs/assets/images/header.png
  docs/docs/assets/images/logo.svg
  docs/docs/installation/docker-compose.md
  docs/docs/stylesheets/extra.css
  docs/mkdocs.yml
Labels: status: review

#2536 README updates
  README.md
  docs/docs/contributing/local-dev.md
  docs/mkdocs.yml
Labels: status: review

#2562 Collectstatic and allowed_hosts bugfixes
  .env.example
  install.py
  install.sh
Labels: status: review

#2453 Password change and reset throw 400
  mathesar/api/exceptions/mixins.py
  mathesar/api/ui/serializers/users.py
Labels: status: review

#2560 Change text 'role' to 'userType', 'user' role to 'standard'
  mathesar_ui/src/icons/index.ts
  mathesar_ui/src/pages/admin-users/UserRow.svelte
  mathesar_ui/src/systems/users-and-permissions/SelectRole.svelte
  mathesar_ui/src/systems/users-and-permissions/SelectUserType.svelte
  mathesar_ui/src/systems/users-and-permissions/UserDetailsForm.svelte
  mathesar_ui/src/systems/users-and-permissions/index.ts
  mathesar_ui/src/systems/users-and-permissions/utils.ts
Labels: status: review

#2558 Improve live demo banner
  mathesar_ui/src/components/LiveDemoBanner.svelte
  mathesar_ui/src/icons/index.ts
  mathesar_ui/src/layouts/LayoutWithHeader.svelte
Labels: status: review

#2568 Support external IP connectivity
  install.sh
Labels: status: review

#2552 Add Deployment type 2
  docs/docs/installation/docker-compose.md
  install.sh
Labels: status: review

#2574 install.sh usability fixes
  docker-compose.yml
  install.sh
  requirements.txt
Labels: status: review

#2567 Some arxiv dataset fixes, data preloading
  demo/install/arxiv_skeleton.py
  demo/install/base.py
  demo/install/datasets.py
  demo/install/resources/arxiv_papers.pickle
  demo/management/commands/download_and_pickle_some_arxiv_data.py
  demo/management/commands/load_arxiv_data.py
Labels: status: review

#2577 Wait on server readiness after upgrade to reload page
  mathesar_ui/src/api/databases.ts
  mathesar_ui/src/pages/admin-update/upgrade-modal/UpgradeModal.svelte
  mathesar_ui/src/stores/databases.ts
Labels: status: review

#2580 Reduce redundant django model updates
  mathesar/state/django.py
Labels: status: review

#2573 Updates to install script text
  install.sh
Labels: status: review

#2583 Minor fixes for `install.sh`
  db/install.py
  install.sh
  run.sh
Labels: status: review

#2389 Fixed placeholder selection bug
  mathesar_ui/src/components/sheet/SheetSelection.ts
Labels: status: review

#2575 Reduce redundant reflection
  demo/management/commands/clean_stale_db.py
  demo/middleware.py
  mathesar/state/django.py
Labels: work: backend, status: review

#2594 More installation fixes
  db/engine.py
  docker-compose.yml
  docs/docs/installation/docker-compose.md
  install.sh
Labels: status: review

#2600 Sync master to develop
  db/engine.py
  db/install.py
  demo/management/commands/clean_stale_db.py
  demo/middleware.py
  docker-compose.yml
  docs/docs/installation/docker-compose.md
  install.sh
  mathesar/state/django.py
  run.sh
Labels: status: waiting

#2597 Add manual reflection button
  mathesar_ui/src/api/reflect.ts
  mathesar_ui/src/pages/database/DatabasePage.svelte
Labels: status: review
