Repository mathesar-foundation/mathesar, pull requests merged in 2023-12, with the labels that each got.

#3326 Db Connections page and Welcome page
  mathesar/urls.py
  mathesar/views.py
  mathesar_ui/src/App.svelte
  mathesar_ui/src/AppTypes.ts
  mathesar_ui/src/api/connections.ts
  mathesar_ui/src/api/databases.ts
  mathesar_ui/src/component-library/common/styles/variables.scss
  mathesar_ui/src/component-library/icon/Icon.svelte
  mathesar_ui/src/component-library/icon/__meta__/Icon.test.ts
  mathesar_ui/src/component-library/tutorial/Tutorial.svelte
  mathesar_ui/src/components/AppHeader.svelte
  mathesar_ui/src/components/DocsLink.svelte
  mathesar_ui/src/components/EntityContainerWithFilterBar.svelte
  mathesar_ui/src/components/breadcrumb/Breadcrumb.svelte
  mathesar_ui/src/components/breadcrumb/BreadcrumbItem.svelte
  mathesar_ui/src/components/breadcrumb/BreadcrumbSelector.svelte
  mathesar_ui/src/components/breadcrumb/DatabaseSelector.svelte
  mathesar_ui/src/components/breadcrumb/breadcrumbTypes.ts
  mathesar_ui/src/components/form/FieldLayout.svelte
  mathesar_ui/src/components/form/validators.ts
  mathesar_ui/src/i18n/languages/en/dict.json
  mathesar_ui/src/icons/index.ts
  mathesar_ui/src/pages/WelcomePage.svelte
  mathesar_ui/src/pages/admin-update/upgrade-modal/UpgradeModal.svelte
  mathesar_ui/src/pages/admin-users/AdminNavigation.svelte
  mathesar_ui/src/pages/admin-users/UserListingPage.svelte
  mathesar_ui/src/pages/admin-users/UserRow.svelte
  mathesar_ui/src/pages/connections/ConnectionRow.svelte
  mathesar_ui/src/pages/connections/ConnectionsPage.svelte
  mathesar_ui/src/pages/database-connection/AddDatabaseConnection.svelte
  mathesar_ui/src/pages/database-connection/DatabaseConnectionForm.svelte
  mathesar_ui/src/pages/database-connection/DatabaseConnectionItem.svelte
  mathesar_ui/src/pages/database-connection/DatabaseConnectionSkeleton.svelte
  mathesar_ui/src/pages/database-connection/DatabaseConnectionsList.svelte
  mathesar_ui/src/pages/database-connection/EditDatabaseConnection.svelte
  mathesar_ui/src/pages/database/DatabaseDetails.svelte
  mathesar_ui/src/pages/database/DatabaseNavigationList.svelte
  mathesar_ui/src/pages/database/DatabasePage.svelte
  mathesar_ui/src/pages/database/DeleteDatabaseConnectionConfirmationModal.svelte
  mathesar_ui/src/pages/database/NoDatabaseFound.svelte
  mathesar_ui/src/pages/schema/SchemaPage.svelte
  mathesar_ui/src/routes/AdminRoute.svelte
  mathesar_ui/src/routes/AuthenticatedRoutes.svelte
  mathesar_ui/src/routes/DatabaseConnectionRoute.svelte
  mathesar_ui/src/routes/DatabaseRoute.svelte
  mathesar_ui/src/routes/urls.ts
  mathesar_ui/src/stores/databases.ts
  mathesar_ui/src/stores/schemas.ts
  mathesar_ui/src/systems/connections/AddConnectionModal.svelte
  mathesar_ui/src/systems/connections/ConnectionsEmptyState.svelte
  mathesar_ui/src/systems/connections/DeleteConnectionModal.svelte
  mathesar_ui/src/systems/connections/EditConnectionModal.svelte
  mathesar_ui/src/systems/connections/index.ts
  mathesar_ui/src/utils/preloadData.ts
Labels: status: review

#3200 added: exclusion violation custom error
  mathesar/api/exceptions/database_exceptions/exceptions.py
  mathesar/api/serializers/records.py
  mathesar/tests/api/test_record_api.py
  mathesar/tests/conftest.py
Labels: status: waiting

#3336 Prepare GitHub actions for new labeling scheme
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/actions/project_update/project_update.py
  .github/actions/project_update/requirements.txt
  .github/sync.yml
  .github/workflows/add-to-project.yml
  .github/workflows/test-and-lint-code.yml
  .github/workflows/update-project-on-issue-close.yml
  .github/workflows/update-project-on-issue-edit.yml
  .github/workflows/update-project-on-issue-label.yml
  .github/workflows/update-project-on-pr-edit.yml
  .github/workflows/update-project-on-pr-label.yml
Labels: pr-status: review

#3334 Replace eslint-plugin-svelte3 with officially supported eslint-plugin-svelte plugin
  mathesar_ui/.eslintrc.cjs
  mathesar_ui/package-lock.json
  mathesar_ui/package.json
  mathesar_ui/src/component-library/checkbox-group/CheckboxGroup.svelte
  mathesar_ui/src/component-library/dropdown/Dropdown.svelte
  mathesar_ui/src/component-library/radio-group/RadioGroup.svelte
  mathesar_ui/src/component-library/toast/ToastItem.svelte
  mathesar_ui/src/components/EditableTextWithActions.svelte
  mathesar_ui/src/components/NameWithIcon.svelte
  mathesar_ui/src/components/RecordSummary.svelte
  mathesar_ui/src/components/abstract-type-control/AbstractTypeDBOptions.svelte
  mathesar_ui/src/components/abstract-type-control/AbstractTypeDisplayOptions.svelte
  mathesar_ui/src/components/rich-text/RichText.svelte
  mathesar_ui/src/components/sheet/SheetVirtualRows.svelte
  mathesar_ui/src/pages/import/preview/ImportPreviewSheet.svelte
  mathesar_ui/src/pages/schema/CreateNewExplorationTutorial.svelte
  mathesar_ui/src/pages/schema/TableSkeleton.svelte
  mathesar_ui/src/routes/RootRoute.svelte
  mathesar_ui/src/systems/data-explorer/result-pane/QueryRunErrors.svelte
  mathesar_ui/src/systems/data-explorer/result-pane/Results.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorTable.svelte
  mathesar_ui/src/systems/table-view/Body.svelte
  mathesar_ui/src/systems/table-view/StatusPane.svelte
  mathesar_ui/src/systems/table-view/constraints/ForeignKeyConstraintDetails.svelte
  mathesar_ui/src/systems/table-view/header/drag-and-drop/Droppable.svelte
  mathesar_ui/src/systems/table-view/header/header-cell/HeaderCell.svelte
  mathesar_ui/src/systems/table-view/link-table/LinkTableForm.svelte
  mathesar_ui/src/systems/table-view/row/Row.svelte
  mathesar_ui/src/systems/table-view/row/RowControl.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/TableDeleteConfirmationBody.svelte
Labels: pr-status: review

#3337 Translate /src/components, add linting and formatting rules
  mathesar_ui/.eslintrc.cjs
  mathesar_ui/.prettierignore
  mathesar_ui/.prettierrc
  mathesar_ui/package-lock.json
  mathesar_ui/package.json
  mathesar_ui/src/api/types/queries.ts
  mathesar_ui/src/component-library/button/Button.scss
  mathesar_ui/src/component-library/common/utils/typeUtils.ts
  mathesar_ui/src/component-library/date-time-picker/DateTimePicker.scss
  mathesar_ui/src/component-library/dropdown/Dropdown.scss
  mathesar_ui/src/component-library/toast/ToastItem.scss
  mathesar_ui/src/components/AppHeader.svelte
  mathesar_ui/src/components/EditTableHOC.svelte
  mathesar_ui/src/components/EditableTextWithActions.svelte
  mathesar_ui/src/components/LinkedRecord.svelte
  mathesar_ui/src/components/LiveDemoBanner.svelte
  mathesar_ui/src/components/ModificationStatus.svelte
  mathesar_ui/src/components/NameAndDescInputModalForm.svelte
  mathesar_ui/src/components/OnPageFilterBar.svelte
  mathesar_ui/src/components/RecordPageLink.svelte
  mathesar_ui/src/components/RefreshButton.svelte
  mathesar_ui/src/components/abstract-type-control/AbstractTypeControl.svelte
  mathesar_ui/src/components/abstract-type-control/AbstractTypeSelector.svelte
  mathesar_ui/src/components/abstract-type-control/DbTypeIndicator.svelte
  mathesar_ui/src/components/abstract-type-control/config-components/DurationConfiguration.svelte
  mathesar_ui/src/components/breadcrumb/BreadcrumbSelector.svelte
  mathesar_ui/src/components/breadcrumb/EntitySelector.svelte
  mathesar_ui/src/components/breadcrumb/LogoAndNameWithLink.svelte
  mathesar_ui/src/components/breadcrumb/SchemaSelector.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/date-time/Presets.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LinkedRecordCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LinkedRecordInput.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/primary-key/PrimaryKeyCell.svelte
  mathesar_ui/src/components/form/form.ts
  mathesar_ui/src/components/form/validators.ts
  mathesar_ui/src/components/group-entry/GroupEntry.svelte
  mathesar_ui/src/components/sort-entry/SortEntry.svelte
  mathesar_ui/src/components/sort-entry/utils.ts
  mathesar_ui/src/i18n/languages/en/dict.json
  mathesar_ui/src/stores/abstract-types/types.ts
  mathesar_ui/src/systems/data-explorer/utils.ts
  mathesar_ui/tsconfig.json
  mathesar_ui/vite.config.js
  mathesar_ui/vitest-setup.config.ts
Labels: pr-status: review

#3316 Added drag functionality to update precendence for sort condition
  mathesar_ui/src/components/sortable/README.md
  mathesar_ui/src/components/sortable/sortable.css
  mathesar_ui/src/components/sortable/sortable.ts
  mathesar_ui/src/icons/index.ts
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/sort/Sort.svelte
Labels: pr-status: review

#3343 [Bugfix:API] Fix DatetimeFieldOverflow error handling
  mathesar/api/db/viewsets/records.py
  mathesar/tests/api/test_record_api.py
Labels: pr-status: revision

#3349 filter and create schemas using connection_id
  mathesar/api/db/viewsets/schemas.py
  mathesar/api/serializers/schemas.py
  mathesar/tests/api/test_schema_api.py
  mathesar/utils/schemas.py
Labels: pr-status: review

#3353 Fix: Make prettier work on Svelte files
  mathesar_ui/.prettierrc
  mathesar_ui/src/components/cell-fabric/data-types/components/CellWrapper.svelte
  mathesar_ui/src/components/sortable/README.md
  mathesar_ui/src/systems/data-explorer/exploration-inspector/ExplorationInspector.svelte
  mathesar_ui/src/systems/table-view/header/header-cell/HeaderCell.svelte
  mathesar_ui/src/systems/table-view/row/CellErrors.svelte
  mathesar_ui/src/systems/table-view/row/Row.svelte
Labels: pr-status: review

#3341 Use connection ids instead of names
  mathesar/urls.py
  mathesar/views.py
  mathesar_ui/src/api/connections.ts
  mathesar_ui/src/api/schemas.ts
  mathesar_ui/src/components/AppHeader.svelte
  mathesar_ui/src/components/breadcrumb/BreadcrumbItem.svelte
  mathesar_ui/src/components/breadcrumb/DatabaseSelector.svelte
  mathesar_ui/src/components/breadcrumb/EntitySelector.svelte
  mathesar_ui/src/components/breadcrumb/SchemaSelector.svelte
  mathesar_ui/src/pages/connections/ConnectionRow.svelte
  mathesar_ui/src/pages/data-explorer/DataExplorerPage.svelte
  mathesar_ui/src/pages/database/AddEditSchemaModal.svelte
  mathesar_ui/src/pages/database/DatabaseDetails.svelte
  mathesar_ui/src/pages/database/SchemaRow.svelte
  mathesar_ui/src/pages/exploration/ExplorationPage.svelte
  mathesar_ui/src/pages/exploration/Header.svelte
  mathesar_ui/src/pages/import/preview/ImportPreviewContent.svelte
  mathesar_ui/src/pages/import/preview/ImportPreviewPage.svelte
  mathesar_ui/src/pages/import/upload/ImportUploadPage.svelte
  mathesar_ui/src/pages/schema/CreateEmptyTableButton.svelte
  mathesar_ui/src/pages/schema/CreateNewExplorationTutorial.svelte
  mathesar_ui/src/pages/schema/CreateNewTableButton.svelte
  mathesar_ui/src/pages/schema/CreateNewTableTutorial.svelte
  mathesar_ui/src/pages/schema/ExplorationItem.svelte
  mathesar_ui/src/pages/schema/SchemaExplorations.svelte
  mathesar_ui/src/pages/schema/SchemaOverview.svelte
  mathesar_ui/src/pages/schema/SchemaPage.svelte
  mathesar_ui/src/pages/schema/TableCard.svelte
  mathesar_ui/src/routes/AuthenticatedRoutes.svelte
  mathesar_ui/src/routes/DataExplorerRoute.svelte
  mathesar_ui/src/routes/DatabaseRoute.svelte
  mathesar_ui/src/routes/ImportRoute.svelte
  mathesar_ui/src/routes/urls.ts
  mathesar_ui/src/stores/abstract-types/store.ts
  mathesar_ui/src/stores/databases.ts
  mathesar_ui/src/stores/schemas.ts
  mathesar_ui/src/stores/storeBasedUrls.ts
  mathesar_ui/src/systems/data-explorer/result-pane/QueryRunErrors.svelte
  mathesar_ui/src/systems/data-explorer/urlSerializationUtils.ts
  mathesar_ui/src/systems/table-view/table-inspector/table/TableActions.svelte
  mathesar_ui/src/utils/preloadData.ts
  mathesar_ui/src/utils/tables.ts
Labels: pr-status: review

#3321 Django i18n and instructions
  .gitignore
  .tx/config
  .tx/integration.yml
  DEVELOPER_GUIDE.md
  config/settings/common_settings.py
  mathesar/templates/mathesar/login_base.html
  mathesar/templates/registration/login.html
  mathesar/templates/registration/superuser_create.html
  mathesar/templates/users/password_reset_confirmation.html
  translations/en/LC_MESSAGES/django.po
  translations/ja/LC_MESSAGES/django.po
Labels: pr-status: review

#3352 Allow editing connection nicknames
  mathesar_ui/src/api/connections.ts
  mathesar_ui/src/systems/connections/EditConnectionModal.svelte
Labels: pr-status: review

#3313 Added Focus styles to Schema Row, Table Row and Buttons.
  mathesar_ui/src/component-library/button/Button.scss
  mathesar_ui/src/component-library/dropdown/Dropdown.scss
  mathesar_ui/src/pages/database/SchemaRow.svelte
  mathesar_ui/src/pages/schema/TableCard.svelte
Labels: pr-status: review

#3348 Add connections rpc endpoints
  db/install.py
  db/sql/0_msar.sql
  db/sql/test_0_msar.sql
  demo/install/datasets.py
  mathesar/api/exceptions/error_codes.py
  mathesar/api/exceptions/validation_exceptions/exceptions.py
  mathesar/api/ui/permissions/ui_database.py
  mathesar/api/ui/viewsets/databases.py
  mathesar/install.py
  mathesar/models/base.py
  mathesar/utils/connections.py
  mathesar/views.py
Labels: pr-status: review

#3368 Extract sample data loaders for dependency reasons
  demo/install/datasets.py
  demo/install/library_dataset.py
  demo/install/movies_dataset.py
  mathesar/utils/connections.py
Labels: pr-status: review
