Repository mathesar-foundation/mathesar, pull requests merged in 2023-09, with the labels that each got.

#3012 Fix URL cell focus loss when clicking on its contained hyperlink
  mathesar_ui/src/components/cell-fabric/data-types/components/uri/UriCellContent.svelte
Labels: status: review

#3195 Add `sheet_index` param in datafile API to handle excel files with multiple sheets
  mathesar/api/serializers/data_files.py
  mathesar/imports/excel.py
  mathesar/migrations/0005_datafile_sheet_name.py
  mathesar/migrations/0006_auto_20230906_0413.py
  mathesar/models/base.py
  mathesar/tests/api/test_table_api.py
  mathesar/tests/conftest.py
  mathesar/tests/data/excel_parsing/multiple_sheets.xlsx
  mathesar/utils/datafiles.py
Labels: work: backend

#3117 Remove db superuser requirement
  db/install.py
  docs/docs/installation/build-from-source/index.md
  docs/docs/installation/docker/index.md
  docs/docs/snippets/docker-compose-prerequisites.md
Labels: status: waiting

#3186 Comments for columns, backend impl.
  db/columns/defaults.py
  db/columns/operations/alter.py
  db/columns/operations/create.py
  db/columns/operations/select.py
  db/sql/0_msar.sql
  db/sql/test_0_msar.sql
  mathesar/api/db/viewsets/columns.py
  mathesar/api/serializers/columns.py
  mathesar/models/base.py
  mathesar/tests/api/test_column_api.py
Labels: work: backend, status: review

#3146 3145 add openapi specification for /tables/ endpoint
  config/settings/openapi.py
  schema.yml
Labels: type: enhancement, work: backend, status: draft

#3206 Postgres basic compatibility versions 13, 14, 15
  .github/workflows/run-pytest.yml
  .github/workflows/run-sql-tests.yml
  Dockerfile.devdb
  db/sql/test_0_msar.sql
  docker-compose.dev.yml
  docker-compose.yml
  mathesar/tests/api/query/test_aggregation_functions.py
  mathesar/tests/api/test_column_api.py
Labels: status: review

#3203 Migrate django_db to sqlite
  config/settings/common_settings.py
  docker-compose.dev.yml
  docker-compose.yml
  mathesar/api/serializers/table_settings.py
  mathesar/migrations/0007_auto_20230913_1912.py
  mathesar/models/base.py
  setup.cfg
Labels: status: review

#3189 Add script for creating debian package
  DEVELOPER_GUIDE.md
  MANIFEST.in
  config/settings/common_settings.py
  db/functions/operations/__init__.py
  db/sql/__init__.py
  db/types/base.py
  db/utils.py
  dev-run.sh
  docs/docs/installation/build-from-source/index.md
  mathesar/api/display_options.py
  mathesar/data/__init__.py
  mathesar/data/currency_info.json
  mathesar/database/types.py
  mathesar/filters/__init__.py
  mathesar/install.py
  mathesar/start.py
  mathesar/utils/display_options_inference.py
  pyproject.toml
  release-scripts/__init__.py
  release-scripts/build-debian.sh
  release-scripts/debian/build_virtualenv
  release-scripts/debian/changelog
  release-scripts/debian/control
  release-scripts/debian/mathesar.postinst
  release-scripts/debian/mathesar.service
  release-scripts/debian/rules
  run.sh
Labels: status: waiting

#3121 Add Postgres to Mathesar docker image
  .github/workflows/run-pytest.yml
  Dockerfile
  config/settings/common_settings.py
  db-run.sh
  db/install.py
  dev-run.sh
  docs/docs/index.md
  docs/docs/installation/docker/index.md
  docs/mkdocs.yml
  run.sh
  setup.cfg
Labels: status: review

#3212 Update Docker installation instructions based on the updated installation plan
  docs/docs/configuration/env-variables.md
  docs/docs/installation/docker/index.md
  docs/docs/user-guide/glossary.md
  docs/mkdocs.yml
Labels: status: review

#3219 Add description to column properties, frontend impl.
  mathesar_ui/src/api/types/tables/columns.ts
  mathesar_ui/src/stores/table-data/columns.ts
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnMode.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnNameAndDescription.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnOptions.svelte
Labels: status: review

#3214 Upgrade node version, remove Storybook
  .dockerignore
  .github/workflows/run-lint-audit-tests-ui.yml
  .gitignore
  Dockerfile
  Dockerfile.integ-tests
  docs/docs/installation/build-from-source/index.md
  mathesar_ui/.eslintrc.cjs
  mathesar_ui/.nvmrc
  mathesar_ui/.prettierignore
  mathesar_ui/.storybook/main.js
  mathesar_ui/.storybook/preview.js
  mathesar_ui/ARCHITECTURE.md
  mathesar_ui/README.md
  mathesar_ui/package-lock.json
  mathesar_ui/package.json
  mathesar_ui/src/component-library/README.md
  mathesar_ui/tsconfig.json
Labels: status: waiting
