Repository mathesar-foundation/mathesar, pull requests merged in 2023-07, with the labels that each got.

#2978 Column creation and duplication DDL 2
  db/columns/operations/create.py
  db/sql/0_msar.sql
  db/sql/test_0_msar.sql
  db/tests/columns/operations/test_create.py
  db/tests/dependents/test_dependents.py
  mathesar/api/db/viewsets/columns.py
  mathesar/tests/api/test_column_api.py
  mathesar/tests/conftest.py
Labels: status: review

#2996 Update demo's documentation
  demo/README.md
Labels: work: documentation, affects: dx, status: review

#2968 Added pandas and JSON normalization code
  db/records/operations/insert.py
  mathesar/api/exceptions/database_exceptions/exceptions.py
  mathesar/api/exceptions/error_codes.py
  mathesar/imports/json.py
  mathesar/tests/data/json_parsing/missing_keys.json
  mathesar/utils/datafiles.py
  requirements.txt
Labels: status: waiting

#2992 Added documentation for importing data into tables
  docs/docs/user-guide/importing-data.md
Labels: work: documentation, status: review

#2977 Added api tests for importing JSON feature
  mathesar/tests/api/test_data_file_api.py
  mathesar/tests/api/test_table_api.py
Labels: status: review

#2976 Cleaner consolidated logic for adding constraints
  db/constraints/base.py
  db/constraints/operations/create.py
  db/tests/constraints/operations/test_drop.py
  db/tests/dependents/test_dependents.py
  mathesar/models/base.py
Labels: status: waiting

#2993 Remove lazydict dependency
  mathesar/api/display_options.py
  requirements.txt
Labels: status: review

#2985 Updated frontend to send a single bulk delete request instead of one request for each record
  mathesar_ui/src/api/utils/requestUtils.ts
  mathesar_ui/src/stores/table-data/records.ts
Labels: status: review

#3014 Added margin between breadcrumb selector and bottom of the veiwport
  mathesar_ui/src/components/breadcrumb/BreadcrumbSelector.svelte
Labels: status: waiting

#2981 Add `Peak Time` aggregation function.
  db/functions/base.py
  db/sql/3_msar_custom_aggregates.sql
  db/sql/install.py
  mathesar/models/query.py
  mathesar/tests/api/query/test_aggregation_functions.py
  mathesar_ui/src/api/types/queries.ts
  mathesar_ui/src/stores/abstract-types/operations/summarization.ts
Labels: status: review

#3008 Extended import via copy-paste for JSON and updated UI
  mathesar/imports/json.py
  mathesar/utils/datafiles.py
  mathesar_ui/src/pages/import-upload/UploadViaClipboard.svelte
  mathesar_ui/src/pages/import-upload/UploadViaFile.svelte
  mathesar_ui/src/pages/import-upload/UploadViaUrl.svelte
Labels: status: waiting

#3038 Date Input closes now on tab
  mathesar_ui/src/components/cell-fabric/data-types/components/date-time/DateTimeInput.svelte
Labels: status: review

#3042 Clean up import docs
  docs/docs/user-guide/importing-data.md
  docs/mkdocs.yml
  mathesar/imports/base.py
  mathesar/imports/csv.py
Labels: status: waiting

#3045 Scroll sheet all the way down when clicking the New Record button
  mathesar_ui/src/components/sheet/SheetVirtualRows.svelte
Labels: status: review

#3039 Added `max_level` param for JSON import feature in the backend
  db/records/operations/insert.py
  mathesar/api/serializers/data_files.py
  mathesar/imports/json.py
  mathesar/migrations/0003_datafile_max_level.py
  mathesar/models/base.py
  mathesar/tests/api/test_table_api.py
  mathesar/tests/data/json_parsing/nested_objects.json
  mathesar/utils/datafiles.py
Labels: status: review

#2986 SQL for links creation
  db/links/operations/create.py
  db/sql/0_msar.sql
  db/sql/test_0_msar.sql
  db/sql/test_startup.sql
  db/tables/operations/split.py
  mathesar/api/serializers/links.py
Labels: status: review

#2975 Auto-focus input when editing number/money cells
  mathesar_ui/src/components/cell-fabric/data-types/components/money/MoneyCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/number/NumberCell.svelte
Labels: status: review

#2989 Improve cell focus behavior
  mathesar_ui/src/components/cell-fabric/data-types/components/CellWrapper.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LinkedRecordCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/primary-key/PrimaryKeyCell.svelte
Labels: status: review

#3029 Update build from source documentation
  docs/docs/installation/build-from-source/index.md
Labels: status: review

#3086 Help text: "its linked tables" (possessive adjective)
  mathesar_ui/src/systems/data-explorer/input-sidebar/InputSidebar.svelte
Labels: status: review

#3021 Improved the operationIds by implementing a post hook function
  config/settings/common_settings.py
  config/settings/openapi.py
Labels: type: enhancement, work: backend, status: waiting

#3082 Add SQL files to the pytest workflow
  .github/workflows/run-pytest.yml
Labels: affects: dx, status: started

#3006 Add `Peak Month` aggregation function.
  db/functions/base.py
  db/sql/3_msar_custom_aggregates.sql
  mathesar/models/query.py
  mathesar/tests/api/query/test_aggregation_functions.py
  mathesar_ui/src/api/types/queries.ts
  mathesar_ui/src/stores/abstract-types/operations/summarization.ts
Labels: status: review

#3077 Use Truncate component in Record Selector table cells
  mathesar_ui/src/component-library/truncate/Truncate.scss
  mathesar_ui/src/components/cell-fabric/CellFabric.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/SteppedInputCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/date-time/DateTimeCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/formatted-input/FormattedInputCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/money/MoneyCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/number/NumberCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/textarea/TextAreaCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/textbox/TextBoxCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/typeDefinitions.ts
  mathesar_ui/src/components/cell-fabric/data-types/components/uri/UriCell.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorCellWrapper.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorDataCell.svelte
Labels: status: review

#2751 Update README.md with troubleshooting instructions
  README.md
  TROUBLESHOOTING.md
Labels: affects: dx, affects: ux, status: review

#3040 Support unknown types (backend)
  db/columns/base.py
  db/records/operations/sort.py
  db/tests/columns/test_base.py
  db/types/base.py
  db/types/operations/convert.py
  mathesar/api/db/viewsets/records.py
  mathesar/tests/api/conftest.py
  mathesar/tests/api/test_column_api.py
  mathesar/tests/api/test_record_api.py
  mathesar/tests/conftest.py
Labels: affects: ux, work: backend, status: review

#3025 Add API tests for multi-column primary key constraints
  mathesar/api/serializers/constraints.py
  mathesar/tests/api/test_constraint_api.py
Labels: status: waiting

#3094 Copy formatted cell values to clipboard instead of raw values
  mathesar_ui/.eslintrc.cjs
  mathesar_ui/src/components/sheet/SheetClipboardHandler.ts
Labels: status: review

#3092 Shareable links backend - Models, APIs, bypass auth for table requests
  mathesar/admin.py
  mathesar/api/db/permissions/columns.py
  mathesar/api/db/permissions/constraint.py
  mathesar/api/db/permissions/records.py
  mathesar/api/db/permissions/table.py
  mathesar/api/db/viewsets/columns.py
  mathesar/api/db/viewsets/constraints.py
  mathesar/api/db/viewsets/records.py
  mathesar/api/db/viewsets/tables.py
  mathesar/api/exceptions/error_codes.py
  mathesar/api/permission_conditions.py
  mathesar/api/permission_utils.py
  mathesar/api/ui/permissions/shares.py
  mathesar/api/ui/serializers/shares.py
  mathesar/api/ui/viewsets/__init__.py
  mathesar/api/ui/viewsets/shares.py
  mathesar/api/utils.py
  mathesar/migrations/0004_shares.py
  mathesar/models/shares.py
  mathesar/tests/api/test_column_api.py
  mathesar/tests/api/test_constraint_api.py
  mathesar/urls.py
  mathesar/views.py
Labels: status: review

#3093 Shareable links frontend - shared table consumer view
  mathesar_ui/src/App.svelte
  mathesar_ui/src/api/utils/requestUtils.ts
  mathesar_ui/src/components/AppHeader.svelte
  mathesar_ui/src/components/EditableTextWithActions.svelte
  mathesar_ui/src/components/routing/EventfulRoute.svelte
  mathesar_ui/src/components/routing/RouteObserver.svelte
  mathesar_ui/src/pages/table/TablePage.svelte
  mathesar_ui/src/routes/AnonymousAccessRoutes.svelte
  mathesar_ui/src/routes/AuthenticatedRoutes.svelte
  mathesar_ui/src/routes/RootRoute.svelte
  mathesar_ui/src/routes/SharedTableRoute.svelte
  mathesar_ui/src/stores/table-data/TableStructure.ts
  mathesar_ui/src/stores/table-data/columns.ts
  mathesar_ui/src/stores/table-data/constraints.ts
  mathesar_ui/src/stores/table-data/records.ts
  mathesar_ui/src/stores/table-data/tabularData.ts
  mathesar_ui/src/stores/userProfile.ts
  mathesar_ui/src/stores/users.ts
  mathesar_ui/src/systems/table-view/StatusPane.svelte
  mathesar_ui/src/systems/table-view/TableView.svelte
  mathesar_ui/src/systems/table-view/actions-pane/ActionsPane.svelte
  mathesar_ui/src/systems/table-view/link-table/LinkTableForm.svelte
  mathesar_ui/src/systems/table-view/table-inspector/WithTableInspector.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/TableDescription.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/TableMode.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/TableName.svelte
  mathesar_ui/src/utils/preloadData.ts
  mathesar_ui/src/utils/shares.ts
Labels: status: waiting

#3107 Remove `pglast`, use SQL function instead
  db/columns/operations/select.py
  db/tests/columns/operations/test_select.py
  db/tests/columns/utils.py
  requirements.txt
Labels: priority: urgent, status: review

#3098 SQL tests for schema ddl
  db/sql/test_0_msar.sql
  db/tests/schemas/operations/test_alter.py
  db/tests/schemas/operations/test_create.py
  db/tests/schemas/operations/test_drop.py
  db/tests/schemas/utils.py
Labels: status: review

#3106 Fix the error when `list aggregation` on mathesar custom array
  conftest.py
  db/tests/resources/player_profiles.sql
  db/types/custom/json_array.py
  mathesar/tests/api/conftest.py
  mathesar/tests/api/query/test_aggregation_functions.py
Labels: status: review

#3099 [i18n] Install typesafe-i18n & translates one component
  mathesar_ui/.typesafe-i18n.json
  mathesar_ui/package-lock.json
  mathesar_ui/package.json
  mathesar_ui/src/App.svelte
  mathesar_ui/src/i18n/en/index.ts
  mathesar_ui/src/i18n/formatters.ts
  mathesar_ui/src/i18n/i18n-load.ts
  mathesar_ui/src/i18n/i18n-svelte.ts
  mathesar_ui/src/i18n/i18n-types.ts
  mathesar_ui/src/i18n/i18n-util.ts
  mathesar_ui/src/i18n/ja/index.ts
  mathesar_ui/src/pages/import-upload/ImportUploadPage.svelte
Labels: status: review
