Repository mathesar-foundation/mathesar, pull requests merged in 2023-11, with the labels that each got.

#3280 Remove mathesar-update-companion from repo workflows
  .github/sync.yml
  .github/workflows/sync-github-labels-milestones.yml
Labels: status: review

#3279 docs: fix install commands
  .github/workflows/deploy-docs.yml
  .github/workflows/test-docs.yml
  docs/docs/installation/build-from-source/index.md
Labels: status: review

#3298 Disable the stale issues bot
  .github/workflows/stale.yml.disabled
Labels: status: review

#3295 Structures Dockerfile based on operation, and simplifies dev environment
  Dockerfile
  docker-compose.dev.yml
Labels: status: review

#3300 Update command to point to dev DB
  DEVELOPER_GUIDE.md
Labels: status: review, status: waiting

#3299 Add metadata about internal db connection in common_data
  mathesar/api/db/viewsets/databases.py
  mathesar/api/exceptions/error_codes.py
  mathesar/api/exceptions/validation_exceptions/exceptions.py
  mathesar/api/serializers/databases.py
  mathesar/install.py
  mathesar/migrations/0010_remove_editable.py
  mathesar/models/base.py
  mathesar/views.py
Labels: status: review

#3303 Added overflow condition for TableView
  mathesar_ui/src/systems/table-view/TableView.svelte
Labels: status: review

#3090 Updated Django REST Framework settings to use JSONParser as the default parser for incoming requests
  config/settings/common_settings.py
  mathesar/api/db/viewsets/data_files.py
Labels: type: enhancement, work: backend, status: review

#3302 Replace typesafe-i18n with svelte-i18n
  config/context_processors.py
  mathesar/utils/frontend.py
  mathesar_ui/.eslintrc.cjs
  mathesar_ui/.typesafe-i18n.json
  mathesar_ui/package-lock.json
  mathesar_ui/package.json
  mathesar_ui/src/App.svelte
  mathesar_ui/src/api/users.ts
  mathesar_ui/src/components/breadcrumb/BreadcrumbSelector.svelte
  mathesar_ui/src/global.d.ts
  mathesar_ui/src/i18n/en/index.ts
  mathesar_ui/src/i18n/formatters.ts
  mathesar_ui/src/i18n/i18n-load.ts
  mathesar_ui/src/i18n/i18n-store.ts
  mathesar_ui/src/i18n/i18n-svelte.ts
  mathesar_ui/src/i18n/i18n-types.ts
  mathesar_ui/src/i18n/i18n-util.ts
  mathesar_ui/src/i18n/index.ts
  mathesar_ui/src/i18n/ja/index.ts
  mathesar_ui/src/i18n/languages/en/dict.json
  mathesar_ui/src/i18n/languages/en/index.ts
  mathesar_ui/src/i18n/languages/ja/dict.json
  mathesar_ui/src/i18n/languages/ja/index.ts
  mathesar_ui/src/i18n/languages/utils.ts
  mathesar_ui/src/pages/import/upload/ImportUploadPage.svelte
  mathesar_ui/src/stores/users.ts
  mathesar_ui/src/systems/table-view/link-table/LinkTypeOption.svelte
  mathesar_ui/src/systems/users-and-permissions/SelectDisplayLanguage.svelte
  mathesar_ui/src/systems/users-and-permissions/UserDetailsForm.svelte
  mathesar_ui/tsconfig.json
  mathesar_ui/vite.config.js
Labels: status: review

#3310 Set clear value as null
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LinkedRecordInput.svelte
Labels: status: review

#3317 Removed sqlalchemy-filters
  db/records/operations/relevance.py
  requirements.txt
Labels: status: review

#3325 Fixed formatting strings for timestampsWithTZ
  mathesar_ui/src/utils/date-time/DateTimeSpecification.ts
Labels: status: review
