Repository mathesar-foundation/mathesar, pull requests merged in 2023-01, with the labels that each got.

#2135 Setup mkdocs
  .github/workflows/deploy-docs.yml
  README.md
  docs/README.md
  docs/docs/index.md
  docs/mkdocs.yml
  requirements-dev.txt
Labels: work: documentation, status: review

#2103 Store Postgres data in a Docker volume
  docker-compose.yml
Labels: affects: dx, work: infrastructure, status: review

#2178 Add --force to mkdocs gh-deploy
  .github/workflows/deploy-docs.yml
Labels: work: documentation, affects: dx

#2183 Select entire row on row header click
  mathesar_ui/src/components/sheet/SheetSelection.ts
Labels: status: review

#2184 Hide edit schema button from public schema page
  mathesar_ui/src/pages/schema/SchemaPage.svelte
Labels: status: review

#2162 Clearing search value when closing the table selector in the nav header
  mathesar_ui/src/components/breadcrumb/BreadcrumbSelector.svelte
Labels: status: waiting

#2186 Forbid editing public schema
  mathesar/api/db/viewsets/schemas.py
  mathesar/api/exceptions/error_codes.py
  mathesar/api/exceptions/validation_exceptions/exceptions.py
Labels: work: backend, status: review

#2147 Use a URL query param instead of a hash to store the filtering/sorting/grouping/pagination
  mathesar_ui/src/pages/table/TablePage.svelte
Labels: status: review

#2146 Consistency Fixes
  mathesar_ui/src/App.svelte
  mathesar_ui/src/component-library/button/Button.scss
  mathesar_ui/src/component-library/collapsible/Collapsible.scss
  mathesar_ui/src/component-library/common/styles/variables.scss
  mathesar_ui/src/component-library/context-menu/__meta__/ContextMenu.stories.svelte
  mathesar_ui/src/component-library/date-time-picker/DateTimePicker.scss
  mathesar_ui/src/component-library/dropdown/Dropdown.scss
  mathesar_ui/src/component-library/form-builder/FormBuilder.scss
  mathesar_ui/src/component-library/input-group/InputGroup.scss
  mathesar_ui/src/component-library/multi-select/MultiSelect.scss
  mathesar_ui/src/component-library/multi-select/__meta__/Side.svelte
  mathesar_ui/src/component-library/tabs/TabContainer.scss
  mathesar_ui/src/component-library/tabs/TabContainer.svelte
  mathesar_ui/src/component-library/tutorial/Tutorial.scss
  mathesar_ui/src/component-library/window/Window.scss
  mathesar_ui/src/components/AppSecondaryHeader.svelte
  mathesar_ui/src/components/EditableTitle.svelte
  mathesar_ui/src/components/EntityPageHeader.svelte
  mathesar_ui/src/components/LinkedRecord.svelte
  mathesar_ui/src/components/Logo.svelte
  mathesar_ui/src/components/PageTitleAndMeta.svelte
  mathesar_ui/src/components/RecordPageLink.svelte
  mathesar_ui/src/components/SchemaName.svelte
  mathesar_ui/src/components/TypeIcon.svelte
  mathesar_ui/src/components/abstract-type-control/config-components/DurationConfiguration.svelte
  mathesar_ui/src/components/breadcrumb/BreadcrumbLink.svelte
  mathesar_ui/src/components/breadcrumb/BreadcrumbRecordSelector.svelte
  mathesar_ui/src/components/breadcrumb/BreadcrumbSelector.svelte
  mathesar_ui/src/components/breadcrumb/LogoAndNameWithLink.svelte
  mathesar_ui/src/components/cell-fabric/CellFabric.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/CellWrapper.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LinkedRecordInput.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/select/SingleSelectCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/uri/UriCellContent.svelte
  mathesar_ui/src/components/sheet/SheetCellResizer.svelte
  mathesar_ui/src/layouts/LayoutWithHeader.svelte
  mathesar_ui/src/pages/database/DatabasePage.svelte
  mathesar_ui/src/pages/database/SchemaConstituentCounts.svelte
  mathesar_ui/src/pages/database/SchemaRow.svelte
  mathesar_ui/src/pages/import-preview/ImportPreviewPage.svelte
  mathesar_ui/src/pages/import-upload/ImportUploadPage.svelte
  mathesar_ui/src/pages/record/RecordPageLoadingSpinner.svelte
  mathesar_ui/src/pages/record/TableWidget.svelte
  mathesar_ui/src/pages/record/Widgets.svelte
  mathesar_ui/src/pages/schema/CreateNewTableButton.svelte
  mathesar_ui/src/pages/schema/OverviewHeader.svelte
  mathesar_ui/src/pages/schema/SchemaPage.svelte
  mathesar_ui/src/pages/schema/TableItem.svelte
  mathesar_ui/src/pages/schema/TablesList.svelte
  mathesar_ui/src/systems/data-explorer/ActionsPane.svelte
  mathesar_ui/src/systems/data-explorer/DataExplorer.svelte
  mathesar_ui/src/systems/data-explorer/exploration-inspector/ExplorationInspector.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/InputSidebar.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/column-selection-pane/TableGroupCollapsible.svelte
  mathesar_ui/src/systems/data-explorer/result-pane/Results.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorCellWrapper.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorContent.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorTable.svelte
  mathesar_ui/src/systems/table-view/row/CellErrors.svelte
  mathesar_ui/src/systems/table-view/table-inspector/TableInspector.svelte
Labels: status: review

#2182 Have CI pytest task stop after first failed test
  .github/workflows/run-pytest.yml
Labels: type: enhancement, affects: dx, work: infrastructure, status: review

#2199 Use realistic library data for live demo
  demo/resources/library_add_checkouts.sql
  demo/resources/library_without_checkouts.sql
Labels: status: review

#2165 Default display_options for inferred/created mathesar_money column
  mathesar/api/serializers/columns.py
  mathesar/tests/api/test_column_api_display_options.py
Labels: status: review

#2201 Table descriptions support on the platform
  mathesar_ui/src/component-library/truncate/Truncate.scss
  mathesar_ui/src/components/EditTableHOC.svelte
  mathesar_ui/src/components/EditableTextWithActions.svelte
  mathesar_ui/src/components/TableNameAndDescription.svelte
  mathesar_ui/src/pages/schema/EditTable.svelte
  mathesar_ui/src/pages/schema/TableItem.svelte
  mathesar_ui/src/stores/tables.ts
  mathesar_ui/src/systems/table-view/actions-pane/ActionsPane.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/TableDescription.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/TableMode.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/TableName.svelte
  mathesar_ui/src/typeUtils.ts
Labels: status: review

#2219 Fix: missing edit button on schema page
  mathesar_ui/src/pages/schema/SchemaPage.svelte
Labels: status: review

#2172 Persist tab name in url for schema page
  mathesar_ui/src/component-library/tabs/Tab.svelte
  mathesar_ui/src/component-library/tabs/TabContainer.scss
  mathesar_ui/src/component-library/tabs/TabContainer.svelte
  mathesar_ui/src/component-library/tabs/TabContainerTypes.ts
  mathesar_ui/src/pages/schema/SchemaPage.svelte
  mathesar_ui/src/routes/urls.ts
Labels: status: waiting

#2216 DE & general fixes - 1
  mathesar/models/query.py
  mathesar/tests/api/query/test_library_demo_reports.py
  mathesar/tests/api/query/test_query_columns_api.py
  mathesar/tests/api/query/test_query_results.py
  mathesar/tests/api/query/test_query_run.py
  mathesar/tests/api/query/test_query_run_partial_transforms.py
  mathesar_ui/src/api/types/queries.ts
  mathesar_ui/src/components/EntityPageHeader.svelte
  mathesar_ui/src/components/TableNameAndDescription.svelte
  mathesar_ui/src/components/cell-fabric/CellFabric.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/CellWrapper.svelte
  mathesar_ui/src/geometry.ts
  mathesar_ui/src/pages/exploration/Header.svelte
  mathesar_ui/src/pages/schema/TableItem.svelte
  mathesar_ui/src/systems/data-explorer/ActionsPane.svelte
  mathesar_ui/src/systems/data-explorer/DataExplorer.svelte
  mathesar_ui/src/systems/data-explorer/exploration-inspector/column-tab/DeleteColumnAction.svelte
  mathesar_ui/src/systems/data-explorer/result-pane/Results.svelte
  mathesar_ui/src/systems/data-explorer/urlSerializationUtils.ts
  mathesar_ui/src/systems/data-explorer/utils.ts
  mathesar_ui/src/systems/table-view/actions-pane/ActionsPane.svelte
  mathesar_ui/src/systems/table-view/row/Row.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/TableActions.svelte
Labels: status: review

#2226 Row header context menu
  mathesar_ui/src/systems/table-view/row/Row.svelte
  mathesar_ui/src/systems/table-view/row/RowContextOptions.svelte
Labels: status: review

#2185 Record Selector styling
  mathesar_ui/src/App.svelte
  mathesar_ui/src/component-library/common/styles/variables.scss
  mathesar_ui/src/component-library/match-highlighter/Match.svelte
  mathesar_ui/src/component-library/match-highlighter/index.ts
  mathesar_ui/src/component-library/match-highlighter/matchHighlighterUtils.ts
  mathesar_ui/src/components/CellValue.svelte
  mathesar_ui/src/components/LinkedRecord.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/CellWrapper.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/SteppedInputCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/checkbox/CheckboxCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/date-time/DateTimeCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/linked-record/LinkedRecordCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/money/MoneyCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/number/NumberCell.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorCellWrapper.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorColumnHeaderCell.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorContent.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorInputCell.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorSubmitButton.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorTable.svelte
  mathesar_ui/src/systems/record-selector/RecordSelectorWindow.svelte
  mathesar_ui/src/systems/record-selector/recordSelectorUtils.ts
Labels: status: review

#2241 DE fixes - 2
  mathesar_ui/src/api/types/queries.ts
  mathesar_ui/src/component-library/input-group/InputGroup.scss
  mathesar_ui/src/component-library/multi-select/MultiSelect.svelte
  mathesar_ui/src/component-library/select/Select.svelte
  mathesar_ui/src/components/SelectSortDirection.svelte
  mathesar_ui/src/components/cell-fabric/data-types/boolean.ts
  mathesar_ui/src/components/cell-fabric/data-types/string.ts
  mathesar_ui/src/components/cell-fabric/data-types/typeDefinitions.ts
  mathesar_ui/src/components/cell-fabric/data-types/uri.ts
  mathesar_ui/src/components/cell-fabric/utils.ts
  mathesar_ui/src/components/filter-entry/utils.ts
  mathesar_ui/src/components/sort-entry/SortEntry.svelte
  mathesar_ui/src/components/sort-entry/utils.ts
  mathesar_ui/src/stores/abstract-types/index.ts
  mathesar_ui/src/stores/abstract-types/operations/filtering.ts
  mathesar_ui/src/stores/abstract-types/types.ts
  mathesar_ui/src/stores/table-data/index.ts
  mathesar_ui/src/stores/table-data/sorting.ts
  mathesar_ui/src/stores/table-data/tabularData.ts
  mathesar_ui/src/systems/data-explorer/QueryFilterTransformationModel.ts
  mathesar_ui/src/systems/data-explorer/QueryHideTransformationModel.ts
  mathesar_ui/src/systems/data-explorer/QueryManager.ts
  mathesar_ui/src/systems/data-explorer/QueryModel.ts
  mathesar_ui/src/systems/data-explorer/QuerySortTransformationModel.ts
  mathesar_ui/src/systems/data-explorer/QuerySummarizationTransformationModel.ts
  mathesar_ui/src/systems/data-explorer/input-sidebar/InputSidebar.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/transformations-pane/SortTransformation.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/transformations-pane/TransformationsPane.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/transformations-pane/transformationUtils.ts
  mathesar_ui/src/systems/data-explorer/utils.ts
  mathesar_ui/src/systems/table-view/actions-pane/ActionsPane.svelte
  mathesar_ui/src/systems/table-view/actions-pane/MiniActionsPane.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/sort/Sort.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/sort/SortDropdown.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/sort/SortEntry.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/types.ts
  mathesar_ui/src/systems/table-view/header/header-cell/HeaderCell.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnDisplayProperties.svelte
Labels: status: review

#2229 Fix reflection to correctly reflect Tables with no columns
  mathesar/models/base.py
  mathesar/state/django.py
  requirements.txt
Labels: status: review

#2239 Add Django management command to delete Stale demo Databases
  demo/clean_up/__init__.py
  demo/clean_up/management/__init__.py
  demo/clean_up/management/commands/__init__.py
  demo/clean_up/management/commands/clean_stale_db.py
  demo/settings.py
Labels: status: review

#2244 Improve demo loading time
  demo/__init__.py
  demo/apps.py
  demo/clean_up/management/commands/clean_stale_db.py
  demo/install.py
  demo/middleware.py
  demo/settings.py
Labels: status: waiting

#2247 Improve general loading time
  demo/middleware.py
  mathesar/api/db/viewsets/links.py
  mathesar/api/serializers/links.py
  mathesar/apps.py
  mathesar/imports/csv.py
  mathesar/models/base.py
  mathesar/state/base.py
  mathesar/state/django.py
  mathesar/utils/models.py
Labels: status: review

#2210 Add `tags` to .gitignore
  .gitignore
Labels: affects: dx

#2228 Fix DBQuery missing joins
  db/queries/base.py
  db/tests/queries/conftest.py
  db/tests/queries/test_base.py
  db/tests/queries/test_initial_relation.py
  db/tests/transforms/test_finish_specifying_summarization.py
  mathesar/models/query.py
Labels: type: bug, work: backend, status: review

#2251 DE fixes - 3
  mathesar_ui/src/component-library/badge/Badge.scss
  mathesar_ui/src/component-library/dropdown/AttachableDropdown.svelte
  mathesar_ui/src/component-library/dropdown/Dropdown.scss
  mathesar_ui/src/component-library/help/Help.scss
  mathesar_ui/src/component-library/help/Help.svelte
  mathesar_ui/src/component-library/index.ts
  mathesar_ui/src/component-library/styles.scss
  mathesar_ui/src/component-library/tooltip/Tooltip.scss
  mathesar_ui/src/component-library/tooltip/Tooltip.svelte
  mathesar_ui/src/component-library/tooltip/TooltipAction.ts
  mathesar_ui/src/pages/database/__help__/SchemasHelp.svelte
  mathesar_ui/src/systems/data-explorer/ActionsPane.svelte
  mathesar_ui/src/systems/data-explorer/QueryModel.ts
  mathesar_ui/src/systems/data-explorer/input-sidebar/column-selection-pane/ColumnSelectionPane.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/column-selection-pane/SelectableColumn.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/column-selection-pane/SelectableColumnTree.svelte
  mathesar_ui/src/systems/table-view/constraints/__help__/UniqueConstraintColumnsHelp.svelte
  mathesar_ui/src/systems/table-view/constraints/__help__/UniqueConstraintsHelp.svelte
  mathesar_ui/src/utils/languageUtils.ts
Labels: status: review

#2243 Improve "Delete Records" button text
  mathesar_ui/src/systems/table-view/table-inspector/record/RowActions.svelte
  mathesar_ui/src/utils/languageUtils.ts
Labels: status: review

#2227 Support self-referential links in Link Table form
  mathesar_ui/src/components/form/field.ts
  mathesar_ui/src/systems/table-view/link-table/LinkTableForm.svelte
  mathesar_ui/src/systems/table-view/link-table/LinkTypeOption.svelte
  mathesar_ui/src/systems/table-view/link-table/SelectLinkType.svelte
  mathesar_ui/src/systems/table-view/link-table/linkTableUtils.ts
  mathesar_ui/src/utils/__tests__/db.test.ts
  mathesar_ui/src/utils/columnUtils.ts
  mathesar_ui/src/utils/db.ts
Labels: status: review

#2257 Fix public schema icon and null record name in navbar
  mathesar_ui/src/components/NameWithIcon.svelte
  mathesar_ui/src/components/SchemaName.svelte
  mathesar_ui/src/components/breadcrumb/BreadcrumbItem.svelte
Labels: status: review

#2253 Fix transforms not being able to define ordering
  db/queries/base.py
  db/records/operations/select.py
  db/records/operations/sort.py
  db/tests/records/operations/test_sort.py
  db/tests/transforms/test_basic.py
  db/transforms/base.py
  db/transforms/operations/apply.py
  mathesar/models/base.py
Labels: work: backend, status: waiting

#2206 Redirect logged-in users to the homepage when they try to visit the login page
  config/settings.py
  mathesar/urls.py
Labels: status: review

#2240 Make table cards clickable
  mathesar_ui/src/component-library/truncate/Truncate.svelte
  mathesar_ui/src/icons/index.ts
  mathesar_ui/src/pages/database/SchemaRow.svelte
  mathesar_ui/src/pages/schema/TableCard.svelte
  mathesar_ui/src/pages/schema/TableItem.svelte
  mathesar_ui/src/pages/schema/TablesList.svelte
Labels: status: review

#2256 Show error message and provide recovery options when columns are no longer present in underlying table
  mathesar_ui/src/api/utils/errorCodes.ts
  mathesar_ui/src/api/utils/requestUtils.ts
  mathesar_ui/src/component-library/button/Button.scss
  mathesar_ui/src/components/message-boxes/ErrorBox.svelte
  mathesar_ui/src/pages/exploration/ExplorationPage.svelte
  mathesar_ui/src/pages/exploration/Header.svelte
  mathesar_ui/src/systems/data-explorer/DataExplorer.svelte
  mathesar_ui/src/systems/data-explorer/QueryHideTransformationModel.ts
  mathesar_ui/src/systems/data-explorer/QueryManager.ts
  mathesar_ui/src/systems/data-explorer/QueryModel.ts
  mathesar_ui/src/systems/data-explorer/QueryRunner.ts
  mathesar_ui/src/systems/data-explorer/QuerySortTransformationModel.ts
  mathesar_ui/src/systems/data-explorer/exploration-inspector/column-tab/DeleteColumnAction.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/InputSidebar.svelte
  mathesar_ui/src/systems/data-explorer/result-pane/QueryRunErrors.svelte
  mathesar_ui/src/systems/data-explorer/result-pane/ResultPane.svelte
  mathesar_ui/src/systems/data-explorer/result-pane/Results.svelte
  mathesar_ui/src/systems/data-explorer/utils.ts
Labels: status: review

#2306 Add arXiv management commands
  demo/arxiv_dataset/scripts/remove_arxiv_pairs_log.py
  demo/arxiv_skeleton.py
  demo/clean_up/management/commands/__init__.py
  demo/install.py
  demo/management/__init__.py
  demo/management/commands/__init__.py
  demo/management/commands/clean_stale_db.py
  demo/management/commands/load_arxiv_data.py
  demo/management/commands/remove_arxiv_pairs_log.py
  demo/middleware.py
  demo/resources/arxiv_dataset_setup.sql
  demo/settings.py
Labels: status: review

#2308 Table uniqueness bugfix
  mathesar/api/exceptions/database_exceptions/exceptions.py
  mathesar/models/base.py
  mathesar/models/query.py
  mathesar/utils/joins.py
Labels: status: review

#2254 Fix imperative breadcrumb logic
  mathesar_ui/src/components/breadcrumb/AppendBreadcrumb.svelte
Labels: status: review

#2315 Fix UIQuery uniqueness
  mathesar/api/exceptions/error_codes.py
  mathesar/api/exceptions/validation_exceptions/exceptions.py
  mathesar/api/serializers/queries.py
  mathesar/migrations/0013_auto_20230119_1303.py
  mathesar/models/query.py
Labels: type: bug, affects: ux, work: backend, status: review

#2208 Add Mathesar DevCon data set
  demo/install.py
  demo/resources/devcon_dataset.sql
Labels: status: review

#2320 Fix filter validation logic when checked using filter id
  mathesar_ui/src/stores/abstract-types/operations/filtering.ts
  mathesar_ui/src/stores/abstract-types/types.ts
Labels: status: review

#2317 Alter library dataset to use DROP ... CASCADE
  demo/install.py
Labels: status: review

#2249 Improve responsiveness of Table Page actions pane
  mathesar_ui/src/components/EntityPageHeader.svelte
  mathesar_ui/src/pages/table/TablePage.svelte
  mathesar_ui/src/routes/TableRoute.svelte
  mathesar_ui/src/systems/table-view/actions-pane/ActionsPane.svelte
  mathesar_ui/src/systems/table-view/actions-pane/SummarizationLink.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/filter/FilterDropdown.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/group/GroupDropdown.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/sort/SortDropdown.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/TableActions.svelte
Labels: status: review

#2246 Grouping and Sorting options in column header's context menu
  mathesar_ui/src/components/sort-entry/SortEntry.svelte
  mathesar_ui/src/components/sort-entry/types.ts
  mathesar_ui/src/components/sort-entry/utils.ts
  mathesar_ui/src/systems/table-view/header/Header.svelte
  mathesar_ui/src/systems/table-view/header/header-cell/ColumnHeaderContextMenu.svelte
Labels: status: waiting

#2335 More premade explorations
  demo/install/explorations.py
Labels: status: review

#2331 Fix API error response when filtering on an invalid date
  mathesar/api/db/viewsets/records.py
Labels: status: review

#2330 Add user data to `common_data`
  mathesar/api/ui/viewsets/users.py
  mathesar/views.py
Labels: status: review

#2340 Fix bug filtering a grouped table page
  mathesar_ui/src/api/types/tables/records.ts
  mathesar_ui/src/stores/table-data/records.ts
Labels: status: review

#2338 Prevent users from supplying PK values to new records via the Record Selector
  mathesar_ui/src/systems/record-selector/RecordSelectorContent.svelte
Labels: status: review

#2361 Fix name constraint preventing updates to UIQueries
  mathesar/api/serializers/queries.py
Labels: work: backend, status: review

#2252 Add autoincrement to existing integer primary key column of an import
  db/columns/utils.py
  db/tables/operations/alter.py
  db/tables/operations/split.py
  mathesar/imports/csv.py
  mathesar/tests/api/test_table_api.py
  mathesar/tests/conftest.py
  mathesar/tests/data/table_with_id_col.csv
Labels: status: review

#2366 Don't auto-activate the first cell within a widget
  mathesar_ui/src/systems/table-view/TableView.svelte
Labels: status: review
