Repository mathesar-foundation/mathesar, pull requests merged in 2023-06, with the labels that each got.

#2898 Add warnings to activate python environment when restarting the shell
  docs/docs/installation/build-from-source/index.md
Labels: status: review

#2904 Improvements to the "Connecting to Existing database" documentation
  docs/docs/configuration/connect-to-existing-db.md
  docs/docs/configuration/customize-docker-compose.md
  docs/docs/configuration/env-variables.md
Labels: status: review

#2836 Fix caret out of view when using Input on Chrome
  mathesar_ui/src/component-library/formatted-input/FormattedInput.svelte
  mathesar_ui/src/component-library/formatted-input/scrollCaretIntoView/README.md
  mathesar_ui/src/component-library/formatted-input/scrollCaretIntoView/README.svg
  mathesar_ui/src/component-library/formatted-input/scrollCaretIntoView/index.ts
  mathesar_ui/src/component-library/formatted-input/scrollCaretIntoView/scrollCaretIntoView.ts
Labels: status: review

#2911 Fix SQL Syntax error while summarizing `Money, URI, Email` column
  db/functions/packed.py
  db/tests/resources/library_without_checkouts.sql
  mathesar/tests/api/query/test_aggregation_functions.py
Labels: status: review

#2906 Added methods to import a perfect JSON
  db/columns/operations/infer_types.py
  db/records/operations/insert.py
  mathesar/imports/json.py
  mathesar/tests/api/conftest.py
  mathesar/tests/api/test_data_file_api.py
  mathesar/tests/api/test_table_api.py
  mathesar/tests/conftest.py
  mathesar/tests/data/data_types.json
  mathesar/tests/display_options_inference/test_money.py
  mathesar/tests/imports/test_csv.py
  mathesar/utils/tables.py
Labels: status: waiting

#2923 Add SQL for column adding
  db/sql/0_msar.sql
  db/sql/run_tests.sh
  db/sql/test_0_msar.sql
Labels: status: review

#2924 Add NPM as a dependency when building from source + Troubleshooting instructions
  docs/docs/installation/build-from-source/index.md
Labels: status: waiting

#2893 Add `Sum` aggregation function
  db/functions/base.py
  mathesar/models/query.py
  mathesar/tests/api/query/test_aggregation_functions.py
  mathesar/tests/api/query/test_library_demo_reports.py
  mathesar_ui/src/api/types/queries.ts
  mathesar_ui/src/stores/abstract-types/index.ts
  mathesar_ui/src/stores/abstract-types/operations/summarization.ts
  mathesar_ui/src/stores/abstract-types/types.ts
  mathesar_ui/src/systems/data-explorer/QuerySummarizationTransformationModel.ts
  mathesar_ui/src/systems/data-explorer/input-sidebar/transformations-pane/summarization/Aggregation.svelte
  mathesar_ui/src/systems/data-explorer/utils.ts
Labels: status: review

#2930 SQL Output type bugfix
  db/sql/0_msar.sql
Labels: status: review

#2932 Add `median` aggregation function
  db/functions/base.py
  mathesar/models/query.py
  mathesar/tests/api/query/test_aggregation_functions.py
  mathesar_ui/src/api/types/queries.ts
  mathesar_ui/src/stores/abstract-types/operations/summarization.ts
Labels: status: review

#2940 Add `Mode` aggregation function
  db/functions/base.py
  mathesar/models/query.py
  mathesar/tests/api/query/test_aggregation_functions.py
  mathesar_ui/src/api/types/queries.ts
  mathesar_ui/src/stores/abstract-types/operations/summarization.ts
Labels: status: review

#2945 Add `Percentage True` aggregation function
  conftest.py
  db/functions/base.py
  db/tests/resources/fraudulent_payments.sql
  mathesar/models/query.py
  mathesar/tests/api/conftest.py
  mathesar/tests/api/query/test_aggregation_functions.py
  mathesar_ui/src/api/types/queries.ts
  mathesar_ui/src/stores/abstract-types/operations/summarization.ts
Labels: status: review

#2912 Add `max` aggregation function
  db/functions/base.py
  mathesar/models/query.py
  mathesar/tests/api/query/test_aggregation_functions.py
  mathesar_ui/src/api/types/queries.ts
  mathesar_ui/src/stores/abstract-types/operations/summarization.ts
Labels: status: review

#2914 Add `min` aggregation function
  db/functions/base.py
  mathesar/models/query.py
  mathesar/tests/api/query/test_aggregation_functions.py
  mathesar_ui/src/api/types/queries.ts
  mathesar_ui/src/stores/abstract-types/operations/summarization.ts
Labels: status: review

#2916 Add `mean` aggregation function
  db/functions/base.py
  mathesar/models/query.py
  mathesar/tests/api/query/test_aggregation_functions.py
  mathesar_ui/src/api/types/queries.ts
  mathesar_ui/src/stores/abstract-types/operations/summarization.ts
Labels: status: review

#2926 Removed code duplication while importing datafiles
  mathesar/imports/base.py
  mathesar/imports/csv.py
  mathesar/imports/json.py
  mathesar/imports/utils.py
  mathesar/tests/conftest.py
  mathesar/tests/imports/test_csv.py
  mathesar/utils/tables.py
Labels: affects: technical debt, status: review

#2933 Added tests to check importing json feature
  mathesar/tests/api/test_data_file_api.py
  mathesar/tests/conftest.py
  mathesar/tests/imports/test_json.py
Labels: status: review

#2952 Move constraint creation to SQL
  db/constraints/base.py
  db/constraints/operations/create.py
  db/constraints/utils.py
  db/sql/0_msar.sql
  db/sql/test_0_msar.sql
  db/tests/constraints/operations/test_create.py
  mathesar/api/serializers/constraints.py
  mathesar/models/base.py
  mathesar/tests/api/test_constraint_api.py
Labels: status: review

#2957 Fix default value input stealing focus
  mathesar_ui/src/components/cell-fabric/data-types/components/money/MoneyCellInput.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/number/NumberCellInput.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/filter/Filter.svelte
Labels: status: review

#2937 Update documentation styles for active and hover
  docs/docs/stylesheets/extra.css
Labels: status: review

#2970 Added the command that generates the API documentation schema file to…
  mathesar/api/README.md
Labels: work: documentation, status: review

#2972 Added the command to copy the .env file, to the DEVELOPER GUIDE
  DEVELOPER_GUIDE.md
Labels: work: documentation, type: enhancement, status: review

#2956 Add `max_split=1` to retrieve the column name
  mathesar_ui/src/components/sheet/SheetSelection.ts
Labels: status: review
