Repository mathesar-foundation/mathesar, pull requests merged in 2023-03, with the labels that each got.

#2484 Backend crash prevention when ordering by a non orderable.
  db/records/operations/sort.py
  db/tests/conftest.py
  db/tests/resources/json_without_pkey.sql
  db/tests/transforms/test_json_without_pkey.py
Labels: status: review, status: waiting

#2601 Improvements to docs
  docs/docs/installation-dc/administration.md
  docs/docs/installation-dc/ansible-setup.md
  docs/docs/installation-dc/quickstart.md
  docs/docs/installation-dc/troubleshooting.md
  docs/docs/installation-dc/under-the-hood.md
  docs/docs/installation-dc/windows-setup.md
  docs/docs/installation/docker-compose.md
  docs/mkdocs.yml
Labels: status: review

#2602 Install.sh usablity fixes
  docker-compose.yml
  install.sh
Labels: status: review

#2579 Caddy Watchtower-related fixes
  Caddyfile
  docker-compose.yml
Labels: status: review

#2584 Fix prod exposing 8000 to host
  docker-compose.yml
Labels: status: review

#2611 Optimize stale constraint lookup
  mathesar/state/django.py
Labels: work: backend, status: review

#2616 Added demo link to README
  README.md
Labels: status: review

#2612 More updates to the docs
  .github/FUNDING.yml
  docs/docs/contributing/welcome.md
  docs/docs/index.md
  docs/docs/installation-dc/quickstart.md
  docs/docs/product/syncing-db.md
  docs/mkdocs.yml
Labels: status: review

#2412 added clarify message that record selector only displays the first 10 records.
  mathesar_ui/src/systems/record-selector/RecordSelectorContent.svelte
Labels: status: review

#2618 Mathesar uninstall docs
  docs/docs/installation-dc/troubleshooting.md
  docs/docs/installation-dc/uninstall.md
  docs/mkdocs.yml
Labels: status: waiting

#2609 Add more `install.sh` fixes
  db/install.py
  install.sh
Labels: status: review

#2606 Update all command in mathesar_ui/README.md to use lastest container (mathesar_service_dev)
  mathesar_ui/README.md
Labels: status: review

#2462 Added navigation link to group header
  mathesar_ui/src/systems/table-view/row/GroupHeaderCellValue.svelte
Labels: status: review

#2591 [#1840] Fix for a11y issue (invalid HTML) in SchemaRow.svelte
  mathesar_ui/src/component-library/dropdown/Dropdown.svelte
  mathesar_ui/src/pages/database/SchemaRow.svelte
Labels: status: review

#2421 Adds more space at the bottom of the Schema Page
  mathesar_ui/src/pages/schema/SchemaPage.svelte
Labels: status: review

#2409 Convert style variable --input-element-text-align into a prop
  mathesar_ui/src/component-library/common/utils/index.ts
  mathesar_ui/src/component-library/common/utils/styleUtils.ts
  mathesar_ui/src/component-library/commonTypes.ts
  mathesar_ui/src/component-library/text-input/TextInput.svelte
  mathesar_ui/src/component-library/text-input/TextInputTypes.ts
  mathesar_ui/src/components/cell-fabric/data-types/components/formatted-input/FormattedInputCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/money/MoneyCellInput.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/number/NumberCellInput.svelte
  mathesar_ui/src/layouts/LayoutWithHeader.svelte
  mathesar_ui/src/utils/typeUtils.ts
Labels: status: review

#2459 Show appropriate breadcrumbs for /administration/users/* pages
  mathesar_ui/src/icons/index.ts
  mathesar_ui/src/pages/admin-users/AdminNavigation.svelte
  mathesar_ui/src/pages/admin-users/EditUserPage.svelte
  mathesar_ui/src/pages/admin-users/NewUserPage.svelte
  mathesar_ui/src/routes/AdminRoute.svelte
  mathesar_ui/src/routes/UsersRoute.svelte
Labels: status: review

#2461 improve styles in explorations listing and users listing
  mathesar_ui/src/component-library/skeleton/Skeleton.svelte
  mathesar_ui/src/components/EntityContainerWithFilterBar.svelte
  mathesar_ui/src/pages/admin-users/UserListingPage.svelte
  mathesar_ui/src/pages/admin-users/UserRow.svelte
  mathesar_ui/src/pages/admin-users/UserSkeleton.svelte
  mathesar_ui/src/pages/schema/ExplorationItem.svelte
  mathesar_ui/src/pages/schema/ExplorationsList.svelte
  mathesar_ui/src/pages/schema/SchemaExplorations.svelte
  mathesar_ui/src/pages/schema/SchemaTables.svelte
Labels: status: review

#2643 Cancel edits when Esc key is pressed while editing cell
  mathesar_ui/src/components/cell-fabric/data-types/components/SteppedInputCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/date-time/DateTimeCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/formatted-input/FormattedInputCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/money/MoneyCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/number/NumberCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/textarea/TextAreaCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/textbox/TextBoxCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/uri/UriCell.svelte
Labels: status: review

#2213 Reorder columns frontend
  mathesar_ui/src/api/types/tables.ts
  mathesar_ui/src/components/sheet/SheetCellResizer.svelte
  mathesar_ui/src/components/sheet/SheetSelection.ts
  mathesar_ui/src/pages/record/TableWidget.svelte
  mathesar_ui/src/pages/record/Widgets.svelte
  mathesar_ui/src/pages/table/TablePage.svelte
  mathesar_ui/src/stores/table-data/tabularData.ts
  mathesar_ui/src/stores/tables.ts
  mathesar_ui/src/systems/data-explorer/QueryRunner.ts
  mathesar_ui/src/systems/record-selector/RecordSelectorWindow.svelte
  mathesar_ui/src/systems/table-view/TableView.svelte
  mathesar_ui/src/systems/table-view/header/Header.svelte
  mathesar_ui/src/systems/table-view/header/drag-and-drop/Draggable.svelte
  mathesar_ui/src/systems/table-view/header/drag-and-drop/Droppable.svelte
  mathesar_ui/src/systems/table-view/header/drag-and-drop/index.ts
  mathesar_ui/src/systems/table-view/header/header-cell/HeaderCell.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record-summary/FkRecordSummaryConfig.svelte
  mathesar_ui/src/utils/tables.ts
Labels: status: review

#2649 Document restarting the installation
  docs/docs/install/docker-compose/ansible.md
  docs/docs/install/docker-compose/requirements.md
  docs/docs/install/docker-compose/troubleshooting.md
  docs/mkdocs.yml
Labels: status: review

#2641 Add bulk delete endpoint
  db/records/operations/delete.py
  mathesar/api/db/permissions/records.py
  mathesar/api/ui/viewsets/__init__.py
  mathesar/api/ui/viewsets/records.py
  mathesar/models/base.py
  mathesar/tests/api/test_record_api.py
  mathesar/urls.py
Labels: status: review

#2660 Add support for static file serving.
  config/settings/common_settings.py
  mathesar/templates/mathesar/login_base.html
  requirements.txt
Labels: status: review

#2420 Updated schema page to show correct number of skeletons while loading
  mathesar_ui/src/pages/schema/SchemaOverview.svelte
  mathesar_ui/src/pages/schema/SchemaPage.svelte
  mathesar_ui/src/pages/schema/TableSkeleton.svelte
Labels: status: review

#2654 Fix UUID pkeys bug
  db/columns/base.py
  db/tests/columns/test_base.py
Labels: status: review

#2665 Put requirements docs content before installation docs content
  docs/docs/install/docker-compose/index.md
  docs/docs/install/docker-compose/requirements.md
  docs/docs/install/docker-compose/troubleshooting.md
  docs/mkdocs.yml
Labels: status: review

#2669 Fix broken link in docs nav
  docs/mkdocs.yml
Labels: status: review

#2632 Fix toast message when deleting rows
  mathesar_ui/src/component-library/confirmation/Confirmation.svelte
  mathesar_ui/src/stores/table-data/records.ts
Labels: status: review

#2645 Focus indicator for boolean button in record selector
  mathesar_ui/src/systems/record-selector/RecordSelectorColumnHeaderCell.svelte
Labels: status: review

#2678 Make frontend access level precedence consistent with backend
  .github/workflows/handle-required-checks.yml
  .github/workflows/run-lint-audit-tests-ui.yml
  .github/workflows/test-docs.yml
  docs/docs/product/users.md
  mathesar_ui/src/component-library/modal/IndependentModal.scss
  mathesar_ui/src/component-library/modal/IndependentModal.svelte
  mathesar_ui/src/component-library/modal/modalTypes.ts
  mathesar_ui/src/pages/schema/SchemaAccessControlModal.svelte
  mathesar_ui/src/stores/users.ts
  mathesar_ui/src/systems/users-and-permissions/AccessControlRow.svelte
  mathesar_ui/src/systems/users-and-permissions/AccessControlView.svelte
  mathesar_ui/src/utils/permissions.ts
Labels: status: review

#2671 Remove boolean inference DAG leaf
  db/columns/operations/infer_types.py
  db/tests/tables/operations/test_infer_types.py
Labels: status: review

#2676 Restrict password changes when running on Demo mode.
  demo/settings.py
  demo/urls.py
  mathesar/users/password_reset.py
Labels: status: review

#2667 Trim data before serializing into Exploration URL
  mathesar_ui/src/systems/data-explorer/urlSerializationUtils.ts
Labels: status: review

#2681 Empty Columns skip type inference
  db/columns/operations/infer_types.py
  db/columns/operations/select.py
  db/tests/tables/operations/test_infer_types.py
Labels: status: waiting

#2653 Be smarter about preventing dropdowns from overflowing the viewport
  mathesar_ui/src/component-library/common/actions/popper.ts
  mathesar_ui/src/component-library/dropdown/AttachableDropdown.svelte
  mathesar_ui/src/component-library/dropdown/Dropdown.scss
  mathesar_ui/src/component-library/dropdown/Dropdown.svelte
  mathesar_ui/src/component-library/tooltip/Tooltip.svelte
  mathesar_ui/src/component-library/tooltip/TooltipAction.ts
  mathesar_ui/src/component-library/truncate/Truncate.svelte
  mathesar_ui/src/pages/schema/TableCard.svelte
Labels: status: review

#2659 Support long column names in CSV imports
  mathesar/imports/csv.py
  mathesar/tests/data/long_column_names.csv
  mathesar/tests/imports/test_csv.py
Labels: work: backend, status: review

#2694 Clear new records array after deleting a record
  mathesar_ui/src/stores/table-data/records.ts
Labels: status: waiting

#2515 Move cell selection to Newly created Record's first Non primary cell
  mathesar_ui/src/components/sheet/SheetSelection.ts
  mathesar_ui/src/systems/table-view/StatusPane.svelte
  mathesar_ui/src/systems/table-view/row/Row.svelte
Labels: status: review

#2683 Modifying the documentation to include a workaround for bash error- line endings problem
  docs/docs/contributing/local-dev.md
Labels: status: review

#2719 Fixes Record page form when PK is not an integer
  mathesar_ui/src/components/breadcrumb/BreadcrumbItem.svelte
  mathesar_ui/src/components/breadcrumb/breadcrumbTypes.ts
  mathesar_ui/src/pages/record/RecordPageContent.svelte
  mathesar_ui/src/pages/record/RecordStore.ts
  mathesar_ui/src/pages/record/TableWidget.svelte
  mathesar_ui/src/pages/record/Widgets.svelte
  mathesar_ui/src/routes/RecordPageRoute.svelte
  mathesar_ui/src/routes/TableRoute.svelte
Labels: priority: urgent, status: review

#2710 Add Sponsors section to README
  README.md
Labels: status: review

#2696 Update all command in local development contribution guide to use the correct container #2693
  docs/docs/contributing/local-dev.md
Labels: status: review

#2731 Reverts #2213 Column reorder from 0.1.1
  mathesar_ui/src/api/types/tables.ts
  mathesar_ui/src/components/sheet/SheetCellResizer.svelte
  mathesar_ui/src/components/sheet/SheetSelection.ts
  mathesar_ui/src/pages/record/TableWidget.svelte
  mathesar_ui/src/pages/record/Widgets.svelte
  mathesar_ui/src/pages/table/TablePage.svelte
  mathesar_ui/src/stores/table-data/tabularData.ts
  mathesar_ui/src/stores/tables.ts
  mathesar_ui/src/systems/data-explorer/QueryRunner.ts
  mathesar_ui/src/systems/record-selector/RecordSelectorWindow.svelte
  mathesar_ui/src/systems/table-view/TableView.svelte
  mathesar_ui/src/systems/table-view/header/Header.svelte
  mathesar_ui/src/systems/table-view/header/drag-and-drop/Draggable.svelte
  mathesar_ui/src/systems/table-view/header/drag-and-drop/Droppable.svelte
  mathesar_ui/src/systems/table-view/header/drag-and-drop/index.ts
  mathesar_ui/src/systems/table-view/header/header-cell/HeaderCell.svelte
  mathesar_ui/src/systems/table-view/table-inspector/record-summary/FkRecordSummaryConfig.svelte
  mathesar_ui/src/utils/tables.ts
Labels: status: review

#2690 Removing SQLAlchemy 1
  conftest.py
  db/connection.py
  db/constants.py
  db/install.py
  db/schemas/operations/select.py
  db/sql/0_msar.sql
  db/sql/1_msar_joinable_tables.sql
  db/sql/2_msar_views.sql
  db/sql/install.py
  db/tables/operations/alter.py
  db/tables/operations/drop.py
  db/tests/tables/operations/test_drop.py
  requirements.txt
Labels: status: waiting

#2625 Added password validation functionality to install.sh
  install.sh
Labels: status: review

#2749 [#2748]Fix for /map_imported_columns API throwing 500 error #2749
  mathesar/api/db/viewsets/tables.py
  mathesar/models/base.py
Labels: status: review

#2640 Add client side validations for email and username
  mathesar_ui/src/components/form/validators.ts
  mathesar_ui/src/systems/users-and-permissions/UserDetailsForm.svelte
Labels: status: review

#2757 Update icon in exploration editor breadcrumb
  mathesar_ui/src/routes/DataExplorerRoute.svelte
Labels: status: review

#2750 [#2355] Part 1- Fixes for Icon type in filter, sort and group
  mathesar_ui/src/components/filter-entry/FilterEntry.svelte
  mathesar_ui/src/components/group-entry/GroupEntry.svelte
  mathesar_ui/src/components/sort-entry/SortEntry.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/filter/FilterEntries.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/group/Group.svelte
  mathesar_ui/src/systems/table-view/actions-pane/record-operations/sort/Sort.svelte
Labels: status: review

#2759 Added support for semicolon-separated value files
  mathesar/imports/csv.py
  mathesar/tests/data/csv_parsing/patents_invalid.csv
Labels: status: review
