Repository mathesar-foundation/mathesar, pull requests merged in 2023-08, with the labels that each got.

#3118 Repeat failed tests
  .github/workflows/run-pytest.yml
  mathesar/tests/integration/README.md
  mathesar/tests/integration/__init__.py
  mathesar/tests/integration/conftest.py
  mathesar/tests/integration/test_base_page.py
  mathesar/tests/integration/test_boolean_type.py
  mathesar/tests/integration/test_columns.py
  mathesar/tests/integration/test_constraints.py
  mathesar/tests/integration/test_imports.py
  mathesar/tests/integration/test_records.py
  mathesar/tests/integration/test_schemas.py
  mathesar/tests/integration/test_scroll_state.py
  mathesar/tests/integration/test_tables.py
  mathesar/tests/integration/test_text_type.py
  mathesar/tests/integration/test_ui.py
  mathesar/tests/integration/utils/component_actions.py
  mathesar/tests/integration/utils/locators.py
  mathesar/tests/integration/utils/table_actions.py
  mathesar/tests/integration/utils/validators.py
  run_pytest.sh
  setup.cfg
Labels: status: review

#3120 Tests for links & constraints ddl
  db/sql/test_0_msar.sql
  db/tests/constraints/operations/test_create.py
  db/tests/constraints/operations/test_drop.py
  db/tests/links/operations/test_create.py
Labels: status: review

#3125 Properly detect identity columns
  db/columns/operations/select.py
  db/sql/0_msar.sql
  db/sql/test_0_msar.sql
Labels: status: review

#3126 Add pldebugger to dev db
  Dockerfile.devdb
  docker-compose.dev.yml
Labels: affects: dx, work: backend, status: review

#3059 Added functionality to import perfect Excel
  db/records/operations/insert.py
  mathesar/api/exceptions/database_exceptions/exceptions.py
  mathesar/api/exceptions/error_codes.py
  mathesar/imports/base.py
  mathesar/imports/csv.py
  mathesar/imports/excel.py
  mathesar/imports/json.py
  mathesar/imports/utils.py
  mathesar/tests/data/patents.xlsx
  mathesar/utils/datafiles.py
  requirements.txt
Labels: status: review

#3119 Move table splitting logic to SQL
  db/sql/0_msar.sql
  db/sql/test_0_msar.sql
  db/tables/operations/split.py
  db/tests/columns/operations/test_alter.py
  db/tests/tables/operations/test_split.py
  mathesar/models/base.py
Labels: status: waiting

#3130 Wiring sql functions for links and tables
  db/links/operations/create.py
  db/sql/0_msar.sql
  db/tables/operations/create.py
  db/tests/columns/operations/test_alter.py
  db/tests/links/operations/test_create.py
  db/tests/records/operations/test_select.py
  db/tests/tables/operations/test_alter.py
  db/tests/tables/operations/test_create.py
  db/tests/tables/operations/test_infer_types.py
  mathesar/api/serializers/links.py
  mathesar/api/serializers/tables.py
  mathesar/imports/csv.py
  mathesar/imports/excel.py
  mathesar/imports/json.py
  mathesar/tests/conftest.py
  mathesar/tests/imports/test_csv.py
  mathesar/tests/imports/test_json.py
  mathesar/utils/tables.py
Labels: status: review

#3100 [i18n] RichText component
  mathesar_ui/src/components/rich-text/RichText.svelte
  mathesar_ui/src/components/rich-text/__tests__/richTextUtils.test.ts
  mathesar_ui/src/components/rich-text/index.ts
  mathesar_ui/src/components/rich-text/richTextUtils.ts
  mathesar_ui/src/i18n/en/index.ts
  mathesar_ui/src/i18n/i18n-types.ts
  mathesar_ui/src/systems/table-view/link-table/LinkTypeOption.svelte
Labels: status: review

#3127 UI for creating & managing shares for tables and explorations
  mathesar/api/ui/permissions/shares.py
  mathesar/tests/api/test_shared_tables.py
  mathesar_ui/src/api/queryShares.ts
  mathesar_ui/src/api/shares.ts
  mathesar_ui/src/api/tableShares.ts
  mathesar_ui/src/api/utils/errors.ts
  mathesar_ui/src/component-library/common/styles/components/input.scss
  mathesar_ui/src/component-library/modal/ControlledModal.svelte
  mathesar_ui/src/component-library/modal/IndependentModal.svelte
  mathesar_ui/src/component-library/modal/ModalController.ts
  mathesar_ui/src/components/Errors.svelte
  mathesar_ui/src/components/form/FieldErrors.svelte
  mathesar_ui/src/components/form/FormSubmit.svelte
  mathesar_ui/src/icons/index.ts
  mathesar_ui/src/pages/exploration/ExplorationPage.svelte
  mathesar_ui/src/pages/exploration/Header.svelte
  mathesar_ui/src/pages/exploration/ShareExplorationDropdown.svelte
  mathesar_ui/src/pages/table/TablePage.svelte
  mathesar_ui/src/routes/urls.ts
  mathesar_ui/src/systems/shares/ShareEntity.svelte
  mathesar_ui/src/systems/table-view/actions-pane/ActionsPane.svelte
  mathesar_ui/src/systems/table-view/actions-pane/ShareTableDropdown.svelte
Labels: status: review

#3064 Allow usage of local.py for untracked settings
  .gitignore
  config/settings/development.py
  config/settings/production.py
Labels: status: review

#3136 Fix `NaN:NaN` error while aggregating duration column
  conftest.py
  db/tests/resources/marathon_athletes.sql
  db/types/custom/datetime.py
  mathesar/tests/api/conftest.py
  mathesar/tests/api/query/test_aggregation_functions.py
Labels: status: review

#3139 Tests for alter table
  db/sql/test_0_msar.sql
  db/tests/tables/operations/test_alter.py
Labels: status: review

#3044 Added OpenAPI spec for datafiles endpoint
  config/settings/common_settings.py
  config/settings/openapi.py
  schema.yml
Labels: type: enhancement, work: backend, status: waiting

#3047 Added OpenAPI specification for databases endpoint
  config/settings/openapi.py
  schema.yml
Labels: type: enhancement, work: backend, status: ready

#3050 Make column type inference optional
  mathesar_ui/src/api/columns.ts
  mathesar_ui/src/api/dataFiles.ts
  mathesar_ui/src/api/types/dataFiles.ts
  mathesar_ui/src/api/utils/requestUtils.ts
  mathesar_ui/src/component-library/fieldset-group/FieldsetGroup.scss
  mathesar_ui/src/component-library/fieldset-group/FieldsetGroup.svelte
  mathesar_ui/src/component-library/file-upload/FileUpload.scss
  mathesar_ui/src/component-library/file-upload/FileUpload.svelte
  mathesar_ui/src/component-library/radio-group/RadioGroup.svelte
  mathesar_ui/src/components/message-boxes/InfoBox.svelte
  mathesar_ui/src/components/sheet/Sheet.svelte
  mathesar_ui/src/i18n/en/index.ts
  mathesar_ui/src/i18n/i18n-types.ts
  mathesar_ui/src/icons/index.ts
  mathesar_ui/src/pages/import-preview/ImportPreviewPage.svelte
  mathesar_ui/src/pages/import-upload/ImportUploadPage.svelte
  mathesar_ui/src/pages/import-upload/UploadViaClipboard.svelte
  mathesar_ui/src/pages/import-upload/UploadViaFile.svelte
  mathesar_ui/src/pages/import-upload/UploadViaUrl.svelte
  mathesar_ui/src/pages/import/column-names/ColumnNamingStrategyInput.svelte
  mathesar_ui/src/pages/import/column-names/LabelNoHeaderRow.svelte
  mathesar_ui/src/pages/import/column-names/LabelYesHeaderRow.svelte
  mathesar_ui/src/pages/import/inference/ColumnTypeInferenceInput.svelte
  mathesar_ui/src/pages/import/inference/LabelInferenceFalse.svelte
  mathesar_ui/src/pages/import/inference/LabelInferenceTrue.svelte
  mathesar_ui/src/pages/import/preview/ErrorInfo.svelte
  mathesar_ui/src/pages/import/preview/ImportPreviewContent.svelte
  mathesar_ui/src/pages/import/preview/ImportPreviewLayout.svelte
  mathesar_ui/src/pages/import/preview/ImportPreviewPage.svelte
  mathesar_ui/src/pages/import/preview/ImportPreviewSheet.svelte
  mathesar_ui/src/pages/import/preview/PreviewColumn.svelte
  mathesar_ui/src/pages/import/preview/importPreviewPageUtils.ts
  mathesar_ui/src/pages/import/upload/DataFileInput.svelte
  mathesar_ui/src/pages/import/upload/ImportUploadPage.svelte
  mathesar_ui/src/pages/import/upload/uploadUtils.ts
  mathesar_ui/src/pages/schema/TableCard.svelte
  mathesar_ui/src/routes/ImportRoute.svelte
  mathesar_ui/src/routes/urls.ts
  mathesar_ui/src/stores/AsyncStore.ts
  mathesar_ui/src/stores/tables.ts
  mathesar_ui/src/systems/table-view/TableView.svelte
  mathesar_ui/src/utils/tables.ts
Labels: status: review

#3129 Fix db list permissions in demo mode
  demo/README.md
  demo/middleware.py
  demo/utils.py
  mathesar/database/base.py
  mathesar/views.py
Labels: affects: ux, work: backend, status: waiting

#3171 Merge db list demo mode commits into release 0.1.3
  demo/README.md
  demo/middleware.py
  demo/utils.py
  mathesar/database/base.py
  mathesar/views.py
Labels: status: review

#3175 Fix regression: Move UserProfile to the App level context from Route level context
  mathesar_ui/src/App.svelte
  mathesar_ui/src/AppContext.svelte
  mathesar_ui/src/routes/AnonymousAccessRoutes.svelte
  mathesar_ui/src/routes/AuthenticatedRoutes.svelte
  mathesar_ui/src/routes/RootRoute.svelte
Labels: priority: urgent, status: review

#3168 Add constraint copying to column extration logic
  db/sql/0_msar.sql
  db/sql/test_0_msar.sql
Labels: priority: urgent, status: review

#3083 Added tests for importing perfect excel feature
  mathesar/tests/api/test_data_file_api.py
  mathesar/tests/api/test_table_api.py
  mathesar/tests/conftest.py
  mathesar/tests/imports/test_excel.py
Labels: status: waiting
