Repository mathesar-foundation/mathesar, pull requests merged in 2024-01, with the labels that each got.

#3177 Updated `oid` and `column_order` fields to only allow positive integers
  mathesar/api/exceptions/error_codes.py
  mathesar/api/exceptions/validation_exceptions/exceptions.py
  mathesar/api/serializers/table_settings.py
  mathesar/migrations/0011_auto_20240103_2120.py
  mathesar/models/base.py
  mathesar/tests/api/test_table_settings_api.py
Labels: pr-status: revision

#3377 Fix bug while deleting the database connection
  mathesar/api/db/viewsets/databases.py
  mathesar/tests/api/test_database_api.py
Labels: pr-status: revision

#3351 Add loading and error indicators for the database page
  mathesar_ui/src/pages/database/DatabaseDetails.svelte
  mathesar_ui/src/pages/database/SchemaListSkeleton.svelte
  mathesar_ui/src/stores/schemas.ts
Labels: pr-status: review

#3319 New DB connection form
  mathesar_ui/.eslintrc.cjs
  mathesar_ui/src/AppTypes.ts
  mathesar_ui/src/api/connections.ts
  mathesar_ui/src/component-library/checkbox-group/CheckboxGroup.svelte
  mathesar_ui/src/component-library/common/utils/typeUtils.ts
  mathesar_ui/src/component-library/fieldset-group/FieldsetGroup.scss
  mathesar_ui/src/component-library/fieldset-group/FieldsetGroup.svelte
  mathesar_ui/src/component-library/index.ts
  mathesar_ui/src/component-library/labeled-input/LabeledInput.scss
  mathesar_ui/src/component-library/labeled-input/LabeledInput.svelte
  mathesar_ui/src/component-library/list-box/ListBoxTypes.ts
  mathesar_ui/src/component-library/margin-trim/MarginTrim.svelte
  mathesar_ui/src/component-library/radio-group/RadioGroup.svelte
  mathesar_ui/src/component-library/render/Render.svelte
  mathesar_ui/src/component-library/render/RenderComponentWithProps.svelte
  mathesar_ui/src/component-library/select/Select.svelte
  mathesar_ui/src/component-library/select/SelectTypes.ts
  mathesar_ui/src/component-library/string-or-component/StringOrComponent.svelte
  mathesar_ui/src/components/breadcrumb/DatabaseSelector.svelte
  mathesar_ui/src/components/form/Field.svelte
  mathesar_ui/src/components/form/FieldHelp.svelte
  mathesar_ui/src/components/form/GridFormInput.svelte
  mathesar_ui/src/components/form/GridFormInputRow.svelte
  mathesar_ui/src/components/grid-form/GridForm.svelte
  mathesar_ui/src/components/grid-form/GridFormDivider.svelte
  mathesar_ui/src/components/grid-form/GridFormLabelRow.svelte
  mathesar_ui/src/components/grid-form/index.ts
  mathesar_ui/src/i18n/languages/en/dict.json
  mathesar_ui/src/pages/connections/ConnectionsPage.svelte
  mathesar_ui/src/routes/AuthenticatedRoutes.svelte
  mathesar_ui/src/routes/DatabaseRoute.svelte
  mathesar_ui/src/stores/databases.ts
  mathesar_ui/src/systems/connections/AddConnection.svelte
  mathesar_ui/src/systems/connections/AddConnectionModal.svelte
  mathesar_ui/src/systems/connections/DeleteConnectionModal.svelte
  mathesar_ui/src/systems/connections/EditConnectionModal.svelte
  mathesar_ui/src/systems/connections/GeneralConnection.svelte
  mathesar_ui/src/systems/connections/generalConnections.ts
  mathesar_ui/src/utils/iterUtils.ts
Labels: pr-status: review

#3388 Improve exception handling while failing to connect to a database
  db/install.py
  demo/management/commands/setup_demo_template_db.py
  mathesar/api/exceptions/database_exceptions/base_exceptions.py
  mathesar/api/exceptions/error_codes.py
  mathesar/exception_handlers.py
  mathesar/install.py
  mathesar/utils/connections.py
Labels: pr-status: review

#3324 Revamped docker compose
  Caddyfile
  config/settings/common_settings.py
  config/settings/production.py
  dev-run.sh
  docker-compose.dev.yml
  docker-compose.yml
  run.sh
Labels: pr-status: review

#3399 Fix gh workflow
  .github/workflows/test-and-lint-code.yml
  docker-compose.dev.yml
  mathesar/tests/api/test_table_settings_api.py
Labels: priority: urgent, pr-status: review

#3407 Fix "Primary Key" UI text
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnTypeSpecifierTag.svelte
Labels: pr-status: review

#3410 Remove in-app upgrade feature from UI
  mathesar_ui/src/api/upgrade.ts
  mathesar_ui/src/i18n/languages/en/dict.json
  mathesar_ui/src/pages/admin-update/ReleaseBox.svelte
  mathesar_ui/src/pages/admin-update/upgrade-modal/UpgradeConfirm.svelte
  mathesar_ui/src/pages/admin-update/upgrade-modal/UpgradeError.svelte
  mathesar_ui/src/pages/admin-update/upgrade-modal/UpgradeModal.svelte
  mathesar_ui/src/pages/admin-update/upgrade-modal/UpgradeProcessing.svelte
  mathesar_ui/src/stores/releases.ts
Labels: pr-status: review

#3417 Remove default value for MATHESAR_DATABASES for production setup
  .env.example
  docker-compose.yml
  run.sh
Labels: pr-status: review

#3425 remove remaining SQLAlchemy filters dependencies
  Dockerfile
  Dockerfile.integ-tests
  db/records/exceptions.py
  db/records/operations/select.py
  mathesar/api/db/viewsets/records.py
Labels: pr-status: review

#3422 Version 0.1.4
  docker-compose.yml
  docs/docs/administration/uninstall.md
  docs/docs/administration/upgrade.md
  docs/docs/administration/upgrade/0.1.4.md
  docs/docs/administration/upgrade/older.md
  docs/docs/configuration/connect-to-existing-db.md
  docs/docs/configuration/customize-docker-compose.md
  docs/docs/configuration/env-variables.md
  docs/docs/index.md
  docs/docs/installation/build-from-source/index.md
  docs/docs/installation/docker-compose/index.md
  docs/docs/installation/docker/index.md
  docs/docs/installation/guided-install/index.md
  docs/docs/installation/guided-install/troubleshooting.md
  docs/docs/installation/guided-install/under-the-hood.md
  docs/docs/releases/.gitignore
  docs/docs/releases/0.1.4.md
  docs/docs/releases/README.md
  docs/docs/releases/find_missing_prs.sh
  docs/docs/snippets/docker-compose-administration.md
  docs/docs/snippets/docker-compose-prerequisites.md
  docs/mkdocs.yml
  docs/placeholder-plugin.yaml
  install.sh
Labels: needs: backend approval, needs: frontend approval

#3431 Migration to copy `MATHESAR_DATABASES` credentials
  mathesar/migrations/0006_mathesar_databases_to_model.py
Labels: pr-status: review
