Repository mathesar-foundation/mathesar, pull requests merged in 2024-04, with the labels that each got.

#3523 Add demo target to Dockerfile
  Dockerfile
  demo/settings.py
Labels: pr-status: review

#3526 Navigate to linked table via cell context menu
  mathesar_ui/src/i18n/languages/en/dict.json
  mathesar_ui/src/systems/table-view/header/header-cell/ColumnHeaderContextMenu.svelte
  mathesar_ui/src/systems/table-view/row/RowCell.svelte
Labels: pr-status: revision

#3357 Removed the 'group' suffix in Data Explorer
  mathesar/models/query.py
  mathesar/tests/api/query/test_query_run_partial_transforms.py
Labels: pr-status: revision

#3529 Made release notes script portable.
  docs/docs/releases/README.md
  docs/docs/releases/find_missing_prs.sh
Labels: pr-status: review

#3524 Modern rpc prototype
  .github/workflows/test-and-lint-code.yml
  config/settings/common_settings.py
  docs/docs/api/rest.md
  docs/docs/api/rpc.md
  docs/mkdocs.yml
  docs/requirements.txt
  mathesar/rpc/__init__.py
  mathesar/rpc/connections.py
  mathesar/rpc/exceptions/__init__.py
  mathesar/rpc/exceptions/error_codes.py
  mathesar/rpc/exceptions/handlers.py
  mathesar/tests/rpc/exceptions/test_error_codes.py
  mathesar/tests/rpc/test_connections.py
  mathesar/tests/rpc/test_endpoints.py
  mathesar/urls.py
  mathesar/views.py
  requirements-dev.txt
  requirements.txt
Labels: pr-status: review

#3541 Remove API documentation infrastructure
  config/settings/common_settings.py
  config/settings/openapi.py
  mathesar/api/README.md
  requirements.txt
  schema.yml
Labels: needs: unblocking, pr-status: review

#3546 Remove Debian build
  DEVELOPER_GUIDE.md
  MANIFEST.in
  mathesar/start.py
  pyproject.toml
  release-scripts/__init__.py
  release-scripts/build-debian.sh
  release-scripts/debian/build_virtualenv
  release-scripts/debian/changelog
  release-scripts/debian/control
  release-scripts/debian/mathesar.postinst
  release-scripts/debian/mathesar.service
  release-scripts/debian/rules
  setup/__init__.py
  setup/secret_key_generator.py
Labels: needs: unblocking

#3547 Exception handler tests
  mathesar/tests/rpc/exceptions/test_error_codes.py
  mathesar/tests/rpc/exceptions/test_error_handler.py
Labels: pr-status: review

#3551 Remove E2E infrastructure
  .github/workflows/run-e2e-integ-tests.yml.disabled
  Dockerfile.integ-tests
Labels: pr-status: review
