Repository mathesar-foundation/mathesar, pull requests merged in 2024-10, with the labels that each got.

#3897 Reduces frontend caching, fixes a few bugs
  mathesar/views.py
  mathesar_ui/src/contexts/DatabaseSettingsRouteContext.ts
  mathesar_ui/src/i18n/languages/en/dict.json
  mathesar_ui/src/models/Database.ts
  mathesar_ui/src/pages/database/DatabasePageWrapper.svelte
  mathesar_ui/src/pages/database/permissions/DatabasePermissionsModal.svelte
  mathesar_ui/src/pages/database/schemas/SchemasSection.svelte
  mathesar_ui/src/pages/database/settings/collaborators/AddCollaboratorModal.svelte
  mathesar_ui/src/pages/database/settings/collaborators/CollaboratorRow.svelte
  mathesar_ui/src/pages/database/settings/collaborators/Collaborators.svelte
  mathesar_ui/src/pages/database/settings/collaborators/EditRoleForCollaboratorModal.svelte
  mathesar_ui/src/pages/database/settings/role-configuration/RoleConfiguration.svelte
  mathesar_ui/src/pages/database/settings/roles/CreateRoleModal.svelte
  mathesar_ui/src/pages/database/settings/roles/ModifyRoleMembers.svelte
  mathesar_ui/src/pages/database/settings/roles/RoleRow.svelte
  mathesar_ui/src/pages/database/settings/roles/Roles.svelte
  mathesar_ui/src/pages/import/preview/ImportPreviewContent.svelte
  mathesar_ui/src/pages/schema/SchemaOverview.svelte
  mathesar_ui/src/pages/schema/SchemaPage.svelte
  mathesar_ui/src/pages/schema/SchemaPermissionsModal.svelte
  mathesar_ui/src/stores/AsyncRpcApiStore.ts
  mathesar_ui/src/stores/AsyncStore.ts
  mathesar_ui/src/stores/queries.ts
  mathesar_ui/src/stores/schemas.ts
  mathesar_ui/src/stores/tables.ts
  mathesar_ui/src/systems/permissions/permissionsUtils.ts
  mathesar_ui/src/systems/table-view/link-table/LinkTableForm.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/TablePermissions.svelte
Labels: pr-status: revision

#3909 Fix bug when updating table twice
  mathesar_ui/src/stores/tables.ts
Labels: pr-status: review

#3922 Fix logic in `get_current_role`
  db/sql/00_msar.sql
  db/sql/test_00_msar.sql
Labels: pr-status: review

#3910 Permissions Documentation Updates
  docs/docs/api/rpc.md
  docs/docs/index.md
  docs/docs/user-guide/databases.md
  docs/docs/user-guide/index.md
  docs/docs/user-guide/permissions.md
  docs/docs/user-guide/syncing-db.md
  docs/docs/user-guide/users.md
  docs/mkdocs.yml
Labels: pr-status: review

#3938 Use a semver library to parse our version strings on the front end
  mathesar_ui/package-lock.json
  mathesar_ui/package.json
  mathesar_ui/src/stores/releases.ts
Labels: pr-status: review

#3940 Fix response of `explorations.run` for summarizations
  mathesar/utils/explorations.py
Labels: pr-status: review

#3945 Docs improvements for build from scrach
  docs/docs/installation/build-from-source/index.md
Labels: pr-status: review

#3948 Fixes server errors when RPC exceptions are thrown while rendering common_data
  mathesar/urls.py
  mathesar/views.py
  mathesar_ui/src/stores/schemas.ts
  mathesar_ui/src/stores/tables.ts
  mathesar_ui/src/utils/preloadData.ts
Labels: pr-status: review

#3958 Bugfix msar.set_members
  db/sql/00_msar.sql
Labels: pr-status: review

#3949 Release notes for 0.2.0-testing.1
  docker-compose.yml
  docs/docs/api/rpc.md
  docs/docs/assets/releases/0.2.0-testing.1/create-link-changes.png
  docs/docs/assets/releases/0.2.0-testing.1/db-settings-collaborators.png
  docs/docs/index.md
  docs/docs/installation/build-from-source/index.md
  docs/docs/installation/docker-compose/index.md
  docs/docs/releases/0.2.0-testing.1.md
  docs/mkdocs.yml
Labels: pr-status: review, work: release

#3974 Refactor SQL install script
  db/sql/install.py
Labels: pr-status: review

#3918 Add PostgreSQL 17 to the testing matrix
  .github/workflows/test-and-lint-code.yml
  db/sql/test_00_msar.sql
Labels: pr-status: review

#3968 Fix browser console warnings
  mathesar_ui/src/component-library/common/utils/EventHandler.ts
Labels: pr-status: review

#3971 Fix form state bug in Edit User
  mathesar_ui/src/systems/users/UserDetailsForm.svelte
Labels: pr-status: review

#3966 Fix missing links in cell context menu
  mathesar_ui/src/systems/table-view/row/Row.svelte
  mathesar_ui/src/systems/table-view/row/RowCell.svelte
  mathesar_ui/src/systems/table-view/row/RowContextOptions.svelte
Labels: pr-status: review

#3973 Fix bug when renaming exploration column
  mathesar_ui/src/components/sheet/selection/SheetSelectionStore.ts
Labels: pr-status: review

#3979 Add tests for `exec_msar_func` python wrappers
  db/columns/operations/create.py
  db/schemas/operations/select.py
  db/tests/wrapper/test_exec_wrappers.py
  mathesar/rpc/schemas/base.py
Labels: pr-status: review

#3980 Fix row height calculation during grouping removal
  mathesar_ui/src/systems/table-view/Body.svelte
  mathesar_ui/src/systems/table-view/ScrollAndRowHeightHandler.svelte
Labels: pr-status: review

#3970 Fix action buttons looking disabled
  mathesar_ui/src/component-library/button/Button.scss
Labels: pr-status: review

#3976 SQL comments to index positional arguments
  db/sql/00_msar.sql
Labels: pr-status: review

#3984 Remove `types.list` RPC endpoint
  config/settings/common_settings.py
  currency_info.json
  docs/docs/api/rpc.md
  mathesar/api/display_options.py
  mathesar/data/__init__.py
  mathesar/data/currency_info.json
  mathesar/database/__init__.py
  mathesar/database/types.py
  mathesar/rpc/types.py
  mathesar/tests/rpc/test_endpoints.py
Labels: pr-status: review

#3983 Drop all msar functions at start of install SQL
  db/sql/00_msar.sql
Labels: pr-status: review

#3985 Reduce backend dependencies
  Dockerfile
  config/settings/common_settings.py
  mathesar/api/exceptions/error_codes.py
  mathesar/api/exceptions/mixins.py
  mathesar/exception_handlers.py
  mathesar/install.py
  mathesar/migrations/0006_mathesar_databases_to_model.py
  mathesar/tests/api/test_data_file_api.py
  mathesar/tests/api/test_user_api.py
  mathesar/tests/conftest.py
  mathesar/tests/data/patents.xlsx
  mathesar/urls.py
  mathesar/utils/datafiles.py
  requirements-dev.txt
  requirements-prod.txt
  requirements.txt
  setup.cfg
Labels: pr-status: review

#3978 Backend support for configurable record summaries
  db/records.py
  db/sql/00_msar.sql
  db/sql/test_00_msar.sql
  mathesar/migrations/0019_clear_record_summary_template_values.py
  mathesar/migrations/0020_remove_tablemetadata_record_summary_customized_and_more.py
  mathesar/models/base.py
  mathesar/rpc/records.py
  mathesar/rpc/tables/metadata.py
  mathesar/tests/rpc/tables/test_t_metadata.py
  mathesar/tests/rpc/test_records.py
  mathesar/utils/tables.py
Labels: pr-status: review

#3989 Add python 13 to testing matrix
  .github/workflows/test-and-lint-code.yml
Labels: pr-status: review

#3982 Fix some bugs from milestone testing-2
  mathesar_ui/src/i18n/languages/en/dict.json
  mathesar_ui/src/pages/database/settings/collaborators/Collaborators.svelte
  mathesar_ui/src/pages/schema/TableCard.svelte
  mathesar_ui/src/systems/permissions/overview/AccessControlRow.svelte
  mathesar_ui/src/systems/table-view/constraints/ConstraintTypeSection.svelte
Labels: pr-status: review

#3991 Faster CI for running backend tests
  .github/workflows/test-build.yml
  Dockerfile
  dev-run.sh
  docker-compose.dev.yml
  run_pytest.sh
Labels: pr-status: review

#3996 Small bug fixes in record summary DB code
  db/sql/00_msar.sql
  db/sql/test_00_msar.sql
Labels: pr-status: review
