Repository mathesar-foundation/mathesar, pull requests merged in 2025-09, with the labels that each got.

#4734 Fetch records data when adding a constraint
  mathesar_ui/src/stores/table-data/constraints.ts
  mathesar_ui/src/stores/table-data/tabularData.ts
Labels: pr-status: review

#4762 File attachment upload
  file_storage.yml.example
  mathesar/tests/utils/test_download_links.py
  mathesar/urls.py
  mathesar/utils/download_links.py
  mathesar/views/download_link.py
Labels: pr-status: review

#4746 Clear all statuses and errors when inserting a new row
  mathesar_ui/src/stores/table-data/meta.ts
  mathesar_ui/src/stores/table-data/records.ts
Labels: pr-status: review

#4770 Implement File column configuration
  mathesar_ui/src/api/rpc/explorations.ts
  mathesar_ui/src/components/abstract-type-control/AbstractTypeControl.svelte
  mathesar_ui/src/components/abstract-type-control/AbstractTypeSelector.svelte
  mathesar_ui/src/components/cell-fabric/data-types/arrayFactory.ts
  mathesar_ui/src/components/cell-fabric/data-types/components/typeDefinitions.ts
  mathesar_ui/src/components/cell-fabric/data-types/file.ts
  mathesar_ui/src/components/cell-fabric/data-types/index.ts
  mathesar_ui/src/components/cell-fabric/data-types/typeDefinitions.ts
  mathesar_ui/src/components/cell-fabric/data-types/utils.ts
  mathesar_ui/src/components/cell-fabric/utils.ts
  mathesar_ui/src/components/filter-entry/FilterEntry.svelte
  mathesar_ui/src/components/group-entry/GroupEntry.svelte
  mathesar_ui/src/components/sort-entry/SortEntry.svelte
  mathesar_ui/src/pages/import/preview/importPreviewPageUtils.ts
  mathesar_ui/src/stores/abstract-types/abstractTypeCategories.ts
  mathesar_ui/src/stores/abstract-types/constants.ts
  mathesar_ui/src/stores/abstract-types/index.ts
  mathesar_ui/src/stores/abstract-types/type-configs/file.ts
  mathesar_ui/src/stores/abstract-types/type-configs/json.ts
  mathesar_ui/src/stores/abstract-types/types.ts
  mathesar_ui/src/stores/table-data/columns.ts
  mathesar_ui/src/stores/table-data/processedColumns.ts
  mathesar_ui/src/systems/data-explorer/input-sidebar/column-selection-pane/SelectableColumn.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/transformations-pane/HideTransformation.svelte
  mathesar_ui/src/systems/data-explorer/input-sidebar/transformations-pane/summarization/SummarizationTransformation.svelte
  mathesar_ui/src/systems/data-explorer/utils.ts
  mathesar_ui/src/systems/data-forms/form-maker/data-form-utilities/fields/FieldColumn.ts
  mathesar_ui/src/systems/record-view/TableWidget.svelte
  mathesar_ui/src/systems/record-view/Widgets.svelte
  mathesar_ui/src/systems/table-view/constraints/ForeignKeyConstraintDetails.svelte
  mathesar_ui/src/systems/table-view/header/new-column-cell/ColumnTypeSelector.svelte
  mathesar_ui/src/systems/table-view/header/new-column-cell/NewColumnCell.svelte
  mathesar_ui/src/systems/table-view/table-inspector/column/ColumnType.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/links/ForwardLinkCard.svelte
  mathesar_ui/src/systems/table-view/table-inspector/table/links/ReverseLinkCard.svelte
  mathesar_ui/src/utils/columnUtils.ts
Labels: pr-status: revision

#4776 Prevent file columns from being added to forms
  mathesar_ui/src/i18n/languages/en/dict.json
  mathesar_ui/src/systems/data-forms/form-maker/elements/add-field/AddFormColumnFieldItem.svelte
Labels: pr-status: prepared

#4779 Implement FileInput component for record page
  mathesar_ui/src/components/cell-fabric/DynamicInput.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/file/FileInput.svelte
  mathesar_ui/src/components/cell-fabric/data-types/file.ts
  mathesar_ui/src/components/cell-fabric/data-types/string.ts
  mathesar_ui/src/components/cell-fabric/data-types/typeDefinitions.ts
  mathesar_ui/src/components/cell-fabric/utils.ts
  mathesar_ui/src/components/file-attachments/cell-content/FileCellContent.svelte
  mathesar_ui/src/components/filter-entry/FilterEntry.svelte
  mathesar_ui/src/components/filter-entry/types.ts
  mathesar_ui/src/stores/table-data/processedColumns.ts
  mathesar_ui/src/systems/data-explorer/utils.ts
  mathesar_ui/src/systems/record-selector/RecordSelectorColumnHeaderCell.svelte
  mathesar_ui/src/systems/record-view/DirectField.svelte
  mathesar_ui/src/systems/record-view/RecordStore.ts
  mathesar_ui/src/systems/table-view/table-inspector/column/SetDefaultValue.svelte
Labels: pr-status: prepared

#4780 Polish flow for deleting file from lightbox
  mathesar_ui/src/components/file-attachments/lightbox/Lightbox.svelte
  mathesar_ui/src/i18n/languages/en/dict.json
Labels: pr-status: prepared

#4782 Initial file cell appearance for non-images
  mathesar_ui/src/component-library/common/icons.ts
  mathesar_ui/src/components/file-attachments/cell-content/AttachedFileReference.svelte
  mathesar_ui/src/components/file-attachments/fileUtils.ts
Labels: pr-status: prepared

#4777 Add tooltips in image file viewer when labels are hidden
  mathesar_ui/src/components/file-attachments/lightbox/Lightbox.svelte
Labels: pr-status: prepared

#4786 Fix Key Error for deleted file column
  mathesar/utils/download_links.py
Labels: pr-status: review

#4783 Files non-image cell dropdown
  mathesar_ui/src/AppContext.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/file/FileCell.svelte
  mathesar_ui/src/components/cell-fabric/data-types/components/file/FileInput.svelte
  mathesar_ui/src/components/file-attachments/FileDetail.svelte
  mathesar_ui/src/components/file-attachments/cell-content/AttachedFileReference.svelte
  mathesar_ui/src/components/file-attachments/cell-content/FileCellContent.svelte
  mathesar_ui/src/components/file-attachments/file-detail-dropdown/ControlledFileDetailDropdown.svelte
  mathesar_ui/src/components/file-attachments/file-detail-dropdown/FileDetailDropdown.svelte
  mathesar_ui/src/components/file-attachments/file-detail-dropdown/FileDetailDropdownController.ts
  mathesar_ui/src/components/file-attachments/fileUtils.ts
  mathesar_ui/src/components/file-attachments/lightbox/Lightbox.svelte
Labels: pr-status: review

#4791 Handle race conditions when clicking to preview images
  mathesar_ui/src/components/file-attachments/cell-content/AttachedFileReference.svelte
  mathesar_ui/src/utils/onAnyUiInteraction.ts
Labels: pr-status: review

#4794 Fix file input size for non-images
  mathesar_ui/src/components/cell-fabric/data-types/components/file/FileInput.svelte
Labels: pr-status: review

#4798 Improve lightbox display for extra small images
  mathesar_ui/src/components/file-attachments/lightbox/Lightbox.svelte
Labels: pr-status: review

#4815 Adds foreign key to new records created via paste in the table widget
  mathesar_ui/src/stores/table-data/records.ts
Labels: pr-status: review
